/**
 * Traversal Builder — constructs TraversalConfig from TraversalSourceData
 *
 * Takes the rich source table data generated by calc:sync (from YAML)
 * and builds per-level TraversalConfig with correct join conditions,
 * meaningful narration, and proper EBT hierarchy expansion.
 */

import type { RollupLevelKey, CatalogueItem } from './types';
import type {
  TraversalConfig,
  TraversalTableDef,
  TraversalStep,
  TraversalSourceData,
  TraversalSourceTable,
} from './metric-config';

// ═══════════════════════════════════════════════════════════════
// EBT Hierarchy Expansion
// ═══════════════════════════════════════════════════════════════

/** Synthetic EBT table entries for multi-hop hierarchy traversals. */
const EBT_HIERARCHY: Record<string, { purpose: string; join_on: string }> = {
  ebt: {
    purpose: 'Resolves desk-level segment from the facility\'s LOB assignment',
    join_on: 'ebt.managed_segment_id = fm.lob_segment_id AND ebt.is_current_flag = \'Y\'',
  },
  ebt_l3: {
    purpose: 'Resolves desk-level segment (first hop from facility LOB)',
    join_on: 'ebt_l3.managed_segment_id = fm.lob_segment_id AND ebt_l3.is_current_flag = \'Y\'',
  },
  ebt_l2: {
    purpose: 'Walks up to portfolio-level segment (parent of desk)',
    join_on: 'ebt_l2.managed_segment_id = ebt_l3.parent_segment_id AND ebt_l2.is_current_flag = \'Y\'',
  },
  ebt_l1: {
    purpose: 'Walks up to business segment level (parent of portfolio)',
    join_on: 'ebt_l1.managed_segment_id = ebt_l2.parent_segment_id AND ebt_l1.is_current_flag = \'Y\'',
  },
};

// ═══════════════════════════════════════════════════════════════
// Table Resolution
// ═══════════════════════════════════════════════════════════════

/**
 * Resolve the active tables for a given level.
 * Handles EBT self-join aliases that don't exist in source_tables.
 */
function resolveTablesForLevel(
  levelAliases: string[],
  allTables: TraversalSourceTable[],
): TraversalSourceTable[] {
  const result: TraversalSourceTable[] = [];
  const ebtBase = allTables.find((t) => t.table_name === 'enterprise_business_taxonomy');

  for (const alias of levelAliases) {
    // Direct match from source_tables
    const direct = allTables.find((t) => t.alias === alias);
    if (direct) {
      result.push(direct);
      continue;
    }

    // EBT self-join variant (ebt_l3, ebt_l2, ebt_l1)
    if (alias.startsWith('ebt') && ebtBase) {
      const ebtInfo = EBT_HIERARCHY[alias];
      if (ebtInfo) {
        result.push({
          alias,
          qualified_name: ebtBase.qualified_name,
          table_name: ebtBase.table_name,
          layer: ebtBase.layer,
          join_type: 'LEFT',
          join_on: ebtInfo.join_on,
          fields: ebtBase.fields,
          purpose: ebtInfo.purpose,
        });
      }
    }
  }

  return result;
}

// ═══════════════════════════════════════════════════════════════
// Narration Generation
// ═══════════════════════════════════════════════════════════════

function humanizeTableName(name: string): string {
  return name
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function buildSourceNarration(table: TraversalSourceTable): string {
  const filterFields = table.fields.filter((f) => f.role === 'FILTER');
  const filterDesc = filterFields.length > 0
    ? ` Filtering by ${filterFields.map((f) => f.name.replace(/_/g, ' ')).join(', ')}.`
    : '';
  return `Start with ${humanizeTableName(table.table_name)}. ${table.purpose}.${filterDesc}`;
}

function buildJoinNarration(table: TraversalSourceTable): string {
  const joinLabel = table.join_type === 'LEFT' ? 'Left join' : 'Join';
  return `${joinLabel} to ${humanizeTableName(table.table_name)}. ${table.purpose}.`;
}

function buildCalcNarration(
  level: RollupLevelKey,
  aggType: string | undefined,
  item: CatalogueItem,
): string {
  const levelDef = item.level_definitions?.find((d) => d.level === level);

  // Extract the COMPUTE line from level_logic if available
  const levelLogic = levelDef?.level_logic ?? '';
  const computeMatch = levelLogic.match(/COMPUTE\s*\n\s*(.*)/);
  const computeExpr = computeMatch?.[1]?.trim();

  switch (aggType) {
    case 'SUM':
      return computeExpr
        ? `Aggregate by summing across all facilities in scope: ${computeExpr}`
        : `Aggregate: SUM across all facilities in scope at the ${level} level.`;
    case 'WEIGHTED_AVG':
      return computeExpr
        ? `Compute exposure-weighted average: ${computeExpr}`
        : `Compute exposure-weighted average at the ${level} level.`;
    case 'COUNT':
    case 'COUNT_DISTINCT':
      return `Count distinct entities at the ${level} level.`;
    case 'RAW':
      return computeExpr
        ? `Read directly: ${computeExpr}`
        : `Read value directly — no aggregation needed.`;
    default: // CUSTOM or others
      return computeExpr
        ? `Calculate: ${computeExpr}`
        : `Apply the formula: ${(item.generic_formula ?? '').substring(0, 150)}`;
  }
}

// ═══════════════════════════════════════════════════════════════
// Step Generation
// ═══════════════════════════════════════════════════════════════

function buildStepsForLevel(
  level: RollupLevelKey,
  activeTables: TraversalSourceTable[],
  aggType: string | undefined,
  item: CatalogueItem,
): TraversalStep[] {
  const steps: TraversalStep[] = [];

  for (const table of activeTables) {
    const measureFields = table.fields.filter((f) => f.role === 'MEASURE');
    const dimFields = table.fields.filter((f) => f.role === 'DIMENSION');
    const highlightFields = measureFields.length > 0
      ? measureFields.map((f) => f.name)
      : dimFields.length > 0
        ? dimFields.map((f) => f.name)
        : table.fields.slice(0, 3).map((f) => f.name);

    if (table.join_type === 'BASE') {
      steps.push({
        kind: 'source',
        highlight_table: table.alias,
        highlight_fields: highlightFields,
        narration: buildSourceNarration(table),
      });
    } else {
      // Clean up join_on for display: shorten long conditions
      let joinDisplay = table.join_on ?? undefined;
      if (joinDisplay && joinDisplay.length > 60) {
        // Show just the core join, trim filter conditions
        const parts = joinDisplay.split(' AND ');
        joinDisplay = parts[0];
        if (parts.length > 1) joinDisplay += ' ...';
      }

      steps.push({
        kind: 'join',
        highlight_table: table.alias,
        highlight_fields: highlightFields,
        narration: buildJoinNarration(table),
        join_condition: joinDisplay,
      });
    }
  }

  // Final calculation step
  steps.push({
    kind: 'calc',
    highlight_table: 'calc_output',
    narration: buildCalcNarration(level, aggType, item),
  });

  return steps;
}

// ═══════════════════════════════════════════════════════════════
// Table Definition Building
// ═══════════════════════════════════════════════════════════════

function buildTableDef(table: TraversalSourceTable): TraversalTableDef {
  return {
    id: table.alias,
    name: table.table_name,
    layer: table.layer,
    fields: table.fields.map((f) => ({
      name: f.name,
      sample_value: f.description || f.name,
      is_pk: f.role === 'JOIN_KEY' && f.name.endsWith('_id'),
      is_fk: f.role === 'JOIN_KEY',
    })),
  };
}

// ═══════════════════════════════════════════════════════════════
// Main Builder
// ═══════════════════════════════════════════════════════════════

/**
 * Build a TraversalConfig from TraversalSourceData (generated by calc:sync).
 * Each level gets its own set of tables and steps based on the actual
 * formula_sql, with correct join conditions, EBT hierarchy, and narration.
 */
export function buildTraversalConfig(
  item: CatalogueItem,
  data: TraversalSourceData,
): TraversalConfig {
  const tables: Record<string, TraversalTableDef> = {};
  const dimensionPaths: Partial<Record<RollupLevelKey, TraversalStep[]>> = {};
  const levels: RollupLevelKey[] = ['facility', 'counterparty', 'desk', 'portfolio', 'lob'];

  // Add calc output table
  const abbr = item.abbreviation ?? item.item_id;
  tables['calc_output'] = {
    id: 'calc_output',
    name: `${abbr.toLowerCase()}_result`,
    layer: 'L3',
    fields: [{ name: 'metric_value', sample_value: abbr, is_pk: false, is_fk: false }],
  };

  for (const level of levels) {
    const levelAliases = data.per_level_tables[level];
    if (!levelAliases || levelAliases.length === 0) continue;

    // Resolve tables for this level (including EBT expansion)
    const activeTables = resolveTablesForLevel(levelAliases, data.source_tables);
    if (activeTables.length === 0) continue;

    // Register table defs (union across all levels)
    for (const t of activeTables) {
      if (!tables[t.alias]) {
        tables[t.alias] = buildTableDef(t);
      }
    }

    // Build steps
    const aggType = data.narration_context.aggregation_type_by_level[level];
    dimensionPaths[level] = buildStepsForLevel(level, activeTables, aggType, item);
  }

  return { tables, dimension_paths: dimensionPaths };
}

// ═══════════════════════════════════════════════════════════════
// Fallback Builder (for legacy metrics without YAML)
// ═══════════════════════════════════════════════════════════════

/**
 * Build a basic TraversalConfig from catalogue source_references.
 * Less rich than YAML-based config but better than the old inferTraversalConfig.
 */
export function buildFallbackTraversalConfig(
  item: CatalogueItem,
): TraversalConfig | undefined {
  const levelDef = item.level_definitions?.[0];
  const refs = levelDef?.source_references ?? [];
  if (refs.length === 0 && (!item.ingredient_fields || item.ingredient_fields.length === 0)) {
    return undefined;
  }

  // Group source_references by table
  const byTable = new Map<string, { layer: string; table: string; fields: Array<{ name: string; description: string }> }>();
  for (const ref of refs) {
    const key = `${ref.layer}.${ref.table}`;
    if (!byTable.has(key)) {
      byTable.set(key, { layer: ref.layer, table: ref.table, fields: [] });
    }
    const existing = byTable.get(key)!;
    if (!existing.fields.some((f) => f.name === ref.field)) {
      existing.fields.push({ name: ref.field, description: ref.description || ref.field });
    }
  }

  if (byTable.size === 0) return undefined;

  const tables: Record<string, TraversalTableDef> = {};
  const steps: TraversalStep[] = [];
  let isFirst = true;

  for (const [, info] of byTable) {
    const alias = info.table.split('_').map((w) => w[0]).join('');
    tables[alias] = {
      id: alias,
      name: info.table,
      layer: info.layer as 'L1' | 'L2' | 'L3',
      fields: info.fields.map((f) => ({
        name: f.name,
        sample_value: f.description,
        is_pk: f.name.endsWith('_id'),
        is_fk: f.name.endsWith('_id'),
      })),
    };

    steps.push({
      kind: isFirst ? 'source' : 'join',
      highlight_table: alias,
      highlight_fields: info.fields.slice(0, 3).map((f) => f.name),
      narration: isFirst
        ? `Start with ${humanizeTableName(info.table)}.`
        : `Join to ${humanizeTableName(info.table)} for additional data.`,
    });
    isFirst = false;
  }

  // Add calc step
  const abbr = item.abbreviation ?? item.item_id;
  tables['calc_output'] = {
    id: 'calc_output',
    name: `${abbr.toLowerCase()}_result`,
    layer: 'L3',
    fields: [{ name: 'metric_value', sample_value: abbr, is_pk: false, is_fk: false }],
  };
  steps.push({
    kind: 'calc',
    highlight_table: 'calc_output',
    narration: `Apply the formula: ${(item.generic_formula ?? '').substring(0, 150)}`,
  });

  // Use same steps for all levels that exist (fallback has no per-level differences)
  const dimensionPaths: Partial<Record<RollupLevelKey, TraversalStep[]>> = {};
  const levels: RollupLevelKey[] = ['facility', 'counterparty', 'desk', 'portfolio', 'lob'];
  for (const level of levels) {
    if (item.level_definitions?.some((d) => d.level === level)) {
      dimensionPaths[level] = steps;
    }
  }

  return { tables, dimension_paths: dimensionPaths };
}
