-- Migration 015: Add governance columns to all L3 tables
-- Adds: model_version (SR 11-7), run_id (calc_run FK), created_by (provenance), updated_ts (audit)
-- Idempotent: safe to re-run

SET search_path TO l1, l2, l3, public;

-- ============================================================
-- model_version VARCHAR(50) — SR 11-7 model governance
-- ============================================================
DO $$ BEGIN ALTER TABLE l3.amendment_detail ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.amendment_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_audit_log ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_run ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_validation_result ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.capital_binding_constraint ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.capital_position_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.cash_flow_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_portfolio_valuation ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_capital_consumption ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_detail_snapshot ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_exposure_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_financial_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_rating_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.credit_event_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.crm_allocation_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_attribute_score ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_snapshot ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_trend ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.deal_pipeline_stage_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.default_loss_recovery_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.desk_capital_consumption ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.ecl_allowance_movement ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.ecl_provision_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.exception_event_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.executive_highlight_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.exposure_metric_cube ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_capital_consumption ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_detail_snapshot ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_financial_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_pricing_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_risk_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_rwa_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_stress_test_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_timeline_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_counterparty_aggregate ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_position_snapshot ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.gl_account_balance_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.kpi_period_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.legal_entity_risk_profile ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_attribution_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_breach_fact ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_counterparty_movement ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_current_state ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_tier_status_matrix ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_utilization_timeseries ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_credit_quality_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_delinquency_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_deterioration_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_exposure_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_pricing_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_profitability_allocation_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_profitability_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_rating_distribution ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_risk_ratio_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_top_contributors ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_result ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_value_fact ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.netting_set_exposure_calc ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_capital_consumption ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.rating_migration_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.regulatory_compliance_state ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_contribution_fact ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_rule_execution ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_value ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_run ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_validation_result ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_appetite_metric_state ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_metric_cube ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.segment_capital_consumption ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_breach_detail ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_result ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_result_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.watchlist_movement_summary ADD COLUMN model_version VARCHAR(50); EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ============================================================
-- run_id VARCHAR(64) — FK to calc_run (technical execution ID)
-- ============================================================
DO $$ BEGIN ALTER TABLE l3.amendment_detail ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.amendment_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.capital_binding_constraint ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.capital_position_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.cash_flow_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_portfolio_valuation ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_capital_consumption ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_detail_snapshot ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_exposure_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_financial_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_rating_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.credit_event_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.crm_allocation_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_attribute_score ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_snapshot ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_trend ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.deal_pipeline_stage_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.default_loss_recovery_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.desk_capital_consumption ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.ecl_allowance_movement ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.ecl_provision_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.exception_event_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.executive_highlight_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.exposure_metric_cube ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_capital_consumption ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_detail_snapshot ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_financial_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_pricing_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_risk_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_rwa_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_stress_test_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_timeline_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_counterparty_aggregate ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_position_snapshot ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.gl_account_balance_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.kpi_period_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.legal_entity_risk_profile ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_attribution_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_breach_fact ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_counterparty_movement ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_current_state ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_tier_status_matrix ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_utilization_timeseries ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_credit_quality_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_delinquency_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_deterioration_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_exposure_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_pricing_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_profitability_allocation_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_profitability_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_rating_distribution ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_risk_ratio_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_top_contributors ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_value_fact ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.netting_set_exposure_calc ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_capital_consumption ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.rating_migration_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.regulatory_compliance_state ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_contribution_fact ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_rule_execution ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_value ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_run ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_validation_result ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_appetite_metric_state ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_metric_cube ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.segment_capital_consumption ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_breach_detail ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_result ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_result_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.watchlist_movement_summary ADD COLUMN run_id VARCHAR(64); EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ============================================================
-- created_by VARCHAR(100) — provenance tracking
-- ============================================================
DO $$ BEGIN ALTER TABLE l3.amendment_detail ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.amendment_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_audit_log ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_run ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_validation_result ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.capital_binding_constraint ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.cash_flow_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_portfolio_valuation ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_capital_consumption ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_detail_snapshot ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_exposure_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_rating_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.credit_event_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.crm_allocation_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_attribute_score ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_snapshot ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_trend ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.deal_pipeline_stage_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.default_loss_recovery_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.desk_capital_consumption ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.executive_highlight_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.exposure_metric_cube ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_capital_consumption ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_detail_snapshot ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_financial_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_pricing_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_risk_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_rwa_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_stress_test_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_timeline_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_counterparty_aggregate ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_position_snapshot ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.gl_account_balance_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.kpi_period_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.legal_entity_risk_profile ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_attribution_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_breach_fact ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_counterparty_movement ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_current_state ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_tier_status_matrix ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_utilization_timeseries ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_credit_quality_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_delinquency_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_deterioration_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_exposure_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_pricing_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_profitability_allocation_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_profitability_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_rating_distribution ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_risk_ratio_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_top_contributors ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_result ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_value_fact ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.netting_set_exposure_calc ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_capital_consumption ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.rating_migration_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.regulatory_compliance_state ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_contribution_fact ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_rule_execution ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_value ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_run ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_validation_result ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_appetite_metric_state ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_metric_cube ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.segment_capital_consumption ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_breach_detail ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_result_summary ADD COLUMN created_by VARCHAR(100); EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ============================================================
-- updated_ts TIMESTAMP — modification audit trail
-- ============================================================
DO $$ BEGIN ALTER TABLE l3.amendment_detail ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.amendment_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_audit_log ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_validation_result ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.cash_flow_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.collateral_portfolio_valuation ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_detail_snapshot ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_exposure_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.counterparty_rating_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.credit_event_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.crm_allocation_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_attribute_score ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_snapshot ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_score_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.data_quality_trend ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.default_loss_recovery_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.executive_highlight_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.exposure_metric_cube ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_detail_snapshot ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_exposure_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_financial_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_pricing_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_risk_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_stress_test_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.facility_timeline_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_counterparty_aggregate ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.fr2590_position_snapshot ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.gl_account_balance_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.kpi_period_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.legal_entity_risk_profile ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_attribution_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_breach_fact ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_counterparty_movement ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_current_state ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_tier_status_matrix ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.limit_utilization_timeseries ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_deterioration_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_exposure_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_rating_distribution ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_risk_ratio_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.lob_top_contributors ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_result ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.metric_value_fact ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.netting_set_exposure_calc ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.portfolio_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.rating_migration_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.regulatory_compliance_state ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_contribution_fact ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_rule_execution ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_cell_value ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_run ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.report_validation_result ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_appetite_metric_state ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.risk_metric_cube ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_breach_detail ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.stress_test_result_summary ADD COLUMN updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ============================================================
-- created_ts for calc infrastructure tables that lacked it
-- ============================================================
DO $$ BEGIN ALTER TABLE l3.calc_audit_log ADD COLUMN created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_run ADD COLUMN created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE l3.calc_validation_result ADD COLUMN created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
