-- ═══════════════════════════════════════════════════════════════
-- Migration 025: Move NOI from facility_financial_snapshot to collateral_snapshot
-- ═══════════════════════════════════════════════════════════════
-- NOI (Net Operating Income) is the revenue/income generated by a specific
-- collateral asset (CRE rental property). It was incorrectly placed on
-- facility_financial_snapshot. This migration:
--   1. Adds noi_current_amt and noi_at_origination_amt to collateral_snapshot
--   2. Backfills from facility_financial_snapshot where possible
--   3. Drops noi_amt from facility_financial_snapshot
--
-- counterparty_financial_snapshot.noi_amt is KEPT — it represents the
-- borrower's enterprise-level financial statement NOI (different concept).
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- Step 1: Add NOI columns to collateral_snapshot
ALTER TABLE l2.collateral_snapshot
  ADD COLUMN IF NOT EXISTS noi_current_amt NUMERIC(18,2),
  ADD COLUMN IF NOT EXISTS noi_at_origination_amt NUMERIC(18,2);

COMMENT ON COLUMN l2.collateral_snapshot.noi_current_amt IS
  'Current-period Net Operating Income for the collateral asset (CRE property income).';
COMMENT ON COLUMN l2.collateral_snapshot.noi_at_origination_amt IS
  'Net Operating Income at loan origination for the collateral asset.';

-- Step 2: Backfill from facility_financial_snapshot where facility_id matches
UPDATE l2.collateral_snapshot cs
SET noi_current_amt = ffs.noi_amt,
    noi_at_origination_amt = ffs.noi_amt
FROM l2.facility_financial_snapshot ffs
WHERE cs.facility_id = ffs.facility_id
  AND cs.as_of_date = ffs.as_of_date
  AND ffs.noi_amt IS NOT NULL;

-- Step 3: Drop noi_amt from facility_financial_snapshot
ALTER TABLE l2.facility_financial_snapshot
  DROP COLUMN IF EXISTS noi_amt;

COMMIT;
