-- Migration 029: Product tables — derivatives + offbs_commitments
-- Generated by scripts/parse-product-tables-excel.ts
-- Date: 2026-03-24

SET search_path TO l1, l2, l3, public;

BEGIN;

-- Derivatives / Accounting & Balances
-- 50 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.derivatives_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accounting_intent       VARCHAR,
    accounting_intent_description VARCHAR,
    aggregate_gross_value   NUMERIC(20,4),
    aggregate_net_value     NUMERIC(20,4),
    allowance_balance       NUMERIC(20,4),
    allowance_for_credit_losses_amount NUMERIC(20,4),
    amount_of_allowance_for_credit_losses NUMERIC(20,4),
    asset_liability_flag    VARCHAR,
    asset_liability_flag_description VARCHAR,
    bs_amount               NUMERIC(20,4),
    bankruptcy_charge_off_amount NUMERIC(18,2),
    carrying_value          NUMERIC(18,6),
    charge_off_amount       NUMERIC(20,4),
    collateral_fair_value   NUMERIC(20,4),
    collateral_fair_value_amount_at_origination NUMERIC(20,4),
    conversion_factor_percentage NUMERIC(10,6),
    counterparty_exposure_value NUMERIC(20,4),
    cumulative_charge_offs  VARCHAR,
    current_credit_exposure_amount NUMERIC(20,4),
    effective_multiplier    NUMERIC(10,6),
    effective_notional_amount NUMERIC(20,4),
    exposure_at_default_ead VARCHAR,
    exposure_type           VARCHAR,
    exposure_amount         NUMERIC(20,4),
    fair_value              NUMERIC(18,2),
    fair_value_far_leg      NUMERIC(20,4),
    fair_value_near_leg     NUMERIC(20,4),
    fair_value_measurement_level VARCHAR,
    gross_contractual_charge_off_amount NUMERIC(18,2),
    gross_fair_value_amount NUMERIC(20,4),
    loss_write_down_amount  NUMERIC(20,4),
    net_gross_ratio         NUMERIC(10,6),
    net_recovery_amount     NUMERIC(20,4),
    notional_amount         NUMERIC(18,2),
    notional_amount_far_leg NUMERIC(20,4),
    notional_amount_near_leg NUMERIC(20,4),
    notional_amount_at_inception NUMERIC(18,2),
    number_of_units         VARCHAR,
    other_charge_off_amount NUMERIC(18,2),
    principal_write_down_amount NUMERIC(18,6),
    principal_write_down    VARCHAR,
    recoveries_amount       NUMERIC(20,4),
    recovery_ltd            NUMERIC(20,4),
    recovery_mtd            NUMERIC(18,6),
    recovery_qtd            NUMERIC(18,6),
    trading_intent          VARCHAR,
    transaction_date        DATE,
    usd_equivalent_amount   NUMERIC(20,4),
    unfunded_allowance_balance NUMERIC(18,6),
    write_down_to_fair_value_amount NUMERIC(18,2),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Derivatives / Classification & Relationships
-- 20 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.derivatives_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    counterparty_type       VARCHAR,
    customer_id             VARCHAR,
    gl_account_number       INTEGER,
    isda_id                 VARCHAR,
    identifier_type         VARCHAR,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    performance_guarantee   BOOLEAN,
    performance_guarantee_amount NUMERIC(18,6),
    primary_monetization_channel VARCHAR,
    qmna                    BOOLEAN,
    qmna_id                 VARCHAR,
    recognized_guarantee    BOOLEAN,
    security_identifier     VARCHAR,
    source_system           VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    usd_conversion_rate     NUMERIC(18,6),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Derivatives / Indicative Record
-- 50 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.derivatives_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    asset_liability_indicator VARCHAR,
    clearing_status         VARCHAR,
    clearing_type_flag      VARCHAR,
    clearing_type_flag_description VARCHAR,
    currency_code           VARCHAR,
    currency_code_far_leg   VARCHAR,
    currency_code_near_leg  VARCHAR,
    derivative_direction    VARCHAR,
    derivative_id           VARCHAR,
    derivative_instrument_type VARCHAR,
    derivative_type         VARCHAR,
    derivative_type_description VARCHAR,
    effective_maturity_date DATE,
    encumbrance_end_date    DATE,
    forward_type            VARCHAR,
    future_type             VARCHAR,
    hedge_id                VARCHAR,
    interest_rate           NUMERIC(18,6),
    interest_rate_type      VARCHAR,
    is_hedge                BOOLEAN,
    maturity_date           DATE,
    maturity_date_optionality DATE,
    maturity_optionality    VARCHAR,
    netting_set_status      VARCHAR,
    otc_trade_flag          BOOLEAN,
    option_type             VARCHAR,
    product_domain          VARCHAR,
    purchased_written_flag  VARCHAR,
    purchased_written_flag_description VARCHAR,
    reference_entity        VARCHAR,
    reporting_currency      VARCHAR,
    reporting_currency_far_leg VARCHAR,
    reporting_currency_near_leg VARCHAR,
    repricing_date_interest_reset_date DATE,
    risk_type               VARCHAR,
    settlement_currency     VARCHAR,
    settlement_currency_near_leg VARCHAR,
    settlement_currency_far_leg VARCHAR,
    snapshot_date           DATE,
    swap_fixed_flag         BOOLEAN,
    swap_type               VARCHAR,
    trade_capacity_code     VARCHAR,
    trade_execution_type    VARCHAR,
    tranche_level           VARCHAR,
    transaction_currency    VARCHAR,
    transaction_currency_far_leg VARCHAR,
    transaction_currency_near_leg VARCHAR,
    trigger_type            VARCHAR,
    underlying_entity       VARCHAR,
    underlying_risk_type    VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Derivatives / Risk & Other
-- 33 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.derivatives_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    charge_off_due_to_bankruptcy_flag VARCHAR,
    collateralization_type  VARCHAR,
    eligible_collateral     NUMERIC(20,4),
    eligible_im_non_cash    NUMERIC(20,4),
    eligible_im_cash        NUMERIC(20,4),
    eligible_vm_cash        NUMERIC(20,4),
    eligible_vm_non_cash    NUMERIC(20,4),
    encumbered_flag         BOOLEAN,
    expected_loss_given_default_elgd NUMERIC(18,6),
    ineligible_vm_cash      NUMERIC(20,4),
    ineligible_vm_non_cash  NUMERIC(20,4),
    ineligible_im_cash      NUMERIC(20,4),
    ineligible_im_non_cash  NUMERIC(20,4),
    latest_record           VARCHAR,
    loss_given_default_lgd  NUMERIC(18,6),
    market_risk_capital_category_indicator VARCHAR,
    market_risk_capital_category_indicator_description VARCHAR,
    market_risk_rule        BOOLEAN,
    maximum_probability_of_default NUMERIC(18,6),
    minimum_probability_of_default NUMERIC(18,6),
    other_charge_off_amount_explanation VARCHAR,
    outstanding_collateral_amount NUMERIC(18,2),
    outstanding_collateral_amount_to_be_posted NUMERIC(20,4),
    outstanding_collateral_amount_to_be_received NUMERIC(20,4),
    pledged_flag            BOOLEAN,
    potential_future_exposure_adjustment NUMERIC(18,6),
    potential_future_exposure_amount NUMERIC(20,4),
    probability_of_default_pd NUMERIC(18,6),
    reference_asset_credit_quality VARCHAR,
    reference_asset_credit_quality_description VARCHAR,
    secured_flag            VARCHAR,
    treasury_control_flag   BOOLEAN,
    two_year_probability_of_default NUMERIC(18,6),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Off-BS Commitments / Accounting & Balances
-- 36 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.offbs_commitments_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    allowance_balance       NUMERIC(20,4),
    allowance_for_credit_losses_amount NUMERIC(20,4),
    amount_of_allowance_for_credit_losses NUMERIC(20,4),
    bankruptcy_charge_off_amount NUMERIC(18,2),
    charge_off_amount       NUMERIC(20,4),
    committed_exposure_global NUMERIC(18,2),
    committed_exposure_global_fair_value VARCHAR,
    committed_exposure_global_par_value VARCHAR,
    counterparty_exposure_value NUMERIC(20,4),
    credit_conversion_factor VARCHAR,
    cumulative_charge_offs  VARCHAR,
    exposure_at_default_ead VARCHAR,
    exposure_type           VARCHAR,
    exposure_amount         NUMERIC(20,4),
    funded_allowance_balance NUMERIC(18,6),
    funded_committed_exposure NUMERIC(20,4),
    gross_contractual_charge_off_amount NUMERIC(18,2),
    loss_write_down_amount  NUMERIC(20,4),
    net_recovery_amount     NUMERIC(20,4),
    notional_amount         NUMERIC(18,2),
    original_commitment_amount NUMERIC(18,2),
    other_charge_off_amount NUMERIC(18,2),
    outstanding_balance     NUMERIC(18,2),
    principal_write_down_amount NUMERIC(18,6),
    principal_write_down    VARCHAR,
    recoveries_amount       NUMERIC(20,4),
    recovery_ltd            NUMERIC(20,4),
    recovery_mtd            NUMERIC(18,6),
    recovery_qtd            NUMERIC(18,6),
    unfunded_allowance_balance NUMERIC(18,6),
    unfunded_amount         NUMERIC(20,4),
    unused_commitment_exposure NUMERIC(20,4),
    utilized_exposure_global NUMERIC(20,4),
    utilized_exposure_global_fair_value VARCHAR,
    utilized_exposure_global_par_value VARCHAR,
    write_down_to_fair_value_amount NUMERIC(18,2),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Off-BS Commitments / Classification & Relationships
-- 11 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.offbs_commitments_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    country_code            VARCHAR,
    customer_id             VARCHAR,
    gl_account_number       INTEGER,
    guarantee_flag          VARCHAR,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    liquidity_facilities    VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Off-BS Commitments / Indicative Record
-- 12 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.offbs_commitments_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    commitment_id           VARCHAR,
    commitment_type         VARCHAR,
    currency_code           VARCHAR,
    effective_date          DATE,
    maturity_bucket         VARCHAR,
    maturity_date           DATE,
    maturity_optionality    VARCHAR,
    off_balancesheet_product_type_exposures VARCHAR,
    reporting_currency      VARCHAR,
    repricing_date_interest_reset_date DATE,
    settlement_currency     VARCHAR,
    transaction_currency    VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Off-BS Commitments / Risk & Other
-- 14 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.offbs_commitments_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    charge_off_due_to_bankruptcy_flag VARCHAR,
    entity_internal_risk_rating VARCHAR,
    expected_loss_given_default_elgd NUMERIC(18,6),
    guarantor_internal_risk_rating VARCHAR,
    internal_risk_rating    VARCHAR,
    internal_risk_rating_description VARCHAR,
    loss_given_default_lgd  NUMERIC(18,6),
    maximum_probability_of_default NUMERIC(18,6),
    minimum_probability_of_default NUMERIC(18,6),
    other_charge_off_amount_explanation VARCHAR,
    probability_of_default_pd NUMERIC(18,6),
    treasury_control_flag   BOOLEAN,
    two_year_probability_of_default NUMERIC(18,6),
    unconditionally_cancellable_flag BOOLEAN,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Foreign key constraints
ALTER TABLE l2.derivatives_accounting_snapshot
  ADD CONSTRAINT fk_deriv_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.derivatives_classification_snapshot
  ADD CONSTRAINT fk_deriv_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.derivatives_indicative_snapshot
  ADD CONSTRAINT fk_deriv_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.derivatives_risk_snapshot
  ADD CONSTRAINT fk_deriv_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.offbs_commitments_accounting_snapshot
  ADD CONSTRAINT fk_offbs_commit_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.offbs_commitments_classification_snapshot
  ADD CONSTRAINT fk_offbs_commit_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.offbs_commitments_indicative_snapshot
  ADD CONSTRAINT fk_offbs_commit_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.offbs_commitments_risk_snapshot
  ADD CONSTRAINT fk_offbs_commit_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

COMMIT;