-- Migration 030: Product tables — sft + securities
-- Generated by scripts/parse-product-tables-excel.ts
-- Date: 2026-03-24

SET search_path TO l1, l2, l3, public;

BEGIN;

-- Secured Financing Transactions / Accounting & Balances
-- 60 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.sft_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accounting_intent       VARCHAR,
    accrued_interest_dividend_amount NUMERIC(18,2),
    accrued_interest_amount NUMERIC(18,2),
    allowance_balance       NUMERIC(20,4),
    allowance_for_credit_losses_amount NUMERIC(20,4),
    amortized_cost          NUMERIC(18,2),
    amount_of_allowance_for_credit_losses NUMERIC(20,4),
    bs_amount               NUMERIC(20,4),
    bankruptcy_charge_off_amount NUMERIC(18,2),
    book_value_amount       NUMERIC(18,6),
    cash_fair_value         NUMERIC(20,4),
    charge_offs_amount      NUMERIC(20,4),
    collateral_fair_value   NUMERIC(20,4),
    collateral_fair_value_amount_at_as_of_date NUMERIC(20,4),
    collateral_fair_value_amount_at_origination NUMERIC(20,4),
    collateral_fair_value_at_reporting_date NUMERIC(20,4),
    collateral_fair_value_at_settlement_date NUMERIC(20,4),
    collateral_value_at_inception_date NUMERIC(20,4),
    collateral_value_at_reporting_date NUMERIC(20,4),
    contract_amount         NUMERIC(18,2),
    contract_amount_at_inception_date NUMERIC(20,4),
    contract_amount_at_maturity_date NUMERIC(20,4),
    contract_amount_at_reporting_date NUMERIC(20,4),
    counterparty_exposure_value NUMERIC(20,4),
    coupon_interest_payment_date DATE,
    cumulative_charge_offs  VARCHAR,
    exposure_at_default_ead VARCHAR,
    exposure_type           VARCHAR,
    exposure_amount         NUMERIC(20,4),
    fair_value_amount       NUMERIC(18,2),
    fair_value_measurement_level VARCHAR,
    gross_contractual_charge_off_amount NUMERIC(18,2),
    indemnification_amount  NUMERIC(18,6),
    indemnification_flag    BOOLEAN,
    lendable_value          NUMERIC(20,4),
    loss_write_down_amount  NUMERIC(20,4),
    maturity_amount         NUMERIC(20,4),
    net_recovery_amount     NUMERIC(20,4),
    original_face_amount    NUMERIC(18,2),
    other_charge_off_amount NUMERIC(18,2),
    paid_amount_at_inception_date NUMERIC(18,6),
    payable_amount_at_maturity_date NUMERIC(18,6),
    payable_amount_at_reporting_date NUMERIC(18,6),
    premium_discount_amount NUMERIC(20,4),
    principal_write_down_amount NUMERIC(18,6),
    principal_write_down    VARCHAR,
    receivable_amount_at_maturity_date NUMERIC(18,6),
    receivable_amount_at_reporting_date NUMERIC(18,6),
    received_amount_at_initiation_date NUMERIC(18,6),
    recoveries_amount       NUMERIC(20,4),
    recovery_ltd            NUMERIC(20,4),
    recovery_mtd            NUMERIC(18,6),
    recovery_qtd            NUMERIC(18,6),
    settlement_date         DATE,
    transaction_date        DATE,
    usd_equivalent_amount   NUMERIC(20,4),
    unfunded_allowance_balance NUMERIC(18,6),
    unfunded_committed_exposure NUMERIC(20,4),
    unrealized_gain_loss    NUMERIC(20,4),
    write_down_to_fair_value_amount NUMERIC(18,2),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Secured Financing Transactions / Classification & Relationships
-- 13 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.sft_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    call_report_code        VARCHAR,
    conduit_transaction_flag BOOLEAN,
    cost_center_id          NUMERIC(20,4),
    counterparty_type       VARCHAR,
    customer_id             VARCHAR,
    gl_account_number       INTEGER,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    primary_monetization_channel VARCHAR,
    qmna_netting_id         VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    transaction_type        VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Secured Financing Transactions / Indicative Record
-- 25 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.sft_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    asset_liability_indicator VARCHAR,
    contract_initiation_date DATE,
    coupon_interest_periodicity VARCHAR,
    currency_code           VARCHAR,
    effective_maturity_date DATE,
    encumbrance_end_date    DATE,
    forward_start_date      DATE,
    interest_rate           NUMERIC(18,6),
    interest_rate_type      VARCHAR,
    maturity_date           DATE,
    maturity_date_optionality DATE,
    maturity_optionality    VARCHAR,
    paid_instrument_type    VARCHAR,
    principal_agent         VARCHAR,
    principal_agent_indicator VARCHAR,
    qmna_flag               BOOLEAN,
    received_instrument_type VARCHAR,
    report_applicability    VARCHAR,
    reporting_currency      VARCHAR,
    repricing_date_interest_reset_date DATE,
    right_to_offset_flag    VARCHAR,
    sft_contract_id         VARCHAR,
    sft_type                VARCHAR,
    settlement_currency     VARCHAR,
    transaction_currency    VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Secured Financing Transactions / Risk & Other
-- 21 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.sft_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    charge_off_due_to_bankruptcy_flag VARCHAR,
    converted               VARCHAR,
    encumbered_flag         BOOLEAN,
    encumbrance_flag        VARCHAR,
    encumbrance_type        VARCHAR,
    expected_loss_given_default_elgd NUMERIC(18,6),
    liquid_assets_collateral_level VARCHAR,
    loss_given_default_lgd  NUMERIC(18,6),
    maximum_probability_of_default NUMERIC(18,6),
    minimum_probability_of_default NUMERIC(18,6),
    non_accrual_status      BOOLEAN,
    other_charge_off_amount_explanation VARCHAR,
    pledged_flag            BOOLEAN,
    probability_of_default_pd NUMERIC(18,6),
    rehypothecated          VARCHAR,
    rehypothecated_flag     VARCHAR,
    secured_flag            VARCHAR,
    security_ownership_type VARCHAR,
    treasury_control        VARCHAR,
    treasury_control_flag   BOOLEAN,
    two_year_probability_of_default NUMERIC(18,6),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Securities / Accounting & Balances
-- 60 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.securities_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    asu_2017_12_hedge_designations VARCHAR,
    accounting_intent       VARCHAR,
    accounting_intent_description VARCHAR,
    accrued_interest_dividend_amount NUMERIC(18,2),
    accrued_interest_amount NUMERIC(18,2),
    acquisition_cost_usd_converted NUMERIC(20,4),
    allowance_for_credit_losses_amount NUMERIC(20,4),
    amortized_cost          NUMERIC(18,2),
    amount_of_allowance_for_credit_losses NUMERIC(20,4),
    balance_sheet_amount    NUMERIC(20,4),
    book_yield              NUMERIC(10,6),
    carrying_value          NUMERIC(18,6),
    charge_off_amount       NUMERIC(20,4),
    collateral_fair_value_amount_at_origination NUMERIC(20,4),
    collateral_market_value NUMERIC(20,4),
    counterparty_exposure_value NUMERIC(20,4),
    coupon_int_pmt_date     DATE,
    current_face_value      NUMERIC(18,6),
    effective_portion_of_cumulative_gains_and_losses NUMERIC(20,4),
    exposure_type           VARCHAR,
    exposure_amount         NUMERIC(20,4),
    fair_value_amount       NUMERIC(18,2),
    fair_value_measurement_level VARCHAR,
    forward_start_amount    NUMERIC(18,6),
    fund_asset_class        VARCHAR,
    fwd_start_amount        NUMERIC(18,6),
    fwd_start_mat_bucket    VARCHAR,
    hedge_horizon           VARCHAR,
    hedge_percentage        NUMERIC(10,6),
    hedge_position_description VARCHAR,
    hedge_position          VARCHAR,
    hedged_cash_flow        VARCHAR,
    hedged_risk             VARCHAR,
    hedging_instrument_at_fair_value NUMERIC(20,4),
    identifier_value        VARCHAR,
    indemnification_asset_amount NUMERIC(18,6),
    lendable_value          NUMERIC(20,4),
    market_value            NUMERIC(18,2),
    option_exercised        VARCHAR,
    option_exercised_status VARCHAR,
    original_balance        NUMERIC(18,2),
    original_book_yield     NUMERIC(20,4),
    original_face_value     NUMERIC(18,2),
    price                   NUMERIC(20,4),
    principal_pmt_date      DATE,
    purchase_date           DATE,
    purchase_price          NUMERIC(20,4),
    retained_earnings       NUMERIC(18,2),
    securities_measurement_level VARCHAR,
    settlement_amount       NUMERIC(20,4),
    settlement_date         DATE,
    trade_date              DATE,
    trade_price             NUMERIC(20,4),
    trade_quantity          NUMERIC(20,4),
    transaction_date        DATE,
    transaction_price       NUMERIC(20,4),
    transaction_price_usd_converted NUMERIC(20,4),
    transaction_quantity    NUMERIC(20,4),
    usd_equivalent_amounts  NUMERIC(20,4),
    unrealized_gain_loss    NUMERIC(20,4),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Securities / Classification & Relationships
-- 61 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.securities_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    cusip                   VARCHAR,
    call_report_code        VARCHAR,
    census_tract            VARCHAR,
    cost_center_id          NUMERIC(20,4),
    counterparty_type       VARCHAR,
    country_code            VARCHAR,
    customer_id             VARCHAR,
    domicile                VARCHAR,
    domicile_issuer         VARCHAR,
    domicile_ultimate_parent VARCHAR,
    gl_account_number       INTEGER,
    geographic_code         VARCHAR,
    guarantee_flag          VARCHAR,
    guarantor_id            VARCHAR,
    guarantor_name          VARCHAR,
    guarantor_type          VARCHAR,
    isin                    VARCHAR,
    iso_country_code_issuer VARCHAR,
    iso_country_code_issuer_parent VARCHAR,
    iso_country_code_parent VARCHAR,
    identifier_type         VARCHAR,
    interest_eligible       BOOLEAN,
    internal_identifier     VARCHAR,
    internal_transaction_flag VARCHAR,
    issuer_domicile         VARCHAR,
    issuer_id               VARCHAR,
    issuer_name             VARCHAR,
    issuer_parent_name      VARCHAR,
    issuer_type             VARCHAR,
    legal_entity_domicile   VARCHAR,
    legal_entity_id         VARCHAR,
    municipal_bond_sector   VARCHAR,
    percent_direct_encumbered NUMERIC(10,6),
    pledged_capacity_counterparty VARCHAR,
    primary_monetization_channel VARCHAR,
    property_city           VARCHAR,
    property_state          VARCHAR,
    property_street_address VARCHAR,
    property_zip_code       VARCHAR,
    qmna_id                 VARCHAR,
    risk_weight_issuer_domicile VARCHAR,
    sedol                   VARCHAR,
    sector                  VARCHAR,
    security_description    VARCHAR,
    security_identifier     VARCHAR,
    security_identifier_type VARCHAR,
    security_name           VARCHAR,
    security_status         VARCHAR,
    settlement_convention   VARCHAR,
    settlement_standard     BOOLEAN,
    settlement_status       VARCHAR,
    source_system           VARCHAR,
    source_system_description VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    stock_exchange_code     VARCHAR,
    ticker_symbol           VARCHAR,
    trade_type_b_s          VARCHAR,
    transaction_type        VARCHAR,
    type_of_hedges          VARCHAR,
    write_offs              NUMERIC(20,4),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Securities / Indicative Record
-- 48 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.securities_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    activity_type           VARCHAR,
    amortization_type       VARCHAR,
    asset_liability_indicator VARCHAR,
    asset_liability_indicator_description VARCHAR,
    call_date               DATE,
    ceiling_rate            NUMERIC(10,6),
    coupon_dividend_rate    NUMERIC(20,4),
    coupon_int_pmt_periodicity VARCHAR,
    currency_code           VARCHAR,
    currency_of_issuance    VARCHAR,
    currency_of_settlement  VARCHAR,
    current_rate            NUMERIC(10,6),
    effective_maturity_date DATE,
    encumbrance_end_date    DATE,
    floor_rate              NUMERIC(10,6),
    forward_start_date      DATE,
    fund_name               VARCHAR,
    fund_type               VARCHAR,
    fund_type_description   VARCHAR,
    fwd_start_mat_date      DATE,
    hedged_interest_rate    VARCHAR,
    hedging_id              VARCHAR,
    interest_rate           NUMERIC(18,6),
    interest_rate_type      VARCHAR,
    issue_date              DATE,
    last_reprice            NUMERIC(20,4),
    last_reprice_date       DATE,
    maturity_date           DATE,
    maturity_date_optionality DATE,
    maturity_optionality    VARCHAR,
    mutual_fund_type        VARCHAR,
    pricing_date            DATE,
    principal_periodicity   VARCHAR,
    product_code            VARCHAR,
    put_date                DATE,
    reporting_currency      VARCHAR,
    repricing_date          DATE,
    repricing_date_interest_reset_date DATE,
    security_sub_type       VARCHAR,
    security_type           VARCHAR,
    security_type_description VARCHAR,
    settlement_currency     VARCHAR,
    settlement_type         VARCHAR,
    sidedness               VARCHAR,
    snapshot_date           DATE,
    transaction_currency    VARCHAR,
    unique_id               VARCHAR,
    weighted_average_life   NUMERIC(18,6),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Securities / Risk & Other
-- 19 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.securities_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    "144a_flag"             BOOLEAN,
    direct_encumbrance_type VARCHAR,
    encumbered_flag         BOOLEAN,
    latest_record           VARCHAR,
    liquid_assets_collateral_level VARCHAR,
    non_accrual_status      BOOLEAN,
    non_accrual_date        DATE,
    performing_flag         BOOLEAN,
    pledged_eligibility     BOOLEAN,
    pledged_flag            BOOLEAN,
    pledged_to              VARCHAR,
    private_placement_flag  BOOLEAN,
    rehypothecated          VARCHAR,
    secured_flag            VARCHAR,
    trade_failed_flag       BOOLEAN,
    trade_long_short_flag   VARCHAR,
    treasury_control        VARCHAR,
    treasury_control_flag   BOOLEAN,
    unencumbered            VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Foreign key constraints
ALTER TABLE l2.sft_accounting_snapshot
  ADD CONSTRAINT fk_sft_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.sft_classification_snapshot
  ADD CONSTRAINT fk_sft_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.sft_indicative_snapshot
  ADD CONSTRAINT fk_sft_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.sft_risk_snapshot
  ADD CONSTRAINT fk_sft_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.securities_accounting_snapshot
  ADD CONSTRAINT fk_sec_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.securities_classification_snapshot
  ADD CONSTRAINT fk_sec_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.securities_indicative_snapshot
  ADD CONSTRAINT fk_sec_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.securities_risk_snapshot
  ADD CONSTRAINT fk_sec_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

COMMIT;