-- Migration 031: Product tables — borrowings + debt + deposits
-- Generated by scripts/parse-product-tables-excel.ts
-- Date: 2026-03-24

SET search_path TO l1, l2, l3, public;

BEGIN;

-- Borrowings / Accounting & Balances
-- 55 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.borrowings_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accounting_intent       VARCHAR,
    accrued_interest_dividend_amount NUMERIC(18,2),
    accrued_interest_amount NUMERIC(18,2),
    allowance_balance       NUMERIC(20,4),
    allowance_for_credit_losses_amount NUMERIC(20,4),
    amortized_cost          NUMERIC(18,2),
    amount_of_allowance_for_credit_losses NUMERIC(20,4),
    bs_amount               NUMERIC(20,4),
    bankruptcy_charge_off_amount NUMERIC(18,2),
    borrowing_date          DATE,
    borrowing_term          VARCHAR,
    carrying_value          NUMERIC(18,6),
    charge_off_amount       NUMERIC(20,4),
    collateral_value        NUMERIC(20,4),
    committed_exposure_global NUMERIC(18,2),
    committed_exposure_global_fair_value VARCHAR,
    committed_exposure_global_par_value VARCHAR,
    counterparty_exposure_value NUMERIC(20,4),
    coupon_interest_payment_date DATE,
    cumulative_charge_offs  VARCHAR,
    current_outstanding_balance NUMERIC(18,2),
    exposure_at_default_ead VARCHAR,
    exposure_type           VARCHAR,
    exposure_amount         NUMERIC(20,4),
    fair_value_amount       NUMERIC(18,2),
    fair_value_measurements_level VARCHAR,
    fair_value_option_flag  VARCHAR,
    forward_start_amount    NUMERIC(18,6),
    funded_allowance_balance NUMERIC(18,6),
    funded_committed_exposure NUMERIC(20,4),
    gross_contractual_charge_off_amount NUMERIC(18,2),
    indemnification_asset_amount NUMERIC(18,6),
    lendable_value          NUMERIC(20,4),
    loss_write_down_amount  NUMERIC(20,4),
    net_recovery_amount     NUMERIC(20,4),
    original_amount         NUMERIC(18,2),
    other_charge_off_amount NUMERIC(18,2),
    premium_discount_amount NUMERIC(20,4),
    principal_write_down_amount NUMERIC(18,6),
    principal_write_down    VARCHAR,
    recoveries_amount       NUMERIC(20,4),
    recovery_ltd            NUMERIC(20,4),
    recovery_mtd            NUMERIC(18,6),
    recovery_qtd            NUMERIC(18,6),
    retained_earnings       NUMERIC(18,2),
    settlement_date         DATE,
    usd_equivalent_amount   NUMERIC(20,4),
    unfunded_allowance_balance NUMERIC(18,6),
    unfunded_committed_exposure NUMERIC(20,4),
    unrealized_gain_loss    NUMERIC(20,4),
    unused_commitment_exposure NUMERIC(20,4),
    utilized_exposure_global NUMERIC(20,4),
    utilized_exposure_global_fair_value VARCHAR,
    utilized_exposure_global_par_value VARCHAR,
    write_down_to_fair_value_amount NUMERIC(18,2),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Borrowings / Classification & Relationships
-- 22 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.borrowings_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    counterparty_type       VARCHAR,
    customer_id             VARCHAR,
    gl_account_number       INTEGER,
    guarantor               VARCHAR,
    guarantor_flag          VARCHAR,
    guarantor_name          VARCHAR,
    guarantor_type          VARCHAR,
    isin                    VARCHAR,
    identifier_type         VARCHAR,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    primary_monetization_channel VARCHAR,
    qmna_id                 VARCHAR,
    sedol                   VARCHAR,
    security_identifier     VARCHAR,
    security_identifier_type VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    stock_exchange_code     VARCHAR,
    ticker_symbol           VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Borrowings / Indicative Record
-- 21 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.borrowings_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    borrowing_id            VARCHAR,
    borrowing_type          VARCHAR,
    call_date               DATE,
    commitment_type         VARCHAR,
    convertible_flag        BOOLEAN,
    currency_code           VARCHAR,
    forward_start_date      DATE,
    hedge_id                VARCHAR,
    interest_rate           NUMERIC(18,6),
    interest_rate_type      VARCHAR,
    interest_rate_variability VARCHAR,
    interest_reset_frequency VARCHAR,
    issue_date              DATE,
    maturity_date           DATE,
    maturity_optionality    VARCHAR,
    put_date                DATE,
    repayment_type          VARCHAR,
    reporting_currency      VARCHAR,
    repricing_date          DATE,
    settlement_currency     VARCHAR,
    transaction_currency    VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Borrowings / Risk & Other
-- 18 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.borrowings_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    charge_off_due_to_bankruptcy_flag VARCHAR,
    entity_internal_risk_rating VARCHAR,
    expected_loss_given_default_elgd NUMERIC(18,6),
    guarantor_internal_risk_rating VARCHAR,
    internal_risk_rating    VARCHAR,
    internal_risk_rating_description VARCHAR,
    loss_given_default_lgd  NUMERIC(18,6),
    maximum_probability_of_default NUMERIC(18,6),
    minimum_probability_of_default NUMERIC(18,6),
    non_accrual_status      BOOLEAN,
    non_accrual_date        DATE,
    other_charge_off_amount_explanation VARCHAR,
    pledged_collateral_value NUMERIC(20,4),
    pledged_flag            BOOLEAN,
    probability_of_default_pd NUMERIC(18,6),
    secured_flag            VARCHAR,
    treasury_control_flag   BOOLEAN,
    two_year_probability_of_default NUMERIC(18,6),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Debt / Accounting & Balances
-- 55 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.debt_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accounting_intent       VARCHAR,
    accrued_interest_dividend_amount NUMERIC(18,2),
    accrued_interest_amount NUMERIC(18,2),
    allowance_balance       NUMERIC(20,4),
    allowance_for_credit_losses_amount NUMERIC(20,4),
    amortized_cost          NUMERIC(18,2),
    amount_of_allowance_for_credit_losses NUMERIC(20,4),
    bs_amount               NUMERIC(20,4),
    bankruptcy_charge_off_amount NUMERIC(18,2),
    carrying_value          NUMERIC(18,6),
    charge_off_amount       NUMERIC(20,4),
    committed_exposure_global NUMERIC(18,2),
    committed_exposure_global_fair_value VARCHAR,
    committed_exposure_global_par_value VARCHAR,
    counterparty_exposure_value NUMERIC(20,4),
    coupon_interest_payment_date DATE,
    cumulative_charge_offs  VARCHAR,
    debt_redeemable_flag    BOOLEAN,
    exposure_at_default_ead VARCHAR,
    exposure_type           VARCHAR,
    exposure_amount         NUMERIC(20,4),
    fair_value_amount       NUMERIC(18,2),
    fair_value_measurement_level VARCHAR,
    fair_value_option_flag  VARCHAR,
    forward_start_amount    NUMERIC(18,6),
    funded_allowance_balance NUMERIC(18,6),
    funded_committed_exposure NUMERIC(20,4),
    gross_contractual_charge_off_amount NUMERIC(18,2),
    indemnification_asset_amount NUMERIC(18,6),
    lendable_value          NUMERIC(20,4),
    loss_write_down_amount  NUMERIC(20,4),
    net_recovery_amount     NUMERIC(20,4),
    number_of_originators   VARCHAR,
    original_face_amount    NUMERIC(18,2),
    other_charge_off_amount NUMERIC(18,2),
    outstanding_balance     NUMERIC(18,2),
    premium_discount_amount NUMERIC(20,4),
    principal_write_down_amount NUMERIC(18,6),
    principal_write_down    VARCHAR,
    recoveries_amount       NUMERIC(20,4),
    recovery_ltd            NUMERIC(20,4),
    recovery_mtd            NUMERIC(18,6),
    recovery_qtd            NUMERIC(18,6),
    retained_earnings       NUMERIC(18,2),
    settlement_date         DATE,
    transaction_date        DATE,
    usd_equivalent_amount   NUMERIC(20,4),
    unfunded_allowance_balance NUMERIC(18,6),
    unfunded_committed_exposure NUMERIC(20,4),
    unrealized_gain_loss    NUMERIC(20,4),
    unused_commitment_exposure NUMERIC(20,4),
    utilized_exposure_global NUMERIC(20,4),
    utilized_exposure_global_fair_value VARCHAR,
    utilized_exposure_global_par_value VARCHAR,
    write_down_to_fair_value_amount NUMERIC(18,2),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Debt / Classification & Relationships
-- 19 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.debt_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    cusip                   VARCHAR,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    counterparty_type       VARCHAR,
    customer_id             VARCHAR,
    gl_account_number       INTEGER,
    isin                    VARCHAR,
    identifier_type         VARCHAR,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    primary_monetization_channel VARCHAR,
    qmna_id                 VARCHAR,
    sedol                   VARCHAR,
    security_identifier     VARCHAR,
    security_identifier_type VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    stock_exchange_code     VARCHAR,
    ticker_symbol           VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Debt / Indicative Record
-- 22 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.debt_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    borrowing_type          VARCHAR,
    call_date               DATE,
    currency_code           VARCHAR,
    debt_type               VARCHAR,
    forward_start_date      DATE,
    hedge_id                VARCHAR,
    interest_rate           NUMERIC(18,6),
    interest_rate_type      VARCHAR,
    issue_date              DATE,
    maturity_date           DATE,
    maturity_optionality    VARCHAR,
    put_date                DATE,
    remaining_maturity_days INTEGER,
    remaining_time_to_repricing INTEGER,
    reporting_currency      VARCHAR,
    repricing_date          DATE,
    repricing_date_interest_reset_date DATE,
    security_sub_type       VARCHAR,
    security_type           VARCHAR,
    settlement_currency     VARCHAR,
    transaction_currency    VARCHAR,
    transaction_id          VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Debt / Risk & Other
-- 16 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.debt_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    charge_off_due_to_bankruptcy_flag VARCHAR,
    entity_internal_risk_rating VARCHAR,
    expected_loss_given_default_elgd NUMERIC(18,6),
    guarantor_internal_risk_rating VARCHAR,
    internal_risk_rating    VARCHAR,
    internal_risk_rating_description VARCHAR,
    loss_given_default_lgd  NUMERIC(18,6),
    maximum_probability_of_default NUMERIC(18,6),
    minimum_probability_of_default NUMERIC(18,6),
    non_accrual_status      BOOLEAN,
    non_accrual_date        DATE,
    other_charge_off_amount_explanation VARCHAR,
    pledged_flag            BOOLEAN,
    probability_of_default_pd NUMERIC(18,6),
    treasury_control_flag   BOOLEAN,
    two_year_probability_of_default NUMERIC(18,6),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Deposits / Accounting & Balances
-- 27 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.deposits_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accounting_intent       VARCHAR,
    accrued_dividend_amount NUMERIC(18,2),
    accrued_interest_dividend_amount NUMERIC(18,2),
    accrued_interest_amount NUMERIC(18,2),
    amortized_cost          NUMERIC(18,2),
    amount_balance          NUMERIC(18,6),
    bs_amount               NUMERIC(20,4),
    book_value_amount       NUMERIC(18,6),
    broker_intent           VARCHAR,
    counterparty_exposure_value NUMERIC(20,4),
    current_balance         NUMERIC(18,2),
    deposit_balance         NUMERIC(18,6),
    early_withdrawn_amount  NUMERIC(18,2),
    excess_operational_balance NUMERIC(18,2),
    fdic_insured_balance    NUMERIC(18,2),
    fdic_insured_depository_institution_flag BOOLEAN,
    fair_value_amount       NUMERIC(18,2),
    interest_balance        NUMERIC(18,2),
    next_interest_payment_date DATE,
    original_balance        NUMERIC(18,2),
    premium_discount_amount NUMERIC(20,4),
    tranche_amount          NUMERIC(18,6),
    transaction_date        DATE,
    usd_equivalent_amount   NUMERIC(20,4),
    unamortized_discount_amount NUMERIC(18,2),
    unamortized_premium_amount NUMERIC(18,2),
    unrealized_gain_loss    NUMERIC(20,4),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Deposits / Classification & Relationships
-- 29 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.deposits_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    account_status          VARCHAR,
    account_status_description VARCHAR,
    acquisition_channel     VARCHAR,
    acquisition_channel_description VARCHAR,
    affiliate_flag          BOOLEAN,
    affiliate_transaction_flag VARCHAR,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    counterparty_type       VARCHAR,
    customer_id             VARCHAR,
    fdic_ownership_code     VARCHAR,
    fdic_ownership_code_description VARCHAR,
    gl_account_number       INTEGER,
    geographic_code         VARCHAR,
    insurance_provider      VARCHAR,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    notice_period           INTEGER,
    preauthorized_transfer_accounts BOOLEAN,
    preferred_deposits      BOOLEAN,
    primary_monetization_channel VARCHAR,
    source_system           VARCHAR,
    source_system_description VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    stability               VARCHAR,
    subsidiary_type         VARCHAR,
    trigger                 BOOLEAN,
    withdrawal_method       BOOLEAN,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Deposits / Indicative Record
-- 24 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.deposits_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    currency_code           VARCHAR,
    currency_type           VARCHAR,
    days_remaining_to_maturity INTEGER,
    deposit_account_type    VARCHAR,
    deposit_id              VARCHAR,
    ecr_implied_interest_rate VARCHAR,
    interest_bearing_flag   BOOLEAN,
    interest_rate           NUMERIC(18,6),
    interest_rate_cap       VARCHAR,
    interest_rate_floor     VARCHAR,
    interest_rate_type      VARCHAR,
    maturity_date           DATE,
    maturity_optionality    VARCHAR,
    optionality_type        VARCHAR,
    optionality_type_description VARCHAR,
    original_maturity_date  DATE,
    product_code            VARCHAR,
    reporting_currency      VARCHAR,
    reporting_date          DATE,
    repricing_date          DATE,
    repricing_date_interest_reset_date DATE,
    settlement_currency     VARCHAR,
    snapshot_date           DATE,
    transaction_currency    VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Deposits / Risk & Other
-- 24 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.deposits_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    "2052a_insured"         VARCHAR,
    automated_renewal_flag  BOOLEAN,
    brokered_flag           BOOLEAN,
    deposit_listing_service_flag BOOLEAN,
    ecr_flag                VARCHAR,
    escrow_service_flag     VARCHAR,
    latest_record           VARCHAR,
    negotiable_flag         BOOLEAN,
    operational_account_flag VARCHAR,
    operational_flag        BOOLEAN,
    overdraft_flag          BOOLEAN,
    rc_e_depositor_type     VARCHAR,
    rc_e_depositor_type_description VARCHAR,
    reciprocal_flag         BOOLEAN,
    relationship_flag       BOOLEAN,
    stable_vs_less_stable_flag VARCHAR,
    sweep_flag              BOOLEAN,
    tradable_flag           BOOLEAN,
    trade_flag              VARCHAR,
    transactional_account_flag VARCHAR,
    transactional_flag      BOOLEAN,
    treasury_control_flag   BOOLEAN,
    trigger_flag            VARCHAR,
    unsettled_flag          BOOLEAN,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Foreign key constraints
ALTER TABLE l2.borrowings_accounting_snapshot
  ADD CONSTRAINT fk_borr_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.borrowings_classification_snapshot
  ADD CONSTRAINT fk_borr_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.borrowings_indicative_snapshot
  ADD CONSTRAINT fk_borr_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.borrowings_risk_snapshot
  ADD CONSTRAINT fk_borr_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.debt_accounting_snapshot
  ADD CONSTRAINT fk_debt_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.debt_classification_snapshot
  ADD CONSTRAINT fk_debt_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.debt_indicative_snapshot
  ADD CONSTRAINT fk_debt_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.debt_risk_snapshot
  ADD CONSTRAINT fk_debt_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.deposits_accounting_snapshot
  ADD CONSTRAINT fk_dep_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.deposits_classification_snapshot
  ADD CONSTRAINT fk_dep_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.deposits_indicative_snapshot
  ADD CONSTRAINT fk_dep_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.deposits_risk_snapshot
  ADD CONSTRAINT fk_dep_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

COMMIT;