-- Migration 032: Product tables — equities + stock
-- Generated by scripts/parse-product-tables-excel.ts
-- Date: 2026-03-24

SET search_path TO l1, l2, l3, public;

BEGIN;

-- Equities / Accounting & Balances
-- 22 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.equities_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accrued_interest_dividend_amount NUMERIC(18,2),
    bs_amount               NUMERIC(20,4),
    carrying_value          NUMERIC(18,6),
    cash_dividends          NUMERIC(18,2),
    cash_dividends_declared_current_period NUMERIC(18,6),
    cash_dividends_paid_current_period NUMERIC(18,6),
    cash_dividends_paid_fiscal_ytd NUMERIC(18,6),
    counterparty_exposure_value NUMERIC(20,4),
    face_value              NUMERIC(18,2),
    fair_value_amount       NUMERIC(18,2),
    lendable_value          NUMERIC(20,4),
    market_value            NUMERIC(18,2),
    minority_interest_amount NUMERIC(18,2),
    number_of_units         VARCHAR,
    number_of_shares        NUMERIC(18,2),
    ownership_percentage    NUMERIC(18,6),
    premium_value           NUMERIC(18,2),
    retained_earnings       NUMERIC(18,2),
    retained_earnings_brought_forward_start_of_fiscal_year NUMERIC(18,6),
    retained_earnings_cumulative_current_fiscal_year NUMERIC(18,6),
    transaction_date        DATE,
    usd_equivalent_amount   NUMERIC(20,4),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Equities / Classification & Relationships
-- 12 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.equities_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    cusip                   VARCHAR,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    customer_id             VARCHAR,
    gl_account_number       INTEGER,
    internal_transaction_flag VARCHAR,
    legal_entity_id         VARCHAR,
    source_system_id        VARCHAR,
    source_system_name      VARCHAR,
    stock_exchange_code     VARCHAR,
    ticker_symbol           VARCHAR,
    unpaid_share_capital    NUMERIC(18,2),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Equities / Indicative Record
-- 7 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.equities_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    currency_code           VARCHAR,
    equity_type             VARCHAR,
    maturity_date           DATE,
    reporting_currency      VARCHAR,
    settlement_currency     VARCHAR,
    transaction_currency    VARCHAR,
    transaction_id          VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Equities / Risk & Other
-- 1 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.equities_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    treasury_control_flag   BOOLEAN,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Stock / Accounting & Balances
-- 9 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.stock_accounting_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    accounting_method       VARCHAR,
    bs_amount               NUMERIC(20,4),
    carrying_value          NUMERIC(18,6),
    fair_value_amount       NUMERIC(18,2),
    investment_type         VARCHAR,
    market_value            NUMERIC(18,2),
    number_of_units         VARCHAR,
    number_of_shares        NUMERIC(18,2),
    unrealized_gain_loss    NUMERIC(20,4),
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Stock / Classification & Relationships
-- 7 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.stock_classification_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    call_report_code        VARCHAR,
    cost_center_id          NUMERIC(20,4),
    customer_id             VARCHAR,
    internal_transaction_flag VARCHAR,
    investee_industry_type  VARCHAR,
    legal_entity_id         VARCHAR,
    percentage_ownership_of_voting_stock VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Stock / Indicative Record
-- 4 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.stock_indicative_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    currency_code           VARCHAR,
    maturity_date           DATE,
    stock_position_id       VARCHAR,
    stock_type              VARCHAR,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Stock / Risk & Other
-- 1 product-specific fields + 2 PK fields
CREATE TABLE IF NOT EXISTS l2.stock_risk_snapshot (
    position_id          BIGINT       NOT NULL,
    as_of_date           DATE         NOT NULL,
    treasury_control_flag   BOOLEAN,
    created_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_ts            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (position_id, as_of_date)
);

-- Foreign key constraints
ALTER TABLE l2.equities_accounting_snapshot
  ADD CONSTRAINT fk_eq_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.equities_classification_snapshot
  ADD CONSTRAINT fk_eq_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.equities_indicative_snapshot
  ADD CONSTRAINT fk_eq_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.equities_risk_snapshot
  ADD CONSTRAINT fk_eq_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.stock_accounting_snapshot
  ADD CONSTRAINT fk_stock_acctg_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.stock_classification_snapshot
  ADD CONSTRAINT fk_stock_class_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.stock_indicative_snapshot
  ADD CONSTRAINT fk_stock_indic_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

ALTER TABLE l2.stock_risk_snapshot
  ADD CONSTRAINT fk_stock_risk_snap_pos
  FOREIGN KEY (position_id) REFERENCES l2.position(position_id);

COMMIT;