/**
 * L1 table definitions in creation (dependency) order.
 * Matches REQUIREMENTS.md L1 specs. PK/FK ensure referential integrity for seed data.
 */
import type { TableDef } from './types';

export const L1_TABLES: TableDef[] = [
  // ========== Phase 1: Reference dims (no FK) ==========
  {
    tableName: 'currency_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'currency_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'currency_symbol', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_active', type: 'VARCHAR(100)', nullable: true },
      { name: 'iso_numeric', type: 'VARCHAR(100)', nullable: true },
      { name: 'minor_unit_decimals', type: 'INTEGER', nullable: true },
      { name: 'is_g10_currency', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'country_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'country_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'is_active', type: 'VARCHAR(100)', nullable: true },
      { name: 'region_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'basel_country_risk_weight', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_developed_market', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_fatf_high_risk', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_ofac_sanctioned', type: 'VARCHAR(100)', nullable: true },
      { name: 'iso_alpha_3', type: 'VARCHAR(100)', nullable: true },
      { name: 'iso_numeric', type: 'VARCHAR(100)', nullable: true },
      { name: 'jurisdiction_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'region_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'region_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'region_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'display_order', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'region_group_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'regulatory_jurisdiction',
    scd: 'SCD-0',
    columns: [
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'jurisdiction_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'is_active', type: 'VARCHAR(100)', nullable: true },
      { name: 'jurisdiction_id', type: 'BIGINT', nullable: true },
      { name: 'primary_regulator', type: 'VARCHAR(100)', nullable: true },
      { name: 'regulatory_framework', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'entity_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'entity_type_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'entity_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'is_financial_institution', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_sovereign', type: 'VARCHAR(100)', nullable: true },
      { name: 'regulatory_counterparty_class', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'credit_event_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'credit_event_type_code', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_event_type_id', type: 'BIGINT', nullable: false },
      { name: 'credit_event_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'default_trigger_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'credit_status_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'credit_status_code', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_status_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'default_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'delinquency_bucket', type: 'VARCHAR(100)', nullable: true },
      { name: 'status_category', type: 'VARCHAR(50)', nullable: false },
    ],
  },
  {
    tableName: 'exposure_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'exposure_type_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'exposure_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'exposure_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'basel_exposure_class', type: 'VARCHAR(100)', nullable: true },
      { name: 'ccf_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'off_balance_sheet_flag', type: 'CHAR(1)', nullable: true },
      { name: 'product_id', type: 'BIGINT', nullable: true },
      { name: 'sa_ccr_asset_class', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'amendment_status_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'amendment_status_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'amendment_status_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'status_group', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_terminal_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'amendment_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'amendment_type_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'amendment_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'default_definition_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'default_definition_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'default_definition_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'days_past_due_threshold', type: 'VARCHAR(255)', nullable: true },
      { name: 'credit_event_trigger_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'materiality_threshold_amt', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'maturity_bucket_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'maturity_bucket_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'bucket_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'bucket_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'bucket_end_days', type: 'VARCHAR(100)', nullable: true },
      { name: 'bucket_start_days', type: 'VARCHAR(100)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'regulatory_framework', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'fr2590_category_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'fr2590_category_code', type: 'BIGINT', nullable: false, pk: true },
      { name: 'category_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'definition', type: 'VARCHAR(100)', nullable: true },
      { name: 'display_order', type: 'VARCHAR(100)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'counterparty_role_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'role_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'role_category', type: 'VARCHAR(50)', nullable: false },
      { name: 'is_risk_bearing_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'rating_scale_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'rating_scale_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'scale_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'default_flag', type: 'CHAR(1)', nullable: true },
      { name: 'display_color_hex', type: 'VARCHAR(100)', nullable: true },
      { name: 'investment_grade_flag', type: 'CHAR(1)', nullable: true },
      { name: 'pd_implied', type: 'VARCHAR(100)', nullable: true },
      { name: 'rating_grade_id', type: 'BIGINT', nullable: true },
      { name: 'rating_notch', type: 'VARCHAR(100)', nullable: true },
      { name: 'rating_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'scale_type', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'crm_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'crm_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'basel_recognition_method', type: 'VARCHAR(255)', nullable: true },
      { name: 'crm_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'eligible_flag', type: 'CHAR(1)', nullable: true },
      { name: 'risk_mitigant_subtype_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  // ========== Phase 2 ==========
  {
    tableName: 'source_system_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'source_system_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'source_system_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'data_domain', type: 'VARCHAR(100)', nullable: true },
      { name: 'ingestion_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'system_owner', type: 'VARCHAR(100)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'date_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'date_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'calendar_date', type: 'DATE', nullable: true },
      { name: 'calendar_year', type: 'VARCHAR(100)', nullable: true },
      { name: 'calendar_quarter', type: 'VARCHAR(100)', nullable: true },
      { name: 'calendar_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_of_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_of_week', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'fiscal_year', type: 'VARCHAR(100)', nullable: true },
      { name: 'fiscal_quarter', type: 'VARCHAR(100)', nullable: true },
      { name: 'fiscal_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_weekend', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_month_end', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_quarter_end', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_year_end', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_us_business_day', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_us_bank_holiday', type: 'VARCHAR(100)', nullable: true },
      { name: 'date_day', type: 'VARCHAR(100)', nullable: true },
      { name: 'date_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'date_quarter', type: 'VARCHAR(100)', nullable: true },
      { name: 'date_year', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'date_time_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'date_time_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'date_id', type: 'BIGINT', nullable: false, fk: 'l1.date_dim(date_id)' },
      { name: 'timestamp_utc', type: 'TIMESTAMP', nullable: true },
      { name: 'hour_of_day', type: 'VARCHAR(100)', nullable: true },
      { name: 'minute_of_hour', type: 'VARCHAR(100)', nullable: true },
      { name: 'second_of_minute', type: 'VARCHAR(100)', nullable: true },
      { name: 'timezone_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'is_dst', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'regulatory_capital_basis_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'basis_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'basis_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  {
    tableName: 'industry_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'industry_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'industry_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'industry_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'industry_level', type: 'VARCHAR(100)', nullable: true },
      { name: 'industry_standard', type: 'VARCHAR(100)', nullable: true },
      { name: 'parent_industry_id', type: 'BIGINT', nullable: false, fk: 'l1.industry_dim(industry_id)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'enterprise_business_taxonomy',
    scd: 'SCD-1',
    columns: [
      { name: 'managed_segment_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'segment_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'segment_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'parent_segment_id', type: 'BIGINT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'change_event', type: 'VARCHAR(100)', nullable: true },
      { name: 'comments', type: 'VARCHAR(2000)', nullable: true },
      { name: 'create_update_date', type: 'DATE', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'effective_date', type: 'DATE', nullable: true },
      { name: 'long_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'parent', type: 'VARCHAR(100)', nullable: true },
      { name: 'parent_leaf', type: 'CHAR(1)', nullable: true },
      { name: 'requestor', type: 'VARCHAR(100)', nullable: true },
      { name: 'status', type: 'VARCHAR(30)', nullable: true },
      { name: 'substatus', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'substatus_effective_to_date', type: 'DATE', nullable: true },
      { name: 'tree_level', type: 'INTEGER', nullable: true },
    ],
  },
  {
    tableName: 'enterprise_product_taxonomy',
    scd: 'SCD-1',
    columns: [
      { name: 'product_node_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'product_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'product_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'parent_node_id', type: 'BIGINT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'change_event', type: 'VARCHAR(100)', nullable: true },
      { name: 'comments', type: 'VARCHAR(2000)', nullable: true },
      { name: 'create_update_date', type: 'DATE', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'effective_date', type: 'DATE', nullable: true },
      { name: 'fr2590_category_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'long_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'parent', type: 'VARCHAR(100)', nullable: true },
      { name: 'parent_leaf', type: 'CHAR(1)', nullable: true },
      { name: 'requestor', type: 'VARCHAR(100)', nullable: true },
      { name: 'status', type: 'VARCHAR(30)', nullable: true },
      { name: 'substatus', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'substatus_effective_to_date', type: 'DATE', nullable: true },
      { name: 'tree_level', type: 'INTEGER', nullable: true },
    ],
  },
  {
    tableName: 'portfolio_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'portfolio_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'portfolio_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'portfolio_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'parent_portfolio_id', type: 'BIGINT', nullable: true },
      { name: 'portfolio_type', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'org_unit_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'org_unit_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'org_unit_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'org_unit_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'parent_org_unit_id', type: 'BIGINT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'cost_center_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_current', type: 'VARCHAR(100)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'manager_user_id', type: 'BIGINT', nullable: true },
      { name: 'org_unit_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'rating_source',
    scd: 'SCD-1',
    columns: [
      { name: 'rating_source_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'source_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'priority_rank', type: 'VARCHAR(100)', nullable: true },
      { name: 'rating_source_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'rating_source_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'vendor_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  {
    tableName: 'rating_grade_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'rating_grade_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rating_scale_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_scale_dim(rating_scale_id)' },
      { name: 'grade_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'grade_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'default_flag', type: 'CHAR(1)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_current', type: 'VARCHAR(100)', nullable: true },
      { name: 'lgd_downturn', type: 'VARCHAR(100)', nullable: true },
      { name: 'pd_12m', type: 'VARCHAR(100)', nullable: true },
      { name: 'rating_grade_code', type: 'BIGINT', nullable: true },
      { name: 'rating_grade_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'rating_notch', type: 'VARCHAR(100)', nullable: true },
      { name: 'rating_scale_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'collateral_type',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'name', type: 'VARCHAR(200)', nullable: true },
      { name: 'collateral_category', type: 'VARCHAR(50)', nullable: false },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'basel_rwa_weight', type: 'VARCHAR(100)', nullable: true },
      { name: 'hqla_level', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_eligible_crm', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_financial_collateral', type: 'VARCHAR(255)', nullable: true },
      { name: 'minimum_holding_period_days', type: 'VARCHAR(255)', nullable: true },
      { name: 'risk_mitigant_subtype_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'standard_haircut_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'volatility_adjustment_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'interest_rate_index_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'rate_index_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'index_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'index_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'cessation_date', type: 'DATE', nullable: true },
      { name: 'compounding_method', type: 'VARCHAR(100)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'day_count_convention', type: 'VARCHAR(100)', nullable: true },
      { name: 'fallback_spread_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'fallback_to_index_id', type: 'BIGINT', nullable: true },
      { name: 'index_family', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_bmu_compliant', type: 'CHAR(1)', nullable: true },
      { name: 'is_fallback_rate', type: 'CHAR(1)', nullable: true },
      { name: 'publication_source', type: 'VARCHAR(100)', nullable: true },
      { name: 'tenor_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  {
    tableName: 'ledger_account_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'ledger_account_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'account_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'account_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'account_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'account_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_reconciliation_account', type: 'CHAR(1)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'parent_account_id', type: 'BIGINT', nullable: true },
      { name: 'regulatory_report_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'context_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'context_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'context_domain', type: 'VARCHAR(100)', nullable: true },
      { name: 'context_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'context_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'metric_definition_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'metric_definition_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'metric_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'metric_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'calculation_rule_id', type: 'BIGINT', nullable: true },
      { name: 'definition_text', type: 'VARCHAR(100)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'metric_domain', type: 'VARCHAR(100)', nullable: true },
      { name: 'periodicity_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
      { name: 'unit_of_measure', type: 'VARCHAR(100)', nullable: true },
      { name: 'version', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  // ========== Phase 3: Entity masters ==========
  {
    tableName: 'counterparty',
    scd: 'SCD-2',
    columns: [
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'legal_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'counterparty_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'entity_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.entity_type_dim(entity_type_code)' },
      { name: 'industry_id', type: 'BIGINT', nullable: false, fk: 'l1.industry_dim(industry_id)' },
      { name: 'basel_asset_class', type: 'VARCHAR(50)', nullable: true },
      { name: 'basel_risk_grade', type: 'VARCHAR(100)', nullable: true },
      { name: 'call_report_counterparty_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'country_of_domicile', type: 'INTEGER', nullable: true },
      { name: 'country_of_incorporation', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'country_of_risk', type: 'INTEGER', nullable: true },
      { name: 'external_rating_fitch', type: 'VARCHAR(255)', nullable: true },
      { name: 'external_rating_moodys', type: 'VARCHAR(255)', nullable: true },
      { name: 'external_rating_sp', type: 'VARCHAR(100)', nullable: true },
      { name: 'fr2590_counterparty_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'internal_risk_rating', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_affiliated', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_central_counterparty', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_financial_institution', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_insider', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_multilateral_dev_bank', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_parent_flag', type: 'CHAR(1)', nullable: true },
      { name: 'is_public_sector_entity', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_regulated_entity', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_sovereign', type: 'VARCHAR(100)', nullable: true },
      { name: 'lei_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'lgd_unsecured', type: 'VARCHAR(100)', nullable: true },
      { name: 'pd_annual', type: 'VARCHAR(100)', nullable: true },
      { name: 'regulatory_counterparty_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'y14_obligor_type', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'legal_entity',
    scd: 'SCD-2',
    columns: [
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'legal_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'legal_entity_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'entity_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'functional_currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'institution_id', type: 'BIGINT', nullable: true },
      { name: 'is_reporting_entity', type: 'VARCHAR(100)', nullable: true },
      { name: 'lei_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'primary_regulator', type: 'VARCHAR(100)', nullable: true },
      { name: 'rssd_id', type: 'BIGINT', nullable: true },
      { name: 'short_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'tax_id', type: 'BIGINT', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'instrument_master',
    scd: 'SCD-2',
    columns: [
      { name: 'instrument_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'coupon_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'coupon_rate', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'instrument_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'instrument_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'is_callable', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_convertible', type: 'VARCHAR(100)', nullable: true },
      { name: 'issue_date', type: 'DATE', nullable: true },
      { name: 'issuer_counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'product_id', type: 'BIGINT', nullable: true },
      { name: 'seniority', type: 'VARCHAR(100)', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'instrument_identifier',
    scd: 'SCD-1',
    columns: [
      { name: 'instrument_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.instrument_master(instrument_id)' },
      { name: 'id_type', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'effective_start_date', type: 'DATE', nullable: false, pk: true },
      { name: 'effective_end_date', type: 'DATE', nullable: true },
      { name: 'id_value', type: 'VARCHAR(100)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'is_primary', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  // ========== Phase 4: Facility & agreement ==========
  {
    tableName: 'credit_agreement_master',
    scd: 'SCD-2',
    columns: [
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'borrower_counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'lender_legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'agreement_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'origination_date', type: 'DATE', nullable: false },
      { name: 'maturity_date', type: 'DATE', nullable: false },
      { name: 'status_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'agreement_reference', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'facility_master',
    scd: 'SCD-2',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.credit_agreement_master(credit_agreement_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'facility_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'facility_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'facility_status', type: 'VARCHAR(30)', nullable: false },
      { name: 'committed_facility_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'origination_date', type: 'DATE', nullable: false },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'portfolio_id', type: 'BIGINT', nullable: false, fk: 'l1.portfolio_dim(portfolio_id)' },
      { name: 'industry_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_business_taxonomy(managed_segment_id)' },
      { name: 'product_node_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_product_taxonomy(product_node_id)' },
      { name: 'rate_index_id', type: 'BIGINT', nullable: false, fk: 'l1.interest_rate_index_dim(rate_index_id)' },
      { name: 'ledger_account_id', type: 'BIGINT', nullable: false, fk: 'l1.ledger_account_dim(ledger_account_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'all_in_rate_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'amortization_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'created_by', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_count_convention', type: 'INTEGER', nullable: true },
      { name: 'facility_reference', type: 'VARCHAR(100)', nullable: true },
      { name: 'interest_rate_reference', type: 'DECIMAL(8,6)', nullable: true },
      { name: 'interest_rate_spread_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'interest_rate_type', type: 'DECIMAL(8,6)', nullable: true },
      { name: 'next_repricing_date', type: 'DATE', nullable: true },
      { name: 'payment_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'prepayment_penalty_flag', type: 'CHAR(1)', nullable: true },
      { name: 'product_id', type: 'BIGINT', nullable: true },
      { name: 'rate_cap_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'rate_floor_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'region_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'revolving_flag', type: 'CHAR(1)', nullable: true },
    ],
  },
  {
    tableName: 'contract_master',
    scd: 'SCD-2',
    columns: [
      { name: 'contract_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'contract_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'contract_status', type: 'VARCHAR(30)', nullable: false },
      { name: 'effective_start_date', type: 'DATE', nullable: false },
      { name: 'contract_end_date', type: 'DATE', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true },
      { name: 'instrument_id', type: 'BIGINT', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true },
      { name: 'product_node_id', type: 'BIGINT', nullable: true },
      { name: 'source_record_id', type: 'BIGINT', nullable: true },
    ],
  },
  // ========== Phase 5: Netting, collateral, CRM ==========
  {
    tableName: 'netting_agreement',
    scd: 'SCD-2',
    columns: [
      { name: 'netting_agreement_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'governing_law', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_bankruptcy_remote', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_enforceable', type: 'VARCHAR(100)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'margin_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'minimum_transfer_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'netting_agreement_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
      { name: 'threshold_amount', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'netting_set',
    scd: 'SCD-2',
    columns: [
      { name: 'netting_set_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'netting_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.netting_agreement(netting_agreement_id)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'governing_law', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_enforceable_flag', type: 'CHAR(1)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'master_agreement_reference', type: 'VARCHAR(255)', nullable: true },
      { name: 'netting_set_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'netting_set_link',
    scd: 'SCD-2',
    columns: [
      { name: 'netting_set_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: false, fk: 'l1.netting_set(netting_set_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'anchor_id', type: 'BIGINT', nullable: true },
      { name: 'anchor_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'csa_master',
    scd: 'SCD-2',
    columns: [
      { name: 'csa_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'csa_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'eligible_collateral_desc', type: 'VARCHAR(255)', nullable: true },
      { name: 'governing_law', type: 'VARCHAR(100)', nullable: true },
      { name: 'independent_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'margin_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'minimum_transfer_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true },
      { name: 'threshold_amount', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'margin_agreement',
    scd: 'SCD-2',
    columns: [
      { name: 'margin_agreement_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'csa_id', type: 'BIGINT', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'im_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'loaded_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'margin_model', type: 'VARCHAR(100)', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
      { name: 'vm_amount', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'collateral_asset_master',
    scd: 'SCD-2',
    columns: [
      { name: 'collateral_asset_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_type(collateral_type_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'charge_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'collateral_asset_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'collateral_id', type: 'BIGINT', nullable: true },
      { name: 'collateral_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'insurance_expiry_date', type: 'DATE', nullable: true },
      { name: 'insurance_flag', type: 'CHAR(1)', nullable: true },
      { name: 'lien_priority', type: 'VARCHAR(100)', nullable: true },
      { name: 'location_country_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'location_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'original_cost', type: 'VARCHAR(100)', nullable: true },
      { name: 'regulatory_eligible_flag', type: 'CHAR(1)', nullable: true },
      { name: 'revaluation_frequency', type: 'VARCHAR(255)', nullable: true },
      { name: 'source_record_id', type: 'BIGINT', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'valuation_currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'vintage_date', type: 'DATE', nullable: true },
    ],
  },
  {
    tableName: 'collateral_link',
    scd: 'SCD-2',
    columns: [
      { name: 'collateral_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_asset_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_asset_master(collateral_asset_id)' },
      { name: 'anchor_id', type: 'BIGINT', nullable: false },
      { name: 'anchor_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'link_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'pledged_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'pledged_currency_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  {
    tableName: 'collateral_eligibility_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_eligibility_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_type(collateral_type_id)' },
      { name: 'effective_from_date', type: 'DATE', nullable: false },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'eligible_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, fk: 'l1.regulatory_capital_basis_dim(regulatory_capital_basis_id)' },
      { name: 'haircut_method', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'collateral_haircut_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_haircut_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_type(collateral_type_id)' },
      { name: 'effective_from_date', type: 'DATE', nullable: false },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'haircut_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'maturity_bucket_id', type: 'BIGINT', nullable: false, fk: 'l1.maturity_bucket_dim(maturity_bucket_id)' },
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, fk: 'l1.regulatory_capital_basis_dim(regulatory_capital_basis_id)' },
      { name: 'volatility_adjustment_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'crm_eligibility_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'crm_eligibility_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.crm_type_dim(crm_type_code)' },
      { name: 'effective_from_date', type: 'DATE', nullable: false },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'eligible_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, fk: 'l1.regulatory_capital_basis_dim(regulatory_capital_basis_id)' },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'eligibility_conditions', type: 'VARCHAR(255)', nullable: true },
    ],
  },
  {
    tableName: 'crm_protection_master',
    scd: 'SCD-2',
    columns: [
      { name: 'protection_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.crm_type_dim(crm_type_code)' },
      { name: 'beneficiary_legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'notional_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: false },
      { name: 'enforceable_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'coverage_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'governing_law_jurisdiction_id', type: 'BIGINT', nullable: true },
      { name: 'protection_provider_counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'protection_reference', type: 'VARCHAR(100)', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'protection_link',
    scd: 'SCD-2',
    columns: [
      { name: 'protection_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'protection_id', type: 'BIGINT', nullable: false, fk: 'l1.crm_protection_master(protection_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'allocated_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'allocated_currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'allocation_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'anchor_id', type: 'BIGINT', nullable: true },
      { name: 'anchor_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'risk_mitigant_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'risk_mitigant_subtype_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'subtype_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'display_order', type: 'VARCHAR(100)', nullable: true },
      { name: 'eligible_flag', type: 'CHAR(1)', nullable: true },
      { name: 'mitigant_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'parent_group_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'parent_group_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'risk_mitigant_master',
    scd: 'SCD-2',
    columns: [
      { name: 'risk_mitigant_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'risk_mitigant_subtype_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.risk_mitigant_type_dim(risk_mitigant_subtype_code)' },
      { name: 'collateral_asset_id', type: 'BIGINT', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'mitigant_source_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'protection_id', type: 'BIGINT', nullable: true },
      { name: 'provider_counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'source_record_id', type: 'BIGINT', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'risk_mitigant_link',
    scd: 'SCD-2',
    columns: [
      { name: 'risk_mitigant_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'risk_mitigant_id', type: 'BIGINT', nullable: false, fk: 'l1.risk_mitigant_master(risk_mitigant_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'anchor_id', type: 'BIGINT', nullable: true },
      { name: 'anchor_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'collateral_portfolio',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_portfolio_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'portfolio_id', type: 'BIGINT', nullable: false, fk: 'l1.portfolio_dim(portfolio_id)' },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_business_taxonomy(managed_segment_id)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'portfolio_name_override', type: 'VARCHAR(255)', nullable: true },
    ],
  },
  // ========== Phase 6: Hierarchies, relationships, remaining ==========
  {
    tableName: 'counterparty_hierarchy',
    scd: 'Snapshot',
    columns: [
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'immediate_parent_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'ultimate_parent_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'ownership_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'legal_entity_hierarchy',
    scd: 'SCD-2',
    columns: [
      { name: 'hierarchy_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'parent_legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'consolidation_method', type: 'VARCHAR(100)', nullable: true },
      { name: 'hierarchy_level', type: 'VARCHAR(100)', nullable: true },
      { name: 'hierarchy_path', type: 'VARCHAR(100)', nullable: true },
      { name: 'ownership_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'ultimate_parent_legal_entity_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'control_relationship',
    scd: 'SCD-2',
    columns: [
      { name: 'control_relationship_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'parent_counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'subsidiary_counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'control_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'controlled_counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'controller_counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'ownership_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'economic_interdependence_relationship',
    scd: 'SCD-2',
    columns: [
      { name: 'econ_interdep_relationship_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id_1', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'counterparty_id_2', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'interdependence_strength_score', type: 'VARCHAR(255)', nullable: true },
      { name: 'interdependence_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'rationale', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'credit_agreement_counterparty_participation',
    scd: 'SCD-2',
    columns: [
      { name: 'agreement_participation_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.credit_agreement_master(credit_agreement_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.counterparty_role_dim(counterparty_role_code)' },
      { name: 'is_primary_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'participation_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'source_record_id', type: 'BIGINT', nullable: false },
      { name: 'role_priority_rank', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'facility_counterparty_participation',
    scd: 'SCD-2',
    columns: [
      { name: 'facility_participation_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.counterparty_role_dim(counterparty_role_code)' },
      { name: 'is_primary_flag', type: 'CHAR(1)', nullable: true },
      { name: 'participation_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'role_priority_rank', type: 'VARCHAR(100)', nullable: true },
      { name: 'source_record_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'sccl_counterparty_group',
    scd: 'SCD-1',
    columns: [
      { name: 'sccl_group_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'group_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'created_by', type: 'VARCHAR(100)', nullable: true },
      { name: 'grouping_basis', type: 'VARCHAR(100)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'run_version_id', type: 'BIGINT', nullable: true },
      { name: 'sccl_group_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'ultimate_parent_counterparty_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'sccl_counterparty_group_member',
    scd: 'SCD-1',
    columns: [
      { name: 'member_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'sccl_group_id', type: 'BIGINT', nullable: false, fk: 'l1.sccl_counterparty_group(sccl_group_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'effective_end_date', type: 'DATE', nullable: true },
      { name: 'effective_start_date', type: 'DATE', nullable: true },
      { name: 'included_flag', type: 'CHAR(1)', nullable: true },
      { name: 'member_role_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'ownership_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'sccl_group_member_id', type: 'BIGINT', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'limit_rule',
    scd: 'SCD-1',
    columns: [
      { name: 'limit_rule_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rule_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'rule_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'inner_threshold_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'limit_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'limit_scope', type: 'VARCHAR(30)', nullable: true },
      { name: 'limit_type', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'outer_threshold_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'risk_tier', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'limit_threshold',
    scd: 'SCD-1',
    columns: [
      { name: 'limit_threshold_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'limit_rule_id', type: 'BIGINT', nullable: false, fk: 'l1.limit_rule(limit_rule_id)' },
      { name: 'threshold_value', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'direction', type: 'VARCHAR(100)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'escalation_action', type: 'VARCHAR(100)', nullable: true },
      { name: 'threshold_lower_abs', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'threshold_lower_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'threshold_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'threshold_upper_abs', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'threshold_upper_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'fx_rate',
    scd: 'Snapshot',
    columns: [
      { name: 'fx_rate_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'from_currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'to_currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'rate', type: 'DECIMAL(18,10)', nullable: true },
      { name: 'rate_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'effective_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'loaded_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'provider', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'run_control',
    scd: 'SCD-1',
    columns: [
      { name: 'run_control_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'run_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'certified_by', type: 'VARCHAR(100)', nullable: true },
      { name: 'certified_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'created_by', type: 'VARCHAR(100)', nullable: true },
      { name: 'cutoff_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'notes', type: 'VARCHAR(2000)', nullable: true },
      { name: 'run_version_id', type: 'BIGINT', nullable: true },
      { name: 'status', type: 'VARCHAR(30)', nullable: true },
    ],
  },
  {
    tableName: 'report_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'report_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'report_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'report_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'regulator_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  {
    tableName: 'reporting_calendar_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'reporting_calendar_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'calendar_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'calendar_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'cutoff_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'fiscal_quarter', type: 'DATE', nullable: true },
      { name: 'fiscal_year', type: 'DATE', nullable: true },
      { name: 'is_period_end', type: 'DATE', nullable: true },
      { name: 'period_end_date', type: 'DATE', nullable: true },
      { name: 'period_start_date', type: 'DATE', nullable: true },
      { name: 'regulator_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  {
    tableName: 'reporting_entity_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'reporting_entity_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'entity_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'entity_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'consolidation_basis', type: 'DATE', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'functional_currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'is_current', type: 'VARCHAR(100)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'reporting_entity_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'reporting_entity_name', type: 'VARCHAR(200)', nullable: true },
    ],
  },
  {
    tableName: 'model_registry_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'model_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'model_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'model_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'documentation_url', type: 'VARCHAR(100)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_current', type: 'VARCHAR(100)', nullable: true },
      { name: 'model_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'model_version', type: 'VARCHAR(100)', nullable: true },
      { name: 'owner_org_unit_id', type: 'BIGINT', nullable: true },
      { name: 'regulatory_approved_flag', type: 'CHAR(1)', nullable: true },
      { name: 'validation_status', type: 'VARCHAR(30)', nullable: true },
    ],
  },
  {
    tableName: 'rule_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'rule_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rule_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'rule_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'approved_by', type: 'VARCHAR(100)', nullable: true },
      { name: 'approved_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'input_variables', type: 'VARCHAR(100)', nullable: true },
      { name: 'output_variable', type: 'VARCHAR(100)', nullable: true },
      { name: 'rule_expression', type: 'VARCHAR(100)', nullable: true },
      { name: 'rule_type', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'validation_check_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'check_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'check_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'check_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'check_rule_id', type: 'BIGINT', nullable: false, fk: 'l1.rule_registry(rule_id)' },
      { name: 'target_table', type: 'VARCHAR(100)', nullable: true },
      { name: 'target_column', type: 'VARCHAR(100)', nullable: true },
      { name: 'severity', type: 'VARCHAR(100)', nullable: true },
      { name: 'owner_id', type: 'BIGINT', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'validation_check_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'reconciliation_control',
    scd: 'SCD-1',
    columns: [
      { name: 'reconciliation_control_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'control_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'actual_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'check_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'check_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'executed_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'expected_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'owner_id', type: 'BIGINT', nullable: true },
      { name: 'recon_id', type: 'BIGINT', nullable: true },
      { name: 'remediation_ticket_id', type: 'BIGINT', nullable: true },
      { name: 'report_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'run_version_id', type: 'BIGINT', nullable: true },
      { name: 'status', type: 'VARCHAR(30)', nullable: true },
      { name: 'tolerance_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'variance_value', type: 'DECIMAL(18,4)', nullable: true },
    ],
  },
  {
    tableName: 'regulatory_mapping',
    scd: 'SCD-1',
    columns: [
      { name: 'regulatory_mapping_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'mapping_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'calculation_rule_id', type: 'BIGINT', nullable: true },
      { name: 'effective_end_date', type: 'DATE', nullable: true },
      { name: 'effective_start_date', type: 'DATE', nullable: true },
      { name: 'line_item_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'mapping_id', type: 'BIGINT', nullable: true },
      { name: 'mdrm_id', type: 'BIGINT', nullable: true },
      { name: 'metric_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'notes', type: 'VARCHAR(2000)', nullable: true },
      { name: 'relationship_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'report_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'schedule_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_mdrm_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_report_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
      { name: 'target_mdrm_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'target_report_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'tolerance_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'transformation_rule', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'report_cell_definition',
    scd: 'SCD-1',
    columns: [
      { name: 'report_cell_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'report_id', type: 'BIGINT', nullable: false, fk: 'l1.report_registry(report_id)' },
      { name: 'cell_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'cell_definition', type: 'TEXT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'calculation_rule_id', type: 'BIGINT', nullable: true },
      { name: 'cell_datatype', type: 'VARCHAR(100)', nullable: true },
      { name: 'cell_id', type: 'BIGINT', nullable: true },
      { name: 'cell_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'is_derived_flag', type: 'CHAR(1)', nullable: true },
      { name: 'line_item_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'report_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'schedule_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'uom', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'rating_mapping',
    scd: 'SCD-1',
    columns: [
      { name: 'rating_mapping_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rating_scale_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_scale_dim(rating_scale_id)' },
      { name: 'rating_source_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_source(rating_source_id)' },
      { name: 'external_rating', type: 'VARCHAR(50)', nullable: true },
      { name: 'internal_grade_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_grade_dim(rating_grade_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'approved_by', type: 'VARCHAR(100)', nullable: true },
      { name: 'approved_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'is_current', type: 'VARCHAR(100)', nullable: true },
      { name: 'mapping_method', type: 'VARCHAR(100)', nullable: true },
      { name: 'model_id', type: 'BIGINT', nullable: true },
      { name: 'rating_grade_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_rating_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'scenario_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'scenario_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'scenario_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'scenario_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'scenario_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'is_active', type: 'VARCHAR(100)', nullable: true },
      { name: 'regulatory_scenario_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'scenario_end_date', type: 'DATE', nullable: true },
      { name: 'scenario_horizon_months', type: 'VARCHAR(255)', nullable: true },
      { name: 'scenario_start_date', type: 'DATE', nullable: true },
      { name: 'shock_parameters_json', type: 'VARCHAR(255)', nullable: true },
    ],
  },
];
