/**
 * L1 table definitions in creation (dependency) order.
 * Matches REQUIREMENTS.md L1 specs. PK/FK ensure referential integrity for seed data.
 */
import type { TableDef } from './types';

export const L1_TABLES: TableDef[] = [
  // ========== Phase 1: Reference dims (no FK) ==========
  {
    tableName: 'currency_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'currency_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'currency_symbol', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_active', type: 'VARCHAR(100)', nullable: true },
      { name: 'iso_numeric', type: 'VARCHAR(100)', nullable: true },
      { name: 'minor_unit_decimals', type: 'INTEGER', nullable: true },
    ],
  },
  {
    tableName: 'country_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'country_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'is_active', type: 'VARCHAR(100)', nullable: true },
      { name: 'region_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'basel_country_risk_weight', type: 'VARCHAR(255)', nullable: true },
      { name: 'is_developed_market', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_fatf_high_risk', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_ofac_sanctioned', type: 'VARCHAR(100)', nullable: true },
      { name: 'iso_alpha_3', type: 'VARCHAR(100)', nullable: true },
      { name: 'iso_numeric', type: 'VARCHAR(100)', nullable: true },
      { name: 'jurisdiction_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'region_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'region_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'region_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'regulatory_jurisdiction',
    scd: 'SCD-0',
    columns: [
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'jurisdiction_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'entity_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'entity_type_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'entity_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'credit_event_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'credit_event_type_code', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_event_type_id', type: 'BIGINT', nullable: false },
      { name: 'credit_event_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'default_trigger_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'credit_status_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'credit_status_code', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_status_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'default_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'delinquency_bucket', type: 'VARCHAR(100)', nullable: true },
      { name: 'status_category', type: 'VARCHAR(50)', nullable: false },
    ],
  },
  {
    tableName: 'exposure_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'exposure_type_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'exposure_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'exposure_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'amendment_status_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'amendment_status_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'amendment_status_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'status_group', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_terminal_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'amendment_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'amendment_type_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'amendment_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'default_definition_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'default_definition_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'default_definition_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'days_past_due_threshold', type: 'VARCHAR(255)', nullable: true },
      { name: 'credit_event_trigger_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'materiality_threshold_amt', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'maturity_bucket_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'maturity_bucket_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'bucket_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'bucket_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'fr2590_category_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'fr2590_category_code', type: 'BIGINT', nullable: false, pk: true },
      { name: 'category_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'definition', type: 'VARCHAR(100)', nullable: true },
      { name: 'display_order', type: 'VARCHAR(100)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'counterparty_role_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'role_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'role_category', type: 'VARCHAR(50)', nullable: false },
      { name: 'is_risk_bearing_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'rating_scale_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'rating_scale_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'scale_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'crm_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'crm_type_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  // ========== Phase 2 ==========
  {
    tableName: 'source_system_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'source_system_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'source_system_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'data_domain', type: 'VARCHAR(100)', nullable: true },
      { name: 'ingestion_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'system_owner', type: 'VARCHAR(100)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'date_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'date_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'calendar_date', type: 'DATE', nullable: true },
      { name: 'calendar_year', type: 'VARCHAR(100)', nullable: true },
      { name: 'calendar_quarter', type: 'VARCHAR(100)', nullable: true },
      { name: 'calendar_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_of_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_of_week', type: 'VARCHAR(100)', nullable: true },
      { name: 'day_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'fiscal_year', type: 'VARCHAR(100)', nullable: true },
      { name: 'fiscal_quarter', type: 'VARCHAR(100)', nullable: true },
      { name: 'fiscal_month', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_weekend', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_month_end', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_quarter_end', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_year_end', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_us_business_day', type: 'VARCHAR(100)', nullable: true },
      { name: 'is_us_bank_holiday', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'date_time_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'date_time_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'date_id', type: 'BIGINT', nullable: false, fk: 'l1.date_dim(date_id)' },
      { name: 'timestamp_utc', type: 'TIMESTAMP', nullable: true },
      { name: 'hour_of_day', type: 'VARCHAR(100)', nullable: true },
      { name: 'minute_of_hour', type: 'VARCHAR(100)', nullable: true },
      { name: 'second_of_minute', type: 'VARCHAR(100)', nullable: true },
      { name: 'timezone_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'is_dst', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'regulatory_capital_basis_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'basis_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'basis_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'industry_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'industry_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'industry_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'industry_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'industry_level', type: 'VARCHAR(100)', nullable: true },
      { name: 'industry_standard', type: 'VARCHAR(100)', nullable: true },
      { name: 'parent_industry_id', type: 'BIGINT', nullable: false, fk: 'l1.industry_dim(industry_id)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'enterprise_business_taxonomy',
    scd: 'SCD-1',
    columns: [
      { name: 'managed_segment_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'segment_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'segment_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'parent_segment_id', type: 'BIGINT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'enterprise_product_taxonomy',
    scd: 'SCD-1',
    columns: [
      { name: 'product_node_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'product_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'product_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'parent_node_id', type: 'BIGINT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'portfolio_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'portfolio_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'portfolio_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'portfolio_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'org_unit_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'org_unit_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'org_unit_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'org_unit_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'parent_org_unit_id', type: 'BIGINT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'rating_source',
    scd: 'SCD-1',
    columns: [
      { name: 'rating_source_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'source_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'rating_grade_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'rating_grade_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rating_scale_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_scale_dim(rating_scale_id)' },
      { name: 'grade_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'grade_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'collateral_type',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'name', type: 'VARCHAR(200)', nullable: true },
      { name: 'collateral_category', type: 'VARCHAR(50)', nullable: false },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'interest_rate_index_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'rate_index_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'index_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'index_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'ledger_account_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'ledger_account_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'account_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'account_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'context_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'context_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'context_domain', type: 'VARCHAR(100)', nullable: true },
      { name: 'context_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'context_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'is_active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'metric_definition_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'metric_definition_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'metric_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'metric_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  // ========== Phase 3: Entity masters ==========
  {
    tableName: 'counterparty',
    scd: 'SCD-2',
    columns: [
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'legal_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'counterparty_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'entity_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.entity_type_dim(entity_type_code)' },
      { name: 'industry_id', type: 'BIGINT', nullable: false, fk: 'l1.industry_dim(industry_id)' },
    ],
  },
  {
    tableName: 'legal_entity',
    scd: 'SCD-2',
    columns: [
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'legal_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
    ],
  },
  {
    tableName: 'instrument_master',
    scd: 'SCD-2',
    columns: [
      { name: 'instrument_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'instrument_identifier',
    scd: 'SCD-1',
    columns: [
      { name: 'instrument_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.instrument_master(instrument_id)' },
      { name: 'id_type', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'effective_start_date', type: 'DATE', nullable: false, pk: true },
      { name: 'effective_end_date', type: 'DATE', nullable: true },
      { name: 'id_value', type: 'VARCHAR(100)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
    ],
  },
  // ========== Phase 4: Facility & agreement ==========
  {
    tableName: 'credit_agreement_master',
    scd: 'SCD-2',
    columns: [
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'borrower_counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'lender_legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'agreement_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'origination_date', type: 'DATE', nullable: false },
      { name: 'maturity_date', type: 'DATE', nullable: false },
      { name: 'status_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'agreement_reference', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'facility_master',
    scd: 'SCD-2',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.credit_agreement_master(credit_agreement_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'facility_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'facility_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'facility_status', type: 'VARCHAR(30)', nullable: false },
      { name: 'committed_facility_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'origination_date', type: 'DATE', nullable: false },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'portfolio_id', type: 'BIGINT', nullable: false, fk: 'l1.portfolio_dim(portfolio_id)' },
      { name: 'industry_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_business_taxonomy(managed_segment_id)' },
      { name: 'product_node_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_product_taxonomy(product_node_id)' },
      { name: 'rate_index_id', type: 'BIGINT', nullable: false, fk: 'l1.interest_rate_index_dim(rate_index_id)' },
      { name: 'ledger_account_id', type: 'BIGINT', nullable: false, fk: 'l1.ledger_account_dim(ledger_account_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'contract_master',
    scd: 'SCD-2',
    columns: [
      { name: 'contract_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'contract_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'contract_status', type: 'VARCHAR(30)', nullable: false },
      { name: 'effective_start_date', type: 'DATE', nullable: false },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  // ========== Phase 5: Netting, collateral, CRM ==========
  {
    tableName: 'netting_agreement',
    scd: 'SCD-2',
    columns: [
      { name: 'netting_agreement_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
    ],
  },
  {
    tableName: 'netting_set',
    scd: 'SCD-2',
    columns: [
      { name: 'netting_set_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'netting_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.netting_agreement(netting_agreement_id)' },
    ],
  },
  {
    tableName: 'netting_set_link',
    scd: 'SCD-2',
    columns: [
      { name: 'netting_set_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: false, fk: 'l1.netting_set(netting_set_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
    ],
  },
  {
    tableName: 'csa_master',
    scd: 'SCD-2',
    columns: [
      { name: 'csa_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
    ],
  },
  {
    tableName: 'margin_agreement',
    scd: 'SCD-2',
    columns: [
      { name: 'margin_agreement_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
    ],
  },
  {
    tableName: 'collateral_asset_master',
    scd: 'SCD-2',
    columns: [
      { name: 'collateral_asset_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_type(collateral_type_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'country_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.country_dim(country_code)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
    ],
  },
  {
    tableName: 'collateral_link',
    scd: 'SCD-2',
    columns: [
      { name: 'collateral_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_asset_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_asset_master(collateral_asset_id)' },
      { name: 'anchor_id', type: 'BIGINT', nullable: false },
      { name: 'anchor_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
    ],
  },
  {
    tableName: 'collateral_eligibility_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_eligibility_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_type(collateral_type_id)' },
      { name: 'effective_from_date', type: 'DATE', nullable: false },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'eligible_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, fk: 'l1.regulatory_capital_basis_dim(regulatory_capital_basis_id)' },
    ],
  },
  {
    tableName: 'collateral_haircut_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_haircut_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'collateral_type_id', type: 'BIGINT', nullable: false, fk: 'l1.collateral_type(collateral_type_id)' },
      { name: 'effective_from_date', type: 'DATE', nullable: false },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'haircut_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'maturity_bucket_id', type: 'BIGINT', nullable: false, fk: 'l1.maturity_bucket_dim(maturity_bucket_id)' },
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, fk: 'l1.regulatory_capital_basis_dim(regulatory_capital_basis_id)' },
    ],
  },
  {
    tableName: 'crm_eligibility_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'crm_eligibility_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.crm_type_dim(crm_type_code)' },
      { name: 'effective_from_date', type: 'DATE', nullable: false },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'eligible_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'regulatory_capital_basis_id', type: 'BIGINT', nullable: false, fk: 'l1.regulatory_capital_basis_dim(regulatory_capital_basis_id)' },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
    ],
  },
  {
    tableName: 'crm_protection_master',
    scd: 'SCD-2',
    columns: [
      { name: 'protection_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.crm_type_dim(crm_type_code)' },
      { name: 'beneficiary_legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'notional_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: false },
      { name: 'enforceable_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'protection_link',
    scd: 'SCD-2',
    columns: [
      { name: 'protection_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'protection_id', type: 'BIGINT', nullable: false, fk: 'l1.crm_protection_master(protection_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
    ],
  },
  {
    tableName: 'risk_mitigant_type_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'risk_mitigant_subtype_code', type: 'VARCHAR(20)', nullable: false, pk: true },
      { name: 'subtype_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'risk_mitigant_master',
    scd: 'SCD-2',
    columns: [
      { name: 'risk_mitigant_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'risk_mitigant_subtype_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.risk_mitigant_type_dim(risk_mitigant_subtype_code)' },
    ],
  },
  {
    tableName: 'risk_mitigant_link',
    scd: 'SCD-2',
    columns: [
      { name: 'risk_mitigant_link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'risk_mitigant_id', type: 'BIGINT', nullable: false, fk: 'l1.risk_mitigant_master(risk_mitigant_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
    ],
  },
  {
    tableName: 'collateral_portfolio',
    scd: 'SCD-1',
    columns: [
      { name: 'collateral_portfolio_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'portfolio_id', type: 'BIGINT', nullable: false, fk: 'l1.portfolio_dim(portfolio_id)' },
      { name: 'description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_business_taxonomy(managed_segment_id)' },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  // ========== Phase 6: Hierarchies, relationships, remaining ==========
  {
    tableName: 'counterparty_hierarchy',
    scd: 'Snapshot',
    columns: [
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'immediate_parent_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'ultimate_parent_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'ownership_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'legal_entity_hierarchy',
    scd: 'SCD-2',
    columns: [
      { name: 'hierarchy_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'parent_legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
    ],
  },
  {
    tableName: 'control_relationship',
    scd: 'SCD-2',
    columns: [
      { name: 'control_relationship_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'parent_counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'subsidiary_counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
    ],
  },
  {
    tableName: 'economic_interdependence_relationship',
    scd: 'SCD-2',
    columns: [
      { name: 'econ_interdep_relationship_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id_1', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'counterparty_id_2', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
    ],
  },
  {
    tableName: 'credit_agreement_counterparty_participation',
    scd: 'SCD-2',
    columns: [
      { name: 'agreement_participation_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.credit_agreement_master(credit_agreement_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.counterparty_role_dim(counterparty_role_code)' },
      { name: 'is_primary_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
      { name: 'participation_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'source_record_id', type: 'BIGINT', nullable: false },
    ],
  },
  {
    tableName: 'facility_counterparty_participation',
    scd: 'SCD-2',
    columns: [
      { name: 'facility_participation_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.counterparty_role_dim(counterparty_role_code)' },
    ],
  },
  {
    tableName: 'sccl_counterparty_group',
    scd: 'SCD-1',
    columns: [
      { name: 'sccl_group_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'group_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'sccl_counterparty_group_member',
    scd: 'SCD-1',
    columns: [
      { name: 'member_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'sccl_group_id', type: 'BIGINT', nullable: false, fk: 'l1.sccl_counterparty_group(sccl_group_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'limit_rule',
    scd: 'SCD-1',
    columns: [
      { name: 'limit_rule_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rule_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'rule_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'limit_threshold',
    scd: 'SCD-1',
    columns: [
      { name: 'limit_threshold_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'limit_rule_id', type: 'BIGINT', nullable: false, fk: 'l1.limit_rule(limit_rule_id)' },
      { name: 'threshold_value', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'fx_rate',
    scd: 'Snapshot',
    columns: [
      { name: 'fx_rate_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'from_currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'to_currency_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.currency_dim(currency_code)' },
      { name: 'rate', type: 'DECIMAL(18,10)', nullable: true },
      { name: 'rate_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'effective_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'loaded_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'provider', type: 'VARCHAR(100)', nullable: true },
    ],
  },
  {
    tableName: 'run_control',
    scd: 'SCD-1',
    columns: [
      { name: 'run_control_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'run_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'report_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'report_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'report_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'report_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'reporting_calendar_dim',
    scd: 'SCD-0',
    columns: [
      { name: 'reporting_calendar_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'calendar_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'calendar_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'reporting_entity_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'reporting_entity_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'entity_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'entity_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: false, fk: 'l1.legal_entity(legal_entity_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'model_registry_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'model_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'model_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'model_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'rule_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'rule_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rule_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'rule_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'validation_check_registry',
    scd: 'SCD-1',
    columns: [
      { name: 'check_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'check_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'check_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'check_rule_id', type: 'BIGINT', nullable: false, fk: 'l1.rule_registry(rule_id)' },
      { name: 'target_table', type: 'VARCHAR(100)', nullable: true },
      { name: 'target_column', type: 'VARCHAR(100)', nullable: true },
      { name: 'severity', type: 'VARCHAR(100)', nullable: true },
      { name: 'owner_id', type: 'BIGINT', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: false, check: "value IN ('Y','N')", default: "'N'" },
    ],
  },
  {
    tableName: 'reconciliation_control',
    scd: 'SCD-1',
    columns: [
      { name: 'reconciliation_control_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'control_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'regulatory_mapping',
    scd: 'SCD-1',
    columns: [
      { name: 'regulatory_mapping_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'mapping_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'jurisdiction_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.regulatory_jurisdiction(jurisdiction_code)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'report_cell_definition',
    scd: 'SCD-1',
    columns: [
      { name: 'report_cell_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'report_id', type: 'BIGINT', nullable: false, fk: 'l1.report_registry(report_id)' },
      { name: 'cell_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'cell_definition', type: 'TEXT', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'rating_mapping',
    scd: 'SCD-1',
    columns: [
      { name: 'rating_mapping_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'rating_scale_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_scale_dim(rating_scale_id)' },
      { name: 'rating_source_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_source(rating_source_id)' },
      { name: 'external_rating', type: 'VARCHAR(50)', nullable: true },
      { name: 'internal_grade_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_grade_dim(rating_grade_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  {
    tableName: 'scenario_dim',
    scd: 'SCD-1',
    columns: [
      { name: 'scenario_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'scenario_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'scenario_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'scenario_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: false, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: false, default: 'CURRENT_TIMESTAMP' },
      { name: 'updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
];
