#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# Export MVP seed data as a single self-contained SQL file.
#
# Usage:
#   npm run db:export
#   # or directly:
#   bash scripts/export-mvp-sql.sh
#
# Output: sql/exports/credit_dw_mvp.sql
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$ROOT_DIR/sql/exports"
OUT_FILE="$OUT_DIR/credit_dw_mvp.sql"

echo "=== Generating MVP seed data ==="
npx tsx "$ROOT_DIR/scripts/l1/generate.ts" --profile=mvp
npx tsx "$ROOT_DIR/scripts/l2/generate.ts" --profile=mvp

echo ""
echo "=== Assembling combined SQL ==="
mkdir -p "$OUT_DIR"

cat > "$OUT_FILE" << 'HEADER'
-- ═══════════════════════════════════════════════════════════════════
-- Credit Data Warehouse — MVP Seed Data Export
-- ═══════════════════════════════════════════════════════════════════
--
-- Usage:
--   createdb credit_dw
--   psql -d credit_dw -f credit_dw_mvp.sql
--
-- Contents:
--   L1: 79 reference/master tables (100 counterparties, 405 facilities)
--   L2: 27 snapshot/event tables (5 cycles × 405 facilities)
--   L3: 49 reporting tables (DDL only — populate via orchestrator)
--
-- All data uses as_of_date = 2025-01-31.
-- L3 population: CALL l3.run_full_population('RUN_MVP_001','2025-01-31');
--
-- Generated by: npm run db:export
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

HEADER

echo "-- ═══════ L1: Schema + DDL ═══════" >> "$OUT_FILE"
cat "$ROOT_DIR/scripts/l1/output/ddl.sql" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "-- ═══════ L1: Seed Data ═══════" >> "$OUT_FILE"
cat "$ROOT_DIR/scripts/l1/output/seed.sql" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "-- ═══════ L2: Schema + DDL ═══════" >> "$OUT_FILE"
cat "$ROOT_DIR/scripts/l2/output/ddl.sql" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "-- ═══════ L2: Seed Data ═══════" >> "$OUT_FILE"
cat "$ROOT_DIR/scripts/l2/output/seed.sql" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "-- ═══════ L3: Schema + DDL (no seed — use orchestrator) ═══════" >> "$OUT_FILE"
cat "$ROOT_DIR/sql/l3/01_DDL_all_tables.sql" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "COMMIT;" >> "$OUT_FILE"

# Print summary
SIZE=$(wc -c < "$OUT_FILE" | tr -d ' ')
LINES=$(wc -l < "$OUT_FILE" | tr -d ' ')
echo ""
echo "=== Export complete ==="
echo "  File: $OUT_FILE"
echo "  Size: $((SIZE / 1024)) KB ($LINES lines)"
echo ""
echo "To load into PostgreSQL:"
echo "  createdb credit_dw"
echo "  psql -d credit_dw -f $OUT_FILE"
