"""
Generate GSIB Data Model Dictionary Excel file.
Produces a professionally formatted .xlsx with separate tabs for each layer:
  - L1 Reference & Master Data (79 tables)
  - L2 Transactional & Snapshot Data (27 tables)
  - L3 Reporting & Analytics (50 tables)
  - Metric Library (3 tables)
"""

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import os

# ── styling ──────────────────────────────────────────────────────────────────
HEADER_FONT = Font(name="Calibri", bold=True, size=11, color="FFFFFF")
HEADER_FILL = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
HEADER_ALIGN = Alignment(horizontal="center", vertical="center", wrap_text=True)

BODY_FONT = Font(name="Calibri", size=10)
BODY_ALIGN = Alignment(vertical="top", wrap_text=True)

ALT_ROW_FILL = PatternFill(start_color="D6E4F0", end_color="D6E4F0", fill_type="solid")
WHITE_FILL = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")

THIN_BORDER = Border(
    left=Side(style="thin", color="B0B0B0"),
    right=Side(style="thin", color="B0B0B0"),
    top=Side(style="thin", color="B0B0B0"),
    bottom=Side(style="thin", color="B0B0B0"),
)

COLUMNS = [
    ("Table Name", 38),
    ("Description", 60),
    ("Business Purpose & Functionality", 80),
    ("Regulatory Relevance", 55),
    ("Layer", 12),
    ("Tier / Execution Order", 18),
    ("Primary Key", 50),
    ("Key Foreign Keys / Relationships", 70),
]


def style_header(ws):
    for col_idx, (col_name, width) in enumerate(COLUMNS, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = HEADER_ALIGN
        cell.border = THIN_BORDER
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions


def add_row(ws, row_num, values):
    fill = ALT_ROW_FILL if row_num % 2 == 0 else WHITE_FILL
    for col_idx, val in enumerate(values, 1):
        cell = ws.cell(row=row_num, column=col_idx, value=val)
        cell.font = BODY_FONT
        cell.alignment = BODY_ALIGN
        cell.fill = fill
        cell.border = THIN_BORDER


# ── L1 table definitions ─────────────────────────────────────────────────────
L1_TABLES = [
    # (table_name, description, business_purpose, regulatory_relevance, tier, pk, fk)
    ("currency_dim", "ISO currency reference dimension", "Golden source for all currency codes used across the credit risk data warehouse. Provides ISO standard currency metadata including symbols, numeric codes, minor unit precision, and G10 classification. Supports multi-currency exposure aggregation, FX conversion, and consistent denomination across all reporting layers.", "Required for Basel III multi-currency netting and exposure aggregation; supports FR Y-9C, FR 2590, and Call Report denominations.", "Dimension", "currency_code", "None (root dimension)"),
    ("country_dim", "Country and sovereign risk reference dimension", "Master record for all countries referenced in counterparty domicile, facility jurisdiction, and collateral location. Encodes Basel country risk weights, developed market classification, FATF high-risk designation, and OFAC sanctions flags. Drives geographic risk concentration analysis and regulatory treatment selection.", "Basel III sovereign risk weighting; FATF AML/CFT compliance; OFAC sanctions screening; FR 2590 country-of-risk attribution.", "Dimension", "country_code", "jurisdiction_id -> regulatory_jurisdiction"),
    ("region_dim", "Geographic region grouping dimension", "Defines geographic regions for portfolio segmentation, concentration reporting, and executive dashboard views. Supports hierarchical region grouping for drill-down analytics.", "Supports geographic concentration limits under Regulation XX and SCCL; used in CCAR stress scenario geographic segmentation.", "Dimension", "region_code", "None (root dimension)"),
    ("regulatory_jurisdiction", "Regulatory jurisdiction reference", "Catalogs regulatory frameworks and jurisdictions (e.g., US OCC, UK PRA, ECB). Maps each jurisdiction to its primary regulator and applicable regulatory framework. Used to determine which regulatory capital rules, default definitions, and collateral eligibility criteria apply to a given exposure.", "Foundational for multi-jurisdictional GSIB compliance; determines applicable Basel framework (SA vs IRB), default definitions, and regulatory reporting obligations.", "Dimension", "jurisdiction_code", "None (root dimension)"),
    ("entity_type_dim", "Counterparty entity type classification", "Classifies counterparties by legal entity type (corporation, bank, sovereign, PSE, MDB). Drives regulatory counterparty class assignment for Basel risk weight determination and Call Report categorization.", "Basel III counterparty classification for SA and IRB risk weight assignment; Call Report and FR Y-14 counterparty type mapping.", "Dimension", "entity_type_code", "None (root dimension)"),
    ("credit_event_type_dim", "Credit event type classification", "Defines the taxonomy of credit events (default, bankruptcy, restructuring, cross-default, etc.) with flags indicating which events constitute regulatory default triggers. Used to classify and track credit deterioration across the portfolio.", "Basel III default event recognition per CRE 44; aligns with ISDA credit event definitions for derivative counterparties.", "Dimension", "credit_event_type_code", "None (root dimension)"),
    ("credit_status_dim", "Credit facility status dimension", "Enumerates facility credit statuses (performing, watch list, substandard, doubtful, loss) with delinquency bucket mapping and category classification. Drives NPL identification and credit quality segmentation.", "Maps to regulatory asset quality classifications per OCC Handbook; supports Call Report past-due and nonaccrual categorization.", "Dimension", "credit_status_code", "None (root dimension)"),
    ("exposure_type_dim", "Exposure type and Basel classification", "Defines exposure types (loans, guarantees, derivatives, SFTs, commitments) with associated Basel exposure class, credit conversion factors (CCF), on/off-balance-sheet indicators, and SA-CCR asset class mapping.", "Basel III/IV exposure classification; CCF assignment for off-balance-sheet items; SA-CCR asset class mapping for derivative exposures.", "Dimension", "exposure_type_id", "product_id -> enterprise_product_taxonomy"),
    ("amendment_status_dim", "Amendment lifecycle status codes", "Tracks amendment workflow states (pending, approved, completed, rejected) with terminal state flags. Supports amendment pipeline monitoring and facility modification governance.", "Supports OCC guidance on credit facility modification tracking and workout reporting.", "Dimension", "amendment_status_code", "None (root dimension)"),
    ("amendment_type_dim", "Amendment type classification", "Categorizes types of facility amendments (maturity extension, pricing change, covenant modification, commitment increase/decrease). Enables systematic tracking of credit terms modifications.", "Supports regulatory scrutiny of TDR (Troubled Debt Restructuring) classification under ASC 310-40; OCC amendment monitoring requirements.", "Dimension", "amendment_type_code", "None (root dimension)"),
    ("default_definition_dim", "Default definition by jurisdiction", "Encodes jurisdiction-specific default definitions including days-past-due thresholds, materiality thresholds, and credit event triggers. Ensures consistent default identification aligned with local regulatory requirements.", "Basel III CRE 44 default definition; supports multi-jurisdictional GSIB default recognition with jurisdiction-specific thresholds (e.g., 90 DPD vs 180 DPD).", "Dimension", "default_definition_id", "jurisdiction_code -> regulatory_jurisdiction"),
    ("maturity_bucket_dim", "Maturity bucket classification", "Defines time-band buckets for maturity analysis and collateral haircut schedules. Used in cash flow modeling, ALM gap analysis, and regulatory haircut determination by residual maturity.", "Basel III collateral haircut schedules by residual maturity; supports LCR/NSFR maturity bucketing requirements.", "Dimension", "maturity_bucket_id", "jurisdiction_code -> regulatory_jurisdiction"),
    ("fr2590_category_dim", "FR 2590 reporting category dimension", "Maps product and exposure types to FR 2590 regulatory report categories. Enables systematic classification of positions for Federal Reserve large exposure reporting.", "Directly maps to FR 2590 schedule line items; required for top borrower large exposure reporting to the Federal Reserve.", "Dimension", "fr2590_category_code", "None (root dimension)"),
    ("counterparty_role_dim", "Counterparty role classification", "Defines roles a counterparty can assume in credit relationships (borrower, guarantor, co-borrower, collateral provider, protection seller). Includes risk-bearing flag to identify which roles carry credit exposure.", "Supports Basel III CRM recognition requirements; identifies risk-bearing vs non-risk-bearing roles for exposure attribution.", "Dimension", "counterparty_role_code", "None (root dimension)"),
    ("rating_scale_dim", "Rating scale definition", "Defines rating scales used across internal and external rating systems. Contains notch-level detail, PD implications, investment grade boundaries, and display attributes. Supports both agency scales (S&P, Moody's, Fitch) and internal rating masterscales.", "Basel II/III IRB requires mapped internal rating scales; supports regulatory PD calibration and external-to-internal rating reconciliation.", "Dimension", "rating_scale_id", "rating_grade_id -> rating_grade_dim"),
    ("crm_type_dim", "Credit risk mitigation type classification", "Classifies CRM instruments by type (funded collateral, unfunded guarantees, credit derivatives, insurance) with Basel recognition method and eligibility indicators. Drives CRM treatment selection in capital calculations.", "Basel III CRM framework (CRE 22); determines SA vs IRB treatment method for each CRM type; supports collateral substitution and double-default recognition.", "Dimension", "crm_type_code", "risk_mitigant_subtype_code -> risk_mitigant_type_dim"),
    ("source_system_registry", "Source system metadata registry", "Catalogs all upstream data source systems feeding the credit risk data warehouse. Records system owner, data domain, ingestion frequency, and active status. Supports data lineage traceability and reconciliation back to authoritative sources.", "Supports BCBS 239 (RDARR) requirements for data lineage, provenance, and source system documentation.", "Reference", "source_system_id", "None (root reference)"),
    ("date_dim", "Calendar date dimension", "Comprehensive date dimension supporting fiscal and calendar year hierarchies, business day flags, and period-end indicators. Enables consistent time-based aggregation, regulatory period alignment, and holiday-adjusted processing.", "Supports regulatory reporting calendar alignment (quarter-end, year-end reporting); CCAR/DFAST stress testing time horizons.", "Dimension", "date_id", "None (root dimension)"),
    ("date_time_dim", "Timestamp dimension with timezone", "Extends the date dimension with intraday timestamp granularity including hour, minute, second, and timezone. Supports real-time limit monitoring and event timestamping.", "Supports real-time limit monitoring requirements; SCCL intraday exposure tracking.", "Dimension", "date_time_id", "date_id -> date_dim"),
    ("regulatory_capital_basis_dim", "Regulatory capital approach definition", "Defines regulatory capital calculation approaches (Standardized Approach, Foundation IRB, Advanced IRB) by jurisdiction and effective date range. Determines which capital rules apply to exposure segments.", "Basel III/IV capital framework selection; determines RWA calculation methodology for each exposure class and jurisdiction.", "Dimension", "regulatory_capital_basis_id", "jurisdiction_code -> regulatory_jurisdiction"),
    ("industry_dim", "Hierarchical industry classification", "Multi-level industry taxonomy supporting NAICS, SIC, and GICS classification standards. Enables portfolio concentration analysis by industry sector with parent-child hierarchy for drill-down.", "Supports industry concentration monitoring per OCC guidance; FR Y-14 industry segmentation; CCAR sector-level stress testing.", "Dimension", "industry_id", "parent_industry_id -> industry_dim (self-referencing)"),
    ("enterprise_business_taxonomy", "Line of Business (LoB) hierarchy", "Enterprise-wide business segment hierarchy defining lines of business, sub-segments, and managed segment structures. Drives P&L attribution, exposure allocation, and organizational reporting alignment.", "Supports LoB-level capital allocation per Basel III Pillar 2; management reporting alignment with legal entity regulatory reporting.", "Hierarchy", "managed_segment_id", "parent_segment_id -> enterprise_business_taxonomy (self-referencing)"),
    ("enterprise_product_taxonomy", "Product hierarchy classification", "Enterprise product catalog organized in a hierarchical tree structure. Maps products to FR 2590 categories and supports product-level exposure segmentation, pricing analysis, and regulatory classification.", "FR 2590 product mapping; Call Report product classification; supports product-level Basel exposure class assignment.", "Hierarchy", "product_node_id", "parent_node_id -> enterprise_product_taxonomy (self-referencing); fr2590_category_code -> fr2590_category_dim"),
    ("portfolio_dim", "Portfolio definition and grouping", "Defines credit portfolios with hierarchical parent-child relationships and LoB segment linkage. Supports portfolio-level risk aggregation, limit assignment, and performance monitoring.", "Supports portfolio-level capital allocation; Basel III IRB portfolio segmentation requirements.", "Dimension", "portfolio_id", "parent_portfolio_id -> portfolio_dim (self-referencing); lob_segment_id -> enterprise_business_taxonomy"),
    ("org_unit_dim", "Organizational unit hierarchy", "Enterprise organizational structure defining departments, desks, and business units with reporting hierarchy. Links to cost centers and LoB segments for management reporting and accountability assignment.", "Supports operational risk management organizational mapping; three lines of defense (3LoD) accountability structure.", "Dimension", "org_unit_id", "parent_org_unit_id -> org_unit_dim (self-referencing); lob_segment_id -> enterprise_business_taxonomy; source_system_id -> source_system_registry"),
    ("rating_source", "Rating agency and source registry", "Catalogs internal and external rating providers (S&P, Moody's, Fitch, internal models) with priority ranking and vendor codes. Determines rating precedence when multiple ratings exist for a counterparty.", "Basel III external rating recognition (CRE 21); ECAI recognition and rating precedence rules for Standardized Approach.", "Reference", "rating_source_id", "None (root reference)"),
    ("rating_grade_dim", "Individual rating grade definition", "Defines individual rating grades within each rating scale with associated PD estimates, LGD downturn values, default flags, and effective date ranges. Supports rating-to-PD mapping and historical grade tracking.", "Basel II/III IRB PD calibration; supports annual PD backtesting requirements and through-the-cycle vs point-in-time rating assessment.", "Dimension", "rating_grade_id", "rating_scale_id -> rating_scale_dim"),
    ("collateral_type", "Collateral type classification", "Master classification of collateral types (real estate, securities, cash, receivables, equipment) with Basel RWA weights, HQLA levels, CRM eligibility flags, standard haircuts, and holding period requirements.", "Basel III CRM eligible collateral types (CRE 22); LCR HQLA classification; supervisory haircut schedules.", "Dimension", "collateral_type_id", "risk_mitigant_subtype_code -> risk_mitigant_type_dim"),
    ("interest_rate_index_dim", "Interest rate index reference", "Catalogs benchmark interest rate indices (SOFR, EURIBOR, SONIA, legacy LIBOR) with tenor codes, day count conventions, compounding methods, and IBOR transition attributes (fallback rates, cessation dates, fallback spreads).", "Supports IBOR transition compliance monitoring; SR 21-7 guidance on LIBOR transition; benchmark reform regulatory requirements.", "Dimension", "rate_index_id", "currency_code -> currency_dim; fallback_to_index_id -> interest_rate_index_dim (self-referencing)"),
    ("ledger_account_dim", "General ledger account dimension", "Maps credit risk exposures to general ledger accounts for accounting integration. Supports account categorization, reconciliation flagging, and regulatory report code alignment.", "Supports Call Report schedule reconciliation to GL; FR Y-9C cross-validation between risk and finance data.", "Dimension", "ledger_account_id", "currency_code -> currency_dim; legal_entity_id -> legal_entity; parent_account_id -> ledger_account_dim (self-referencing); lob_segment_id -> enterprise_business_taxonomy; source_system_id -> source_system_registry"),
    ("context_dim", "Generic context attribute dimension", "Provides flexible context tagging for financial metric observations. Supports domain-specific context labeling (e.g., reporting period, scenario context, methodology) without requiring schema changes.", "Supports flexible regulatory reporting context attributes; enables scenario-tagged metric observations for CCAR/DFAST.", "Dimension", "context_id", "None (root dimension)"),
    ("metric_definition_dim", "Metric definition reference", "Catalogs all business metrics with calculation rule references, periodicities, units of measure, and domain classifications. Serves as the canonical registry for KPIs, risk metrics, and financial indicators.", "Supports BCBS 239 data dictionary requirements; provides metric lineage for regulatory examination documentation.", "Dimension", "metric_definition_id", "calculation_rule_id -> rule_registry; source_system_id -> source_system_registry"),
    ("counterparty", "Obligor and counterparty master (SCD Type 2)", "Core counterparty master record with legal name, entity type, domicile country, industry classification, and both internal and external credit ratings. Implements SCD Type 2 for historical tracking of counterparty attribute changes. Carries Basel asset class, regulatory counterparty type, and affiliated/insider flags.", "Basel III counterparty classification; FR 2590 counterparty type mapping; Y-14 obligor type; SCCL affiliated counterparty identification; Call Report counterparty categorization.", "Master", "counterparty_id", "country_code -> country_dim; entity_type_code -> entity_type_dim; industry_id -> industry_dim"),
    ("legal_entity", "Internal legal entity master (SCD Type 2)", "Master record for the institution's internal legal entities. Contains regulatory identifiers (LEI, RSSD), reporting entity flags, functional currency, and primary regulator. Implements SCD Type 2 for historical entity attribute tracking.", "Required for multi-entity GSIB consolidated and solo reporting; supports FR Y-9C, FR Y-14, and Call Report entity identification; RSSD mapping for Federal Reserve submissions.", "Master", "legal_entity_id", "country_code -> country_dim"),
    ("instrument_master", "Financial instrument master (SCD Type 2)", "Master record for financial instruments (bonds, loans, derivatives, structured products). Contains instrument type, issuer, currency, maturity, coupon details, and seniority. Implements SCD Type 2 for lifecycle tracking.", "Basel III instrument classification for trading/banking book assignment; supports SA-CCR and IMM derivative instrument identification.", "Master", "instrument_id", "country_code -> country_dim; currency_code -> currency_dim"),
    ("instrument_identifier", "Instrument cross-reference identifiers", "Maps instruments to external identifiers (CUSIP, ISIN, SEDOL, internal IDs) across source systems and effective date ranges. Supports instrument deduplication and cross-system reconciliation.", "Supports BCBS 239 data aggregation; enables cross-system instrument reconciliation for accurate exposure aggregation.", "Reference", "instrument_id + id_type + effective_start_date (composite)", "instrument_id -> instrument_master; source_system_id -> source_system_registry"),
    ("credit_agreement_master", "Credit agreement master (SCD Type 2)", "Master record for credit agreements between the institution (lender) and borrowers (counterparties). Contains agreement type, origination date, maturity date, currency, and status. Each agreement may contain multiple facilities.", "Supports FR Y-14 credit agreement identification; provides the contractual foundation for facility-level exposure tracking.", "Master", "credit_agreement_id", "borrower_counterparty_id -> counterparty; lender_legal_entity_id -> legal_entity; currency_code -> currency_dim"),
    ("facility_master", "Credit facility master (SCD Type 2)", "Core credit facility master containing facility type, status, committed amount, origination/maturity dates, and linkages to counterparty, portfolio, LoB, product, rate index, and ledger account. Central to exposure measurement and credit risk aggregation.", "Central to all regulatory exposure calculations; Basel III EAD computation; FR 2590, FR Y-14, and Call Report facility-level data requirements.", "Master", "facility_id", "credit_agreement_id -> credit_agreement_master; counterparty_id -> counterparty; currency_code -> currency_dim; portfolio_id -> portfolio_dim; lob_segment_id -> enterprise_business_taxonomy; product_node_id -> enterprise_product_taxonomy; rate_index_id -> interest_rate_index_dim; ledger_account_id -> ledger_account_dim"),
    ("contract_master", "Generic contract master (SCD Type 2)", "Flexible contract entity linking counterparties, facilities, instruments, legal entities, and netting sets. Supports multi-product contract structures and cross-product relationship mapping.", "Supports holistic counterparty exposure aggregation across product types; Basel III total exposure computation.", "Master", "contract_id", "counterparty_id -> counterparty; facility_id -> facility_master; instrument_id -> instrument_master; legal_entity_id -> legal_entity"),
    ("netting_agreement", "Master netting agreement (SCD Type 2)", "Records ISDA Master Agreements and similar netting arrangements between the institution and counterparties. Contains enforceability assessment, governing law, margin parameters, and threshold amounts.", "Basel III netting recognition requirements (CRE 53); SA-CCR netting set grouping; IMM netting benefit computation.", "Master", "netting_agreement_id", "counterparty_id -> counterparty"),
    ("netting_set", "Netting set definition (SCD Type 2)", "Defines netting sets under master netting agreements. Groups transactions subject to close-out netting for exposure computation. Contains enforceability flags and master agreement references.", "Basel III SA-CCR and IMM netting set identification; drives replacement cost and PFE aggregation at the netting set level.", "Master", "netting_set_id", "netting_agreement_id -> netting_agreement"),
    ("netting_set_link", "Netting set to facility linkage (SCD Type 2)", "Associates individual facilities/transactions with netting sets. Enables correct grouping of derivative and SFT positions for netting benefit computation.", "Required for accurate SA-CCR netting set composition; ensures correct netting benefit calculation under Basel III.", "Link", "netting_set_link_id", "netting_set_id -> netting_set; facility_id -> facility_master"),
    ("csa_master", "Credit Support Annex master (SCD Type 2)", "Records Credit Support Annexes (CSAs) governing collateral exchange between counterparties. Contains margin frequency, minimum transfer amounts, thresholds, eligible collateral descriptions, and governing law.", "Basel III margin requirements for non-centrally cleared derivatives; SA-CCR margin period of risk calibration; supports UMR compliance.", "Master", "csa_id", "counterparty_id -> counterparty"),
    ("margin_agreement", "Initial and variation margin agreement (SCD Type 2)", "Records initial margin (IM) and variation margin (VM) amounts under each counterparty relationship. Links to CSAs and netting sets for comprehensive margin coverage tracking.", "Supports UMR (Uncleared Margin Rules) compliance; Basel III SA-CCR MPOR adjustment based on margin agreement terms.", "Master", "margin_agreement_id", "counterparty_id -> counterparty"),
    ("collateral_asset_master", "Collateral asset master (SCD Type 2)", "Individual collateral asset records with type classification, pledgor counterparty, custodian legal entity, location, valuation currency, insurance status, lien priority, and regulatory eligibility flags.", "Basel III CRM collateral recognition; supports collateral valuation frequency requirements under CRE 22; real estate collateral appraisal requirements.", "Master", "collateral_asset_id", "collateral_type_id -> collateral_type; counterparty_id -> counterparty; country_code -> country_dim; currency_code -> currency_dim; legal_entity_id -> legal_entity"),
    ("collateral_link", "Collateral asset to facility linkage (SCD Type 2)", "Links collateral assets to secured facilities or other anchor entities. Records pledged amounts, currencies, and source system provenance. Supports one-to-many collateral allocation scenarios.", "Basel III CRM allocation methodology; supports LGD estimation for secured exposures under IRB.", "Link", "collateral_link_id", "collateral_asset_id -> collateral_asset_master; source_system_id -> source_system_registry"),
    ("collateral_eligibility_dim", "Regulatory collateral eligibility rules", "Defines regulatory eligibility criteria for collateral types by jurisdiction and capital basis. Determines whether a collateral type qualifies for CRM recognition under the applicable regulatory framework.", "Basel III CRM eligible collateral recognition by jurisdiction; determines which collateral types reduce RWA under SA and IRB.", "Reference", "collateral_eligibility_id", "collateral_type_id -> collateral_type; jurisdiction_code -> regulatory_jurisdiction; regulatory_capital_basis_id -> regulatory_capital_basis_dim"),
    ("collateral_haircut_dim", "Basel supervisory haircut schedules", "Defines regulatory haircuts by collateral type, maturity bucket, jurisdiction, and capital basis. Includes both standard supervisory haircuts and volatility adjustments per the Basel comprehensive approach.", "Basel III supervisory haircut schedules (CRE 22.50-22.72); supports both supervisory and own-estimate haircut approaches.", "Reference", "collateral_haircut_id", "collateral_type_id -> collateral_type; jurisdiction_code -> regulatory_jurisdiction; maturity_bucket_id -> maturity_bucket_dim; regulatory_capital_basis_id -> regulatory_capital_basis_dim"),
    ("crm_eligibility_dim", "CRM instrument eligibility by jurisdiction", "Defines eligibility conditions for credit risk mitigation instruments (guarantees, credit derivatives, insurance) by jurisdiction, CRM type, and capital basis.", "Basel III CRM eligibility requirements for unfunded protection (CRE 22); determines guarantee and credit derivative recognition rules.", "Reference", "crm_eligibility_id", "crm_type_code -> crm_type_dim; jurisdiction_code -> regulatory_jurisdiction; regulatory_capital_basis_id -> regulatory_capital_basis_dim; source_system_id -> source_system_registry"),
    ("crm_protection_master", "CRM protection contract master (SCD Type 2)", "Master record for credit risk mitigation protection contracts (guarantees, insurance policies, credit derivatives). Contains notional amount, maturity, enforceability assessment, coverage percentage, and protection provider.", "Basel III unfunded CRM recognition; supports guarantee substitution approach and double-default framework under IRB.", "Master", "protection_id", "crm_type_code -> crm_type_dim; beneficiary_legal_entity_id -> legal_entity; currency_code -> currency_dim"),
    ("protection_link", "Protection to facility allocation (SCD Type 2)", "Allocates CRM protection contracts to specific facilities with allocated amounts, percentages, and currencies. Enables precise CRM benefit attribution at the facility level.", "Basel III CRM allocation to individual exposures; supports proportional CRM recognition in EAD and RWA calculations.", "Link", "protection_link_id", "protection_id -> crm_protection_master; facility_id -> facility_master"),
    ("risk_mitigant_type_dim", "Risk mitigant subtype classification", "Classifies risk mitigants into subtypes (cash, government securities, corporate bonds, real estate, receivables) within parent group categories. Supports granular CRM type analysis.", "Supports granular Basel III collateral type classification; maps to supervisory haircut categories.", "Dimension", "risk_mitigant_subtype_code", "None (root dimension)"),
    ("risk_mitigant_master", "Individual risk mitigant master (SCD Type 2)", "Tracks individual risk mitigants linking counterparty, collateral asset, and/or protection records. Provides a unified view of all CRM instruments regardless of funded/unfunded status.", "Supports holistic CRM inventory for Basel III capital calculations; enables total CRM coverage assessment per counterparty.", "Master", "risk_mitigant_id", "counterparty_id -> counterparty; risk_mitigant_subtype_code -> risk_mitigant_type_dim"),
    ("risk_mitigant_link", "Risk mitigant to facility linkage (SCD Type 2)", "Links risk mitigants to secured facilities. Complements collateral_link and protection_link with a unified mitigant-to-facility mapping.", "Supports complete CRM allocation chain for Basel III capital calculations.", "Link", "risk_mitigant_link_id", "risk_mitigant_id -> risk_mitigant_master; facility_id -> facility_master"),
    ("collateral_portfolio", "Collateral portfolio grouping", "Groups collateral assets into portfolios aligned with credit portfolios and LoB segments. Supports portfolio-level collateral valuation and coverage analysis.", "Supports portfolio-level collateral adequacy monitoring; enables CRM coverage ratio reporting.", "Reference", "collateral_portfolio_id", "portfolio_id -> portfolio_dim; lob_segment_id -> enterprise_business_taxonomy"),
    ("counterparty_hierarchy", "Counterparty parent-child hierarchy (temporal)", "Time-variant counterparty ownership hierarchy linking each counterparty to its immediate and ultimate parent entities with ownership percentages. Enables consolidated group-level exposure aggregation.", "Basel III group-level exposure aggregation; SCCL connected counterparty identification; supports FR 2590 top borrower group consolidation.", "Hierarchy", "counterparty_id + as_of_date (composite)", "counterparty_id -> counterparty; immediate_parent_id -> counterparty; ultimate_parent_id -> counterparty"),
    ("legal_entity_hierarchy", "Legal entity consolidation hierarchy (SCD Type 2)", "Defines the institution's legal entity consolidation structure with parent-child relationships, ownership percentages, hierarchy paths, and consolidation methods. Supports regulatory and accounting consolidation.", "Required for multi-entity GSIB consolidated regulatory reporting; determines legal entity scope for FR Y-9C, FR Y-14, and other consolidated filings.", "Hierarchy", "hierarchy_id", "legal_entity_id -> legal_entity; parent_legal_entity_id -> legal_entity"),
    ("control_relationship", "Parent-subsidiary control relationship (SCD Type 2)", "Records ownership and control relationships between counterparties including controlling/controlled entity identification and ownership percentages. Supports group structure analysis for credit risk assessment.", "SCCL counterparty group identification; Basel III control relationship assessment for connected borrower grouping.", "Relationship", "control_relationship_id", "parent_counterparty_id -> counterparty; subsidiary_counterparty_id -> counterparty"),
    ("economic_interdependence_relationship", "Economic interdependence linkage (SCD Type 2)", "Identifies economically interdependent counterparties that may experience correlated default risk. Records interdependence type, strength score, and rationale for grouping.", "SCCL (12 CFR 252.71) economic interdependence assessment; supports connected counterparty grouping for large exposure limits.", "Relationship", "econ_interdep_relationship_id", "counterparty_id_1 -> counterparty; counterparty_id_2 -> counterparty; source_system_id -> source_system_registry"),
    ("credit_agreement_counterparty_participation", "Agreement-level counterparty participation (SCD Type 2)", "Records counterparty participation in credit agreements by role (borrower, guarantor, co-borrower). Supports multi-obligor agreement structures with participation percentages and priority ranking.", "Supports Basel III multi-obligor exposure attribution; FR Y-14 agreement-level participant identification.", "Link", "agreement_participation_id", "credit_agreement_id -> credit_agreement_master; counterparty_id -> counterparty; counterparty_role_code -> counterparty_role_dim"),
    ("facility_counterparty_participation", "Facility-level counterparty participation (SCD Type 2)", "Records counterparty roles at the facility level including borrower, guarantor, and co-borrower designations. Supports multi-party facility structures and risk-bearing role identification.", "Supports facility-level exposure attribution for Basel III; enables guarantor substitution under CRM framework.", "Link", "facility_participation_id", "facility_id -> facility_master; counterparty_id -> counterparty; counterparty_role_code -> counterparty_role_dim"),
    ("facility_lender_allocation", "Syndication lender allocation (SCD Type 2)", "Records the institution's share in syndicated facilities including bank share percentage, committed amount, allocation role, and lead arranger flag. Supports pro-rata exposure computation for participated loans.", "Basel III syndicated loan exposure attribution; supports FR Y-14 syndicated loan reporting requirements.", "Link", "lender_allocation_id", "facility_id -> facility_master; legal_entity_id -> legal_entity"),
    ("sccl_counterparty_group", "SCCL counterparty group definition", "Defines Single Counterparty Credit Limit (SCCL) groups for large exposure monitoring. Groups connected counterparties based on ownership, control, or economic interdependence relationships.", "12 CFR 252 Subpart H (SCCL); required for GSIB large exposure limit monitoring and FR 2590 reporting.", "Reference", "sccl_group_id", "jurisdiction_code -> regulatory_jurisdiction"),
    ("sccl_counterparty_group_member", "SCCL group membership", "Records individual counterparty membership in SCCL groups with ownership percentages, roles, and effective date ranges. Supports dynamic group composition updates.", "12 CFR 252 SCCL group composition; determines which counterparties are included in large exposure limit calculations.", "Link", "member_id", "sccl_group_id -> sccl_counterparty_group; counterparty_id -> counterparty"),
    ("limit_rule", "Credit limit rule definition", "Defines credit limit rules with limit amounts, scope (counterparty, portfolio, LoB), type, risk tier classification, and inner/outer threshold percentages for early warning triggers.", "Supports regulatory credit concentration limit requirements; OCC and Fed guidance on single-name concentration limits.", "Reference", "limit_rule_id", "counterparty_id -> counterparty; lob_segment_id -> enterprise_business_taxonomy"),
    ("limit_threshold", "Credit limit threshold configuration", "Configures threshold levels for credit limits including inner (early warning) and outer (breach) thresholds with escalation actions. Supports multi-tier limit monitoring frameworks.", "Supports three-tier limit monitoring frameworks per OCC guidance; enables graduated escalation for limit utilization.", "Reference", "limit_threshold_id", "limit_rule_id -> limit_rule"),
    ("fx_rate", "Foreign exchange rate time series", "Daily FX rate observations for currency pair conversion. Supports as-of-date rate lookup for multi-currency exposure translation to base currency.", "Required for Basel III multi-currency exposure aggregation; supports FR 2590 USD-equivalent exposure computation.", "Reference", "fx_rate_id", "from_currency_code -> currency_dim; to_currency_code -> currency_dim"),
    ("run_control", "ETL run control metadata", "Tracks data processing runs with as-of-date, run version, status, cutoff timestamp, and certification metadata. Provides the execution context for all L2 snapshots and L3 reporting outputs.", "Supports BCBS 239 data timeliness and accuracy requirements; provides audit trail for regulatory report production runs.", "Reference", "run_control_id", "source_system_id -> source_system_registry"),
    ("report_registry", "Regulatory report definition registry", "Catalogs regulatory reports (FR 2590, FR Y-9C, FR Y-14, Call Report) with filing frequency, jurisdiction, and regulator identification. Serves as the master reference for all regulatory filing obligations.", "Central registry for all regulatory reporting obligations; supports multi-jurisdictional GSIB regulatory compliance tracking.", "Reference", "report_id", "jurisdiction_code -> regulatory_jurisdiction"),
    ("reporting_calendar_dim", "Regulatory reporting calendar", "Defines regulatory reporting periods with period start/end dates, fiscal year/quarter alignment, and filing cutoff timestamps. Ensures timely and consistent regulatory report production.", "Ensures compliance with regulatory filing deadlines; supports automated report scheduling and deadline tracking.", "Reference", "reporting_calendar_id", "None"),
    ("reporting_entity_dim", "Reporting entity definition", "Maps internal legal entities to regulatory reporting entities with consolidation basis, functional currency, and jurisdiction-specific reporting entity codes. Supports multi-entity regulatory filings.", "Determines scope of consolidated vs solo regulatory filings; maps legal entities to RSSD IDs for Federal Reserve submissions.", "Reference", "reporting_entity_id", "legal_entity_id -> legal_entity"),
    ("model_registry_dim", "Risk model registry", "Catalogs risk models (PD, LGD, EAD, DSCR, credit scoring) with model type, version, validation status, regulatory approval flags, and documentation URLs. Supports model risk management and regulatory model inventory.", "Supports SR 11-7 model risk management requirements; tracks regulatory approval status for IRB models; provides model inventory for examination.", "Reference", "model_id", "owner_org_unit_id -> org_unit_dim"),
    ("rule_registry", "Calculation rule registry", "Defines calculation rules and formulas used in regulatory capital computation, report cell calculation, and metric derivation. Contains rule expressions, input/output variables, and approval metadata.", "Supports auditability of regulatory capital calculations; provides transparent calculation logic for examiner review.", "Reference", "rule_id", "None (root reference)"),
    ("validation_check_registry", "Data validation check registry", "Catalogs data quality and validation checks with check type (completeness, accuracy, consistency), target table/column, severity levels, and owner assignment. Supports systematic DQ monitoring.", "Supports BCBS 239 data accuracy requirements; enables systematic data quality governance and exception tracking.", "Reference", "check_id", "check_rule_id -> rule_registry"),
    ("reconciliation_control", "Reconciliation control framework", "Records reconciliation checks between source systems, risk calculations, and regulatory reports. Tracks expected vs actual values, tolerances, variance analysis, and remediation status.", "Supports regulatory reconciliation requirements; ensures consistency between risk data, accounting data, and regulatory report submissions.", "Reference", "reconciliation_control_id", "source_system_id -> source_system_registry"),
    ("regulatory_mapping", "MDRM regulatory mapping reference", "Maps internal data elements to regulatory report line items (MDRM codes), schedules, and calculation rules. Supports automated regulatory report population from internal data sources.", "Directly enables automated FR 2590, FR Y-9C, and Call Report population; MDRM mapping ensures accurate regulatory data submission.", "Reference", "regulatory_mapping_id", "jurisdiction_code -> regulatory_jurisdiction"),
    ("report_cell_definition", "Regulatory report cell definition", "Defines individual cells within regulatory reports with cell codes, names, data types, calculation rules, and schedule/line-item positioning. Enables granular report cell population and validation.", "Defines the atomic reporting units for regulatory filings; supports cell-level audit trail and validation per filing instructions.", "Reference", "report_cell_id", "report_id -> report_registry"),
    ("rating_mapping", "External-to-internal rating mapping", "Maps external agency ratings to internal rating grades with mapping methods, model references, and approval metadata. Supports consistent rating translation across the portfolio.", "Basel III external rating use for SA; supports ECAI-to-internal-scale mapping required for IRB calibration.", "Reference", "rating_mapping_id", "rating_scale_id -> rating_scale_dim; rating_source_id -> rating_source; internal_grade_id -> rating_grade_dim"),
    ("scenario_dim", "Stress test scenario definition", "Defines stress test and multi-scenario analysis scenarios with type, horizon, shock parameters, and regulatory scenario codes. Supports both internal and regulatory-prescribed stress scenarios.", "CCAR/DFAST scenario specification; supports internal stress testing frameworks per SR 12-7; Basel III Pillar 2 scenario analysis.", "Dimension", "scenario_id", "source_system_id -> source_system_registry"),
]

# ── L2 table definitions ─────────────────────────────────────────────────────
L2_TABLES = [
    ("position", "Core position record (point-in-time)", "Captures daily position snapshots linking facilities, instruments, counterparties, and legal entities. Records balance amounts, market values, PD/LGD estimates, credit status, and trading/banking book assignment. Serves as the atomic grain for exposure measurement.", "Basel III position-level EAD computation; SA-CCR replacement cost; FR 2590 position-level data; FR Y-14 schedule H.", "Snapshot", "position_id", "facility_id -> L1.facility_master; instrument_id -> L1.instrument_master; currency_code -> L1.currency_dim; source_system_id -> L1.source_system_registry"),
    ("position_detail", "Extended position attributes", "Provides granular position attributes including CCF, haircuts, funded/unfunded splits, derivatives mark-to-market, PFE, delinquency details, overdue aging buckets, and rate/spread information. Supplements the core position with risk-calculation-ready data.", "Supports Basel III CCF application for off-balance-sheet items; SA-CCR add-on calculations; delinquency bucket mapping for NPL classification.", "Snapshot", "position_detail_id", "position_id -> L2.position"),
    ("exposure_counterparty_attribution", "Counterparty-level exposure attribution", "Attributes exposure amounts to counterparties with role-based allocation and risk-shifting identification. Supports multi-obligor exposure scenarios where exposure may shift from borrower to guarantor.", "Supports Basel III CRM substitution approach; enables counterparty-level exposure aggregation for SCCL calculations.", "Snapshot", "attribution_id + as_of_date (composite)", "exposure_type_id -> L1.exposure_type_dim; counterparty_id -> L1.counterparty; currency_code -> L1.currency_dim"),
    ("facility_exposure_snapshot", "Facility-level exposure snapshot", "Daily facility exposure snapshots capturing drawn/undrawn amounts, committed exposure, coverage ratios, utilization status, and RWA. Includes FR 2590 category mapping and internal risk rating bucket assignment.", "Direct feed to Basel III facility-level EAD; FR 2590 facility-level large exposure data; Call Report schedule RC-C.", "Snapshot", "facility_id + as_of_date (composite)", "facility_id -> L1.facility_master; exposure_type_id -> L1.exposure_type_dim; source_system_id -> L1.source_system_registry"),
    ("netting_set_exposure_snapshot", "Netting set exposure snapshot", "Point-in-time netting set exposures capturing gross/netted MTM, PFE, collateral held, and netting benefit amounts. Used for derivative and SFT counterparty credit risk measurement.", "Basel III SA-CCR netting set level EAD; supports CEM/SA-CCR replacement cost and PFE computation.", "Snapshot", "netting_set_id + as_of_date (composite)", "netting_set_id -> L1.netting_set; currency_code -> L1.currency_dim"),
    ("facility_lob_attribution", "Facility LoB revenue/exposure attribution", "Allocates facility exposures, revenues, and profits across lines of business when a facility spans multiple LoB segments. Supports matrix-based LoB reporting with flexible allocation percentages.", "Supports LoB-level capital allocation per Basel III Pillar 2; enables accurate LoB P&L attribution for management reporting.", "Snapshot", "attribution_id", "facility_id -> L1.facility_master; lob_segment_id -> L1.enterprise_business_taxonomy"),
    ("collateral_snapshot", "Collateral valuation snapshot", "Point-in-time collateral asset valuations with market value, regulatory haircuts, recognized amounts, and CRM type mapping. Supports collateral adequacy monitoring and CRM benefit computation.", "Basel III CRM valuation; supports collateral revaluation frequency requirements under CRE 22; LGD collateral coverage.", "Snapshot", "collateral_asset_id + as_of_date (composite)", "collateral_asset_id -> L1.collateral_asset_master; source_system_id -> L1.source_system_registry"),
    ("cash_flow", "Cash flow projection records", "Records projected and actual cash flows at the facility level with flow type, direction, amount, maturity bucket, and counterparty attribution. Supports liquidity modeling and maturity analysis.", "Supports LCR/NSFR cash flow bucketing; ALM gap analysis; contractual maturity profiling for regulatory reporting.", "Event", "cash_flow_id", "facility_id -> L1.facility_master; currency_code -> L1.currency_dim"),
    ("facility_financial_snapshot", "Facility financial metric snapshot", "Captures facility-level financial metrics including NOI, DSCR, LTV, EBITDA, debt service, and interest rate sensitivity. Supports underwriting quality monitoring and covenant compliance tracking.", "Supports FR Y-14Q schedule H financial data requirements; CRE concentration monitoring per SR 07-1; covenant compliance assessment.", "Snapshot", "facility_id + as_of_date (composite)", "facility_id -> L1.facility_master"),
    ("facility_delinquency_snapshot", "Facility delinquency and past-due snapshot", "Tracks facility delinquency status including days past due, overdue amounts by aging bucket (0-30, 31-60, 61-90+), watch list flags, and payment history. Supports early warning identification and NPL classification.", "Supports Call Report past-due and nonaccrual classification; Basel III default recognition based on days past due thresholds.", "Snapshot", "facility_id + as_of_date (composite)", "facility_id -> L1.facility_master; credit_status_code -> L1.credit_status_dim"),
    ("facility_pricing_snapshot", "Facility pricing and rate snapshot", "Records facility pricing metrics including spread, base rate, all-in rate, rate cap/floor, payment frequency, and pricing tier assignment. Supports pricing exception identification and NIM analysis.", "Supports FR Y-14 pricing data; enables spread-to-threshold analysis for pricing governance; NIM contribution analysis.", "Snapshot", "facility_id + as_of_date (composite)", "facility_id -> L1.facility_master; rate_index_id -> L1.interest_rate_index_dim"),
    ("facility_profitability_snapshot", "Facility profitability snapshot", "Captures facility-level profitability metrics including interest income/expense, fee income, NII, and allocated equity. Supports ROA/ROE computation at the facility level.", "Supports LoB profitability reporting for Basel III Pillar 2 ICAAP; enables risk-adjusted return analysis.", "Snapshot", "facility_id + as_of_date (composite)", "facility_id -> L1.facility_master; ledger_account_id -> L1.ledger_account_dim"),
    ("limit_contribution_snapshot", "Limit utilization contribution by counterparty", "Records individual counterparty contributions to credit limit utilization at the facility level. Enables limit attribution analysis and concentration driver identification.", "Supports SCCL limit monitoring; enables counterparty-level limit contribution analysis for large exposure management.", "Snapshot", "limit_rule_id + counterparty_id + as_of_date (composite)", "limit_rule_id -> L1.limit_rule; counterparty_id -> L1.counterparty; currency_code -> L1.currency_dim"),
    ("limit_utilization_event", "Limit utilization event tracking", "Records point-in-time limit utilization snapshots with utilized and available amounts. Supports limit monitoring dashboards and utilization trend analysis.", "Supports real-time SCCL limit monitoring; enables intraday limit utilization reporting per 12 CFR 252.", "Event", "limit_rule_id + as_of_date (composite)", "limit_rule_id -> L1.limit_rule; counterparty_id -> L1.counterparty"),
    ("amendment_event", "Facility amendment event record", "Captures facility amendment events with type, status, effective date, description, and counterparty linkage. Tracks the lifecycle of credit terms modifications from identification through completion.", "Supports OCC guidance on facility modification tracking; TDR classification assessment under ASC 310-40.", "Event", "amendment_id", "facility_id -> L1.facility_master; credit_agreement_id -> L1.credit_agreement_master; amendment_type_code -> L1.amendment_type_dim; amendment_status_code -> L1.amendment_status_dim"),
    ("amendment_change_detail", "Amendment change field-level detail", "Records individual field-level changes within each amendment event (old value vs new value). Provides granular audit trail of all terms modified during facility amendments.", "Supports examiner review of facility modification details; TDR concession analysis.", "Event", "change_detail_id", "amendment_id -> L2.amendment_event"),
    ("credit_event", "Credit event occurrence record", "Records credit events (defaults, bankruptcies, restructurings, cross-defaults) with event date, loss amounts, recovery amounts, and status. Links to default definitions and counterparty master.", "Basel III credit event recognition per CRE 44; supports default rate and LGD backtesting; CCAR loss estimation.", "Event", "credit_event_id", "counterparty_id -> L1.counterparty; credit_event_type_code -> L1.credit_event_type_dim; default_definition_id -> L1.default_definition_dim"),
    ("credit_event_facility_link", "Credit event to facility linkage", "Associates credit events with affected facilities including exposure at default and estimated loss amounts. Enables facility-level loss attribution for default events.", "Basel III EAD at default; supports LGD computation per facility; facility-level loss tracking for backtesting.", "Link", "link_id", "credit_event_id -> L2.credit_event; facility_id -> L1.facility_master"),
    ("stress_test_result", "Stress test scenario result", "Records stress test results by scenario and portfolio including loss amounts, P&L impacts, capital impacts, and breach counts. Supports scenario comparison and capital adequacy assessment.", "CCAR/DFAST stress test result documentation; Basel III Pillar 2 ICAAP scenario analysis; supports SR 12-7 stress testing requirements.", "Event", "result_id", "scenario_id -> L1.scenario_dim; portfolio_id -> L1.portfolio_dim"),
    ("stress_test_breach", "Stress test limit breach detail", "Records individual limit breaches under stress scenarios with severity, breach amounts, control owner, and failure descriptions. Supports stress test breach remediation tracking.", "CCAR/DFAST breach identification and remediation; supports Fed stress testing limit breach reporting requirements.", "Event", "breach_id", "scenario_id -> L1.scenario_dim; limit_rule_id -> L1.limit_rule; counterparty_id -> L1.counterparty"),
    ("deal_pipeline_fact", "Deal pipeline and origination tracking", "Tracks credit deals through origination pipeline stages with expected amounts, spreads, coverage ratios, risk grades, and expected close dates. Supports pipeline monitoring and LoB origination analysis.", "Supports FR Y-14 schedule A deal pipeline data; enables forward-looking exposure forecasting for capital planning.", "Event", "pipeline_id", "counterparty_id -> L1.counterparty; currency_code -> L1.currency_dim"),
    ("counterparty_rating_observation", "Counterparty rating observation", "Records point-in-time internal and external rating observations for counterparties with rating value, prior rating, rating agency, and migration step tracking. Supports rating migration analysis and PD calibration.", "Basel III IRB PD estimation; supports annual rating model backtesting; enables upgrade/downgrade migration matrix construction.", "Observation", "observation_id", "counterparty_id -> L1.counterparty; rating_grade_id -> L1.rating_grade_dim; rating_source_id -> L1.rating_source"),
    ("financial_metric_observation", "Obligor/facility financial metric observation", "Records financial metric observations (balance sheet items, income statement data, coverage ratios) for counterparties and facilities. Supports credit analysis, covenant monitoring, and financial trend analysis.", "Supports FR Y-14Q schedule H financial data; enables borrower financial health monitoring per OCC guidance.", "Observation", "observation_id", "counterparty_id -> L1.counterparty; facility_id -> L1.facility_master; metric_definition_id -> L1.metric_definition_dim; context_id -> L1.context_dim"),
    ("metric_threshold", "Metric threshold configuration", "Records threshold configurations for monitored metrics including inner/outer threshold percentages, limit values, metric ownership, and reporting requirements. Supports risk appetite metric monitoring.", "Supports risk appetite framework monitoring; enables automated threshold breach detection and escalation.", "Reference", "threshold_id", "metric_definition_id -> L1.metric_definition_dim"),
    ("exception_event", "Exception and breach event tracking", "Records exception events including limit breaches, covenant violations, and policy exceptions with severity, remediation plans, and resolution tracking. Supports exception management governance.", "Supports OCC exception management requirements; enables systematic tracking of limit breaches and policy exceptions.", "Event", "exception_id", "facility_id -> L1.facility_master; counterparty_id -> L1.counterparty"),
    ("risk_flag", "Risk flag and early warning indicator", "Records risk flags raised against facilities or counterparties with flag type, severity, trigger values, and clearance tracking. Supports early warning system and proactive risk identification.", "Supports OCC early warning system requirements; enables proactive credit risk identification per supervisory guidance.", "Event", "risk_flag_id", "facility_id -> L1.facility_master; counterparty_id -> L1.counterparty"),
    ("data_quality_score_snapshot", "Data quality score observation", "Records data quality scores by dimension (completeness, validity, consistency) with issue counts, reconciliation breaks, and impacted report identification. Supports systematic DQ monitoring and remediation.", "Supports BCBS 239 data quality requirements; enables systematic tracking of data accuracy for regulatory reporting integrity.", "Snapshot", "score_id", "source_system_id -> L1.source_system_registry"),
]

# ── L3 table definitions ─────────────────────────────────────────────────────
L3_TABLES = [
    ("exposure_metric_cube", "Granular multi-dimensional exposure fact table", "Central exposure fact table at the most granular level combining counterparty, facility, instrument, product, country, currency, and scenario dimensions. Stores gross/net exposure, drawn/undrawn, EAD, secured/unsecured residual amounts. Serves as the primary source for all downstream exposure summaries and regulatory reports.", "Basel III EAD computation; FR 2590 position-level exposure data; SCCL counterparty-level exposure aggregation; CCAR exposure-at-risk calculations.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id + legal_entity_id + org_unit_id + portfolio_id + product_node_id + counterparty_id + country_code + currency_code + exposure_type_code", "run_version_id -> L1.run_control; scenario_id -> L1.scenario_dim; legal_entity_id -> L1.legal_entity; counterparty_id -> L1.counterparty; facility_id -> L1.facility_master; country_code -> L1.country_dim; currency_code -> L1.currency_dim"),
    ("risk_metric_cube", "Granular risk metrics fact table (PD, LGD, EAD, RWA)", "Companion risk fact table storing PD, LGD, EAD, expected loss, risk weight, RWA, and capital requirement amounts. Linked to rating grades and risk models for full audit trail of risk parameter sourcing.", "Basel III RWA computation under SA and IRB; supports Pillar 3 disclosure on risk parameters; CCAR capital impact analysis.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id + legal_entity_id + portfolio_id + product_node_id + counterparty_id", "run_version_id -> L1.run_control; scenario_id -> L1.scenario_dim; model_id -> L1.model_registry_dim; rating_grade_id -> L1.rating_grade_dim"),
    ("counterparty_exposure_summary", "Counterparty-level exposure aggregation", "Aggregates exposures at the counterparty level across all facilities, products, and legal entities. Includes SCCL group linkage, cross-entity exposure detection, utilization metrics, risk tier classification, and period-over-period change tracking.", "SCCL counterparty aggregate exposure; FR 2590 top borrower identification; Basel III IRB counterparty-level PD/LGD application.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id + legal_entity_id + counterparty_id", "counterparty_id -> L1.counterparty; sccl_group_id -> L1.sccl_counterparty_group; region_code -> L1.region_dim; industry_code -> L1.industry_dim"),
    ("facility_exposure_summary", "Facility-level exposure and EAD summary", "Facility-level exposure summary with outstanding, undrawn commitment, EAD, secured/unsecured breakdown, syndication flags, and amendment status. Supports facility-level drill-down from portfolio views.", "Basel III facility-level EAD and CRM allocation; FR Y-14 schedule H facility data; Call Report RC-C.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id + legal_entity_id + facility_id", "facility_id -> L1.facility_master; counterparty_id -> L1.counterparty; portfolio_id -> L1.portfolio_dim"),
    ("portfolio_summary", "Portfolio-level exposure, risk, and capital summary", "Aggregates exposure, expected loss, PD, LGD, and RWA metrics at the portfolio level. Provides portfolio-level risk profile for capital adequacy assessment and portfolio management.", "Basel III portfolio-level capital adequacy; supports ICAAP portfolio risk assessment; Pillar 3 portfolio disclosure.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id + legal_entity_id + portfolio_id", "portfolio_id -> L1.portfolio_dim; legal_entity_id -> L1.legal_entity"),
    ("crm_allocation_summary", "CRM allocation and coverage summary", "Summarizes credit risk mitigation allocations including market values, haircuts, recognized amounts, and allocated amounts by CRM type and target level (facility, counterparty, netting set).", "Basel III CRM recognition and allocation (CRE 22); supports LGD estimation for secured exposures under IRB; Pillar 3 CRM disclosure.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + legal_entity_id + crm_type_code + allocation_target_level + crm_id", "crm_type_code -> L1.crm_type_dim; facility_id -> L1.facility_master; risk_mitigant_id -> L1.risk_mitigant_master"),
    ("collateral_portfolio_valuation", "Portfolio-level collateral valuation summary", "Aggregates collateral market and recognized values by portfolio and collateral type with asset counts. Supports portfolio-level collateral adequacy assessment.", "Basel III collateral portfolio coverage; supports Pillar 3 CRM disclosure; OCC collateral adequacy monitoring.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + legal_entity_id + portfolio_id + collateral_type_id", "portfolio_id -> L1.portfolio_dim; collateral_type_id -> L1.collateral_type"),
    ("limit_current_state", "Current limit status and utilization", "Real-time view of credit limit status including limit amount, utilization, available headroom, breach history, velocity metrics (30d/90d), and tier classification. Provides the current-state dashboard for limit monitoring.", "SCCL intraday limit monitoring per 12 CFR 252; supports real-time concentration risk management.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_ts + legal_entity_id + limit_assignment_id", "legal_entity_id -> L1.legal_entity"),
    ("limit_utilization_timeseries", "Historical limit utilization time series", "Time-series tracking of limit utilization enabling trend analysis, velocity computation, and historical limit headroom assessment.", "Supports SCCL limit utilization trend reporting; enables limit headroom forecasting for capital planning.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_ts + legal_entity_id + limit_assignment_id", "legal_entity_id -> L1.legal_entity"),
    ("limit_attribution_summary", "Limit utilization attribution by dimension", "Decomposes limit utilization by contributing dimensions (facility, counterparty, portfolio, product, org unit) with contribution amounts and percentages. Enables identification of key limit drivers.", "Supports SCCL limit driver analysis; enables concentration risk decomposition for examiner review.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_ts + legal_entity_id + limit_assignment_id + contributor_level", "facility_id -> L1.facility_master; counterparty_id -> L1.counterparty; portfolio_id -> L1.portfolio_dim"),
    ("limit_breach_fact", "Limit breach event fact table", "Records limit breach events with severity, breach amount, status, and resolution timestamps. Supports breach tracking, escalation management, and historical breach analysis.", "SCCL breach reporting requirements; supports OCC limit exception management; enables breach frequency and severity analysis.", "Tier 1 (Direct L1+L2)", "breach_id", "limit_assignment_id -> L1.limit_rule; legal_entity_id -> L1.legal_entity"),
    ("credit_event_summary", "Credit event aggregation and summary", "Aggregates credit events by type with event counts, default flags, charge-off and recovery amounts, net loss calculations, and impacted facility counts. Provides the executive view of credit event activity.", "Basel III default and loss reporting; CCAR loss estimation; supports Pillar 3 credit event disclosure.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + legal_entity_id + credit_event_type_id", "credit_event_type_id -> L1.credit_event_type_dim; counterparty_id -> L1.counterparty"),
    ("rating_migration_summary", "Rating migration transition matrix", "Records rating migrations between grades with exposure amounts at time of migration. Supports transition matrix construction and rating system performance monitoring.", "Basel III IRB rating system validation; supports annual PD model backtesting; Pillar 3 rating migration disclosure.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + legal_entity_id + counterparty_id + rating_source_id + from_rating_grade_id + to_rating_grade_id", "from_rating_grade_id -> L1.rating_grade_dim; to_rating_grade_id -> L1.rating_grade_dim; rating_source_id -> L1.rating_source"),
    ("default_loss_recovery_summary", "Default, charge-off, and recovery summary", "Summarizes default events with exposure at default, charge-off amounts, recovery amounts, and realized LGD. Supports loss outcome analysis and LGD model calibration.", "Basel III realized LGD computation for IRB backtesting; CCAR loss estimation; charge-off and recovery reporting.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + legal_entity_id + counterparty_id", "counterparty_id -> L1.counterparty; facility_id -> L1.facility_master"),
    ("report_run", "Regulatory report execution metadata", "Records each regulatory report production run with report code, as-of-date, scenario, status, and timing. Provides audit trail for regulatory filing production.", "Supports BCBS 239 timeliness requirements; provides audit trail for regulatory filing submission.", "Tier 1 (Direct L1+L2)", "report_run_id", "run_version_id -> L1.run_control; report_code -> L1.report_registry; scenario_id -> L1.scenario_dim"),
    ("report_cell_value", "Regulatory report cell values", "Stores computed values for each regulatory report cell with amounts, currency, units, precision, and calculation rule references. Represents the final regulatory report output.", "Contains the actual regulatory filing data for FR 2590, FR Y-9C, Call Report; cell-level audit trail.", "Tier 1 (Direct L1+L2)", "report_run_id + cell_id", "report_run_id -> L3.report_run; cell_id -> L1.report_cell_definition"),
    ("report_cell_contribution_fact", "Cell-level source record contributions", "Details how each source record contributes to regulatory report cell values. Enables cell-level drill-down from report totals to underlying positions and exposures.", "Supports examiner drill-down from regulatory report cells to source records; provides full data lineage per BCBS 239.", "Tier 1 (Direct L1+L2)", "contribution_id", "report_run_id -> L3.report_run; cell_id -> L1.report_cell_definition; rule_id -> L1.rule_registry"),
    ("report_cell_rule_execution", "Rule execution audit for report cells", "Records the execution of calculation rules for each report cell including status, timing, input record counts, output values, and error messages. Supports calculation audit and troubleshooting.", "Provides complete calculation audit trail for regulatory filings; supports examiner review of calculation methodology.", "Tier 1 (Direct L1+L2)", "report_run_id + cell_id + rule_id + rule_version", "report_run_id -> L3.report_run; rule_id -> L1.rule_registry"),
    ("report_validation_result", "Report validation check results", "Records validation check outcomes for regulatory reports including threshold vs observed values, pass/fail status, severity, and error messages. Supports pre-submission quality assurance.", "Supports regulatory filing quality assurance; enables pre-submission validation per filing instructions.", "Tier 1 (Direct L1+L2)", "validation_result_id", "report_run_id -> L3.report_run; validation_check_id -> L1.validation_check_registry"),
    ("fr2590_position_snapshot", "FR 2590 position-level mapping snapshot", "Maps individual positions to FR 2590 schedule/line/column identifiers with MDRM codes and amounts. Provides the position-level building blocks for FR 2590 report assembly.", "Directly supports FR 2590 large exposure report production; maps positions to MDRM codes for regulatory submission.", "Tier 1 (Direct L1+L2)", "report_run_id + position_id", "position_id -> L2.position; counterparty_id -> L1.counterparty; fr2590_category_code -> L1.fr2590_category_dim"),
    ("fr2590_counterparty_aggregate", "FR 2590 counterparty-level aggregate", "Aggregates FR 2590 data at the counterparty level with ranking within legal entity and top-counterparty identification. Supports the top borrower schedule of FR 2590.", "FR 2590 top borrower ranking and aggregate reporting; identifies counterparties exceeding large exposure thresholds.", "Tier 1 (Direct L1+L2)", "report_run_id + counterparty_id + legal_entity_id + as_of_date", "counterparty_id -> L1.counterparty; legal_entity_id -> L1.legal_entity; fr2590_category_code -> L1.fr2590_category_dim"),
    ("lob_exposure_summary", "LoB-level exposure and risk summary", "Comprehensive LoB exposure summary with facility/counterparty counts, gross/net exposure, drawn/undrawn, EAD, expected loss, RWA, utilization, NPL ratios, breach counts, and period-over-period changes. Primary LoB dashboard data source.", "Supports LoB-level capital allocation for Pillar 2; enables management-level risk reporting aligned with regulatory views.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id + scenario_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node; scenario_id -> L1.scenario_dim"),
    ("lob_profitability_summary", "LoB profitability and return metrics", "LoB-level profitability summary with total revenue, net income, NII, average earning assets, allocated equity, NIM, ROA, ROE, and period-over-period change tracking.", "Supports risk-adjusted return analysis for Pillar 2 ICAAP; enables management-level profitability attribution.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_pricing_summary", "LoB pricing analytics summary", "LoB-level pricing metrics with average spread, base rate, all-in rate, spread-to-threshold analysis, below-threshold facility counts, documented exceptions, and period-over-period spread changes.", "Supports pricing governance per OCC guidance; enables spread monitoring for LoB profitability management.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_delinquency_summary", "LoB delinquency and overdue aging summary", "LoB-level delinquency summary with total overdue amounts, delinquent facility/counterparty counts, delinquency rates, aging bucket breakdowns (0-30, 31-60, 61-90+), and period-over-period change tracking.", "Supports Call Report past-due reporting; enables early warning of credit deterioration by LoB.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_profitability_allocation_summary", "LoB profitability by allocation dimension", "Breaks down LoB profitability by allocation dimensions (region, industry, counterparty) with exposure, revenue, net income, ROE, ROA, and NIM per dimension. Supports multi-dimensional profitability analysis.", "Supports Pillar 2 granular profitability analysis; enables geographic and industry concentration risk-return assessment.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id + allocation_dim_type", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("deal_pipeline_stage_summary", "LoB deal pipeline by stage", "Summarizes deal pipeline activity by LoB and pipeline stage with deal counts, expected exposures, collateral values, spreads, and coverage ratios. Supports origination monitoring.", "Supports FR Y-14 pipeline data; enables forward-looking exposure forecasting for capital planning.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id + pipeline_stage_code", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_credit_quality_summary", "LoB credit quality and rating summary", "LoB-level credit quality metrics including average internal risk rating, DSCR values, RWA density, rating downgrade counts (internal/external), criticized portfolio counts, and deterioration index.", "Supports OCC credit quality monitoring; enables LoB-level credit deterioration early warning.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("kpi_period_summary", "KPI period-over-period comparison", "Tracks key performance indicators with current value, prior period value, absolute change, percentage change, and unit of measure. Enables executive-level period-over-period KPI tracking.", "Supports Pillar 2 KPI monitoring; enables board-level risk metric trend reporting.", "Tier 4 (Executive)", "as_of_date + run_version_id", "kpi_code -> L1.metric_definition_dim; scenario_id -> L1.scenario_dim; legal_entity_id -> L1.legal_entity"),
    ("risk_appetite_metric_state", "Risk appetite metric current state", "Tracks risk appetite metrics against defined limits and thresholds with utilization, velocity trends, status classification, ownership, and escalation requirements. Central to enterprise risk appetite monitoring.", "Supports enterprise Risk Appetite Framework (RAF) per SR 15-18; enables automated threshold monitoring and breach escalation.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + metric_id", "metric_id -> L1.metric_definition_dim"),
    ("executive_highlight_summary", "Executive dashboard key highlights", "Pre-computed executive summary highlights with category, narrative text, driver explanation, required actions, severity classification, and source metric linkage. Drives the executive summary dashboard.", "Supports board and senior management reporting per OCC Heightened Standards; enables concise executive risk communication.", "Tier 4 (Executive)", "run_version_id + as_of_date + highlight_seq", "source_metric_id -> L1.metric_definition_dim"),
    ("counterparty_detail_snapshot", "Counterparty detail with exposure and risk", "Comprehensive counterparty-level snapshot combining exposure, risk parameters, limit utilization, facility counts, CRM coverage, and period-over-period changes. Supports counterparty drill-down analytics.", "Supports SCCL counterparty detail reporting; enables examiner review of counterparty risk profiles.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + counterparty_id", "counterparty_id -> L1.counterparty; country_code -> L1.country_dim; region_code -> L1.region_dim; industry_code -> L1.industry_dim"),
    ("limit_tier_status_matrix", "Risk tier vs limit status cross-tabulation", "Cross-tabulates counterparty counts by risk tier and limit status with prior period comparison and risk scores. Enables risk-based limit framework monitoring.", "Supports risk-based concentration monitoring per OCC guidance; enables risk tier migration analysis.", "Tier 2 (Aggregate)", "run_version_id + as_of_date + legal_entity_id + risk_tier_code + limit_status_code", "legal_entity_id -> L1.legal_entity"),
    ("limit_counterparty_movement", "Counterparty movement between risk tiers/limit statuses", "Tracks counterparty migrations between risk tier and limit status combinations with movement type (upgrade/downgrade/new/exit) and exposure amounts. Enables dynamic counterparty risk monitoring.", "Supports SCCL dynamic monitoring; enables proactive identification of counterparty risk tier deterioration.", "Tier 2 (Aggregate)", "run_version_id + as_of_date + legal_entity_id + risk_tier_code + limit_status_code + counterparty_id + movement_type", "counterparty_id -> L1.counterparty; legal_entity_id -> L1.legal_entity"),
    ("data_quality_score_summary", "DQ score summary by dimension", "Aggregates data quality scores by dimension type (source system, data domain, report) with trend analysis and issue categorization. Supports DQ governance dashboard.", "Supports BCBS 239 data quality monitoring; enables DQ trend analysis for regulatory reporting integrity.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + dimension_type + dimension_id", "None (aggregated from L2.data_quality_score_snapshot)"),
    ("legal_entity_risk_profile", "Legal entity risk profile summary", "Summarizes risk profile at the legal entity level including gross/net exposure, cross-entity exposure flags, facility counts, liquidity ratios, utilization, PD/LGD, and expected loss.", "Supports solo and consolidated entity-level regulatory reporting; enables legal entity risk concentration analysis.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + legal_entity_id", "legal_entity_id -> L1.legal_entity"),
    ("data_quality_attribute_score", "DQ score by individual data attribute", "Scores individual data attributes for quality with issue counts, impact assessments, impacted report identification, and rank ordering. Enables targeted DQ remediation prioritization.", "Supports BCBS 239 attribute-level data quality assessment; enables targeted remediation for regulatory reporting accuracy.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + attribute_name", "None (aggregated from L2.data_quality_score_snapshot)"),
    ("data_quality_trend", "Overall DQ trend tracking", "Tracks overall data quality scores, reconciliation break counts, and issue totals over time. Enables long-term DQ trend monitoring and improvement tracking.", "Supports BCBS 239 DQ trend monitoring; demonstrates continuous improvement in data governance to regulators.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date", "legal_entity_id -> L1.legal_entity"),
    ("stress_test_result_summary", "Stress test scenario result summary", "Summarizes stress test outcomes by scenario with total exposure, expected loss, capital impact, breach counts by severity, and last tested date. Supports scenario comparison analysis.", "CCAR/DFAST scenario result documentation; Basel III Pillar 2 stress testing disclosure; SR 12-7 compliance.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id", "scenario_id -> L1.scenario_dim"),
    ("stress_test_breach_detail", "Stress test breach detail with controls", "Detailed breach records under stress scenarios with LoB attribution, severity, control descriptions, control owners, and exception narratives. Supports breach remediation and control assessment.", "CCAR/DFAST breach remediation documentation; supports control effectiveness assessment under stress.", "Tier 1 (Direct L1+L2)", "run_version_id + as_of_date + scenario_id + breach_seq", "scenario_id -> L1.scenario_dim; lob_node_id -> L1.lob_node"),
    ("regulatory_compliance_state", "Regulatory compliance metric status", "Tracks regulatory compliance metrics against regulatory thresholds with variance analysis, compliance status, and prior period comparison. Supports regulatory compliance dashboard.", "Supports regulatory compliance monitoring; enables automated compliance status reporting for CET1, LCR, NSFR, and leverage ratio.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + metric_id", "metric_id -> L1.metric_definition_dim"),
    ("facility_timeline_summary", "Facility maturity timeline analysis", "Aggregates facility maturity and origination timelines by month with facility counts, exposure amounts, and cumulative exposure changes. Supports maturity profile analysis and rollover risk assessment.", "Supports ALM maturity profile analysis; enables rollover risk assessment for capital planning.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + timeline_month + timeline_type", "None (aggregated from L1.facility_master + L2 snapshots)"),
    ("amendment_summary", "Amendment activity summary by type/status", "Aggregates amendment activity by type and status with credit agreement counts and total exposure impact. Supports amendment pipeline monitoring and governance.", "Supports OCC amendment monitoring; enables TDR classification assessment; tracks credit modification activity.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + amendment_type_code + amendment_status_code", "amendment_type_code -> L1.amendment_type_dim; amendment_status_code -> L1.amendment_status_dim"),
    ("amendment_detail", "Individual amendment detail records", "Amendment-level detail with credit agreement, obligor, type, description, original/amended values, start date, status, and aging. Supports amendment drill-down analysis.", "Supports TDR concession analysis; OCC examiner review of individual amendments.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + amendment_event_id", "amendment_event_id -> L2.amendment_event; credit_agreement_id -> L1.credit_agreement_master"),
    ("facility_detail_snapshot", "Comprehensive facility detail snapshot", "Full facility snapshot combining type, purpose, LoB hierarchy, portfolio, product, region, counterparty, exposure, utilization, coverage ratio, terms (maturity, duration), pricing details (rate, spread, index), and amendment history.", "Supports FR Y-14 schedule H facility-level detail; Call Report RC-C; comprehensive facility drill-down.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + facility_id", "facility_id -> L1.facility_master; counterparty_id -> L1.counterparty"),
    ("lob_risk_ratio_summary", "LoB risk ratios and capital adequacy", "LoB-level risk ratios including FCCR (Fixed Charge Coverage Ratio), LCR, capital adequacy ratio, tangible net worth, cash interest expense, and exception rates.", "Supports Pillar 2 LoB-level capital adequacy assessment; enables risk ratio monitoring per OCC guidance.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_deterioration_summary", "LoB credit deterioration tracking", "Tracks LoB-level credit deterioration metrics including deteriorated deal counts/exposure, criticized portfolios, deterioration index, internal/external downgrade counts, and period-over-period deterioration changes.", "Supports OCC credit deterioration monitoring; enables early warning of LoB-level credit quality decline.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_rating_distribution", "LoB internal rating bucket distribution", "Distributes counterparty counts and exposure amounts across internal rating buckets for each LoB. Supports rating distribution analysis and concentration monitoring.", "Supports Pillar 3 rating distribution disclosure; enables LoB-level credit quality composition analysis.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id + rating_bucket_code", "hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("lob_top_contributors", "Top counterparty contributors by LoB", "Ranks top counterparties within each LoB by exposure with utilization and contribution percentages. Supports concentration analysis and name-level risk monitoring.", "Supports single-name concentration monitoring per OCC guidance; enables LoB-level top exposure identification.", "Tier 3 (Reads T1-T2)", "run_version_id + as_of_date + hierarchy_id + lob_node_id + rank_order", "counterparty_id -> L1.counterparty; hierarchy_id -> L1.lob_hierarchy_config; lob_node_id -> L1.lob_node"),
    ("metric_value_fact", "Pre-calculated metric values by aggregation level", "Universal metric consumption table storing pre-calculated metric values at multiple aggregation levels (facility, counterparty, desk, portfolio, LoB). Supports dashboard rendering with variant-level metric specificity.", "Supports enterprise-wide metric consumption across all dashboards and reports; enables consistent metric delivery per BCBS 239.", "Consumption", "run_version_id + as_of_date + metric_id + variant_id + aggregation_level + entity keys (composite unique index)", "metric_id -> metric_library.parent_metrics; variant_id -> metric_library.metric_variants"),
]

# ── Metric Library table definitions ──────────────────────────────────────────
METRIC_LIBRARY_TABLES = [
    ("domains", "Metric domain grouping", "Defines navigational domains for organizing metrics (e.g., Credit Quality, Exposure & Risk, Profitability, Capital Adequacy). Provides icons, colors, regulatory relevance tags, and primary stakeholder identification for dashboard presentation.", "Maps metrics to regulatory domains; supports BCBS 239 data dictionary organization; enables stakeholder-aligned metric views.", "Governance", "domain_id", "None (root reference)"),
    ("parent_metrics", "Canonical metric definition", "Defines canonical business metrics (e.g., DSCR, PD, LTV, NPL Ratio, ROE) with formal definitions, generic formulas, unit types, direction (higher-is-better vs lower-is-better), risk appetite relevance flags, rollup philosophy, and regulatory references. Serves as the authoritative metric dictionary.", "Supports BCBS 239 metric lineage and data dictionary; provides governed metric definitions for regulatory examination; aligns metrics with Basel III/IV risk parameters.", "Governance", "metric_id", "domain_ids -> domains (via JSONB array)"),
    ("metric_variants", "Specific metric implementation variant", "Defines specific implementations of parent metrics with precise formulas, numerator/denominator definitions, product scope filters, edge cases, rollup logic, weighting basis, validation rules, and comprehensive sourcing metadata. Includes calculation authority tier, source system integration details, atomic sourcing level, and governance attributes (owner, approver, review cycle).", "Provides implementation-level metric governance for GSIB regulatory metrics; supports SR 11-7 model documentation for calculated metrics; enables audit trail from reported values to source system fields.", "Governance", "variant_id", "parent_metric_id -> parent_metrics"),
]


def build_workbook():
    wb = openpyxl.Workbook()

    # Remove default sheet
    wb.remove(wb.active)

    layers = [
        ("L1 - Reference & Master", L1_TABLES, "L1"),
        ("L2 - Transactional & Snapshot", L2_TABLES, "L2"),
        ("L3 - Reporting & Analytics", L3_TABLES, "L3"),
        ("Metric Library", METRIC_LIBRARY_TABLES, "Metric Library"),
    ]

    for sheet_name, tables, layer_name in layers:
        ws = wb.create_sheet(title=sheet_name)
        style_header(ws)

        for row_idx, t in enumerate(tables, 2):
            table_name, desc, purpose, regulatory, tier, pk, fk = t
            full_table = f"{layer_name.lower().replace(' ', '_').replace('-','_').replace('metric_library','metric_library')}.{table_name}" if layer_name != "Metric Library" else f"metric_library.{table_name}"
            add_row(ws, row_idx, [
                full_table,
                desc,
                purpose,
                regulatory,
                layer_name,
                tier,
                pk,
                fk,
            ])

        # Finalize auto-filter range after populating
        ws.auto_filter.ref = f"A1:{get_column_letter(len(COLUMNS))}{len(tables) + 1}"

    # ── Summary tab ──────────────────────────────────────────────────────────
    ws = wb.create_sheet(title="Summary", index=0)
    summary_headers = [
        ("Category", 40),
        ("Count", 12),
        ("Description", 80),
    ]
    for col_idx, (col_name, width) in enumerate(summary_headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = HEADER_ALIGN
        cell.border = THIN_BORDER
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    ws.freeze_panes = "A2"

    summary_data = [
        ("Total Tables", str(len(L1_TABLES) + len(L2_TABLES) + len(L3_TABLES) + len(METRIC_LIBRARY_TABLES)), "Complete count of all tables across all data warehouse layers and the metric library schema"),
        ("L1 - Reference & Master Data", str(len(L1_TABLES)), "Golden source dimensions, master entities (SCD Type 2), hierarchies, regulatory reference tables, and configuration data. Provides stable reference data consumed by all downstream layers."),
        ("L2 - Transactional & Snapshot Data", str(len(L2_TABLES)), "Point-in-time snapshots, event records, and observations capturing the daily state of positions, exposures, collateral, ratings, and credit events. Time-variant data partitioned by as_of_date."),
        ("L3 - Reporting & Analytics", str(len(L3_TABLES)), "Pre-computed cubes, summaries, and dashboard-ready artifacts organized in a tiered execution model (T1 direct -> T2 aggregate -> T3 analytic -> T4 executive). Drives all BI dashboards and regulatory report outputs."),
        ("Metric Library", str(len(METRIC_LIBRARY_TABLES)), "Governed metric definitions, canonical parent metrics, and implementation-specific variants with full sourcing, rollup, validation, and lineage metadata for GSIB metric governance."),
        ("", "", ""),
        ("Architecture Pattern", "Three-Layer DWH", "L1 (reference) + L2 (transactional) + L3 (analytics/reporting) with a separate Metric Library schema for metric governance."),
        ("Regulatory Frameworks Supported", "Multiple", "Basel III/IV (SA, IRB), FR 2590, FR Y-9C, FR Y-14, Call Report, CCAR/DFAST, SCCL (12 CFR 252), BCBS 239, SR 11-7, SR 12-7, SR 15-18, OCC Heightened Standards"),
        ("Data Currency", "SCD Type 2", "L1 master tables implement Slowly Changing Dimension Type 2 with effective_start_date, effective_end_date, and is_current_flag for full historical tracking."),
        ("L3 Execution Tiers", "4 Tiers", "Tier 1 (direct from L1+L2) -> Tier 2 (cross-table aggregates) -> Tier 3 (analytic summaries from T1/T2) -> Tier 4 (executive dashboards)"),
    ]

    for row_idx, (cat, cnt, desc) in enumerate(summary_data, 2):
        fill = ALT_ROW_FILL if row_idx % 2 == 0 else WHITE_FILL
        for col_idx, val in enumerate([cat, cnt, desc], 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = Font(name="Calibri", size=10, bold=(col_idx == 1 and val != ""))
            cell.alignment = BODY_ALIGN
            cell.fill = fill
            cell.border = THIN_BORDER

    return wb


if __name__ == "__main__":
    wb = build_workbook()
    out_path = os.path.join(os.path.dirname(__file__), "..", "GSIB_Data_Model_Dictionary.xlsx")
    out_path = os.path.abspath(out_path)
    wb.save(out_path)
    print(f"Generated: {out_path}")
    print(f"  L1 tables: {len(L1_TABLES)}")
    print(f"  L2 tables: {len(L2_TABLES)}")
    print(f"  L3 tables: {len(L3_TABLES)}")
    print(f"  Metric Library tables: {len(METRIC_LIBRARY_TABLES)}")
    print(f"  Total: {len(L1_TABLES) + len(L2_TABLES) + len(L3_TABLES) + len(METRIC_LIBRARY_TABLES)}")
