#!/usr/bin/env tsx
/**
 * release-tracker-sync.ts
 *
 * Compares current L1/L2/L3 table definitions against a stored snapshot.
 * Reads from data-dictionary.json (the golden source, generated by
 * `npm run db:introspect` from PostgreSQL).
 *
 * If tables or fields were added/removed, appends entries to
 * data/release-entries.json and updates the snapshot.
 *
 * Usage:
 *   npx tsx scripts/release-tracker-sync.ts          # normal run
 *   npx tsx scripts/release-tracker-sync.ts --init    # create initial snapshot (no diff)
 */

import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface FieldInfo {
  name: string;
}

interface TableInfo {
  layer: 'L1' | 'L2' | 'L3';
  tableName: string;
  fields: FieldInfo[];
}

interface Snapshot {
  /** ISO date when snapshot was taken */
  createdAt: string;
  tables: TableInfo[];
}

interface Change {
  layer: 'L1' | 'L2' | 'L3';
  table: string;
  field: string;
  changeType: 'Added' | 'Removed';
  rationale: string;
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ROOT = path.resolve(__dirname, '..');
const SNAPSHOT_PATH = path.join(ROOT, 'scripts', 'release-tracker-snapshot.json');
const DATA_JSON_PATH = path.join(ROOT, 'data', 'release-entries.json');
const DATA_DICT_PATH = path.join(ROOT, 'facility-summary-mvp', 'output', 'data-dictionary', 'data-dictionary.json');

// ---------------------------------------------------------------------------
// Parser — read from data-dictionary.json (golden source)
// ---------------------------------------------------------------------------

interface DataDictField {
  name: string;
  [key: string]: unknown;
}

interface DataDictTable {
  name: string;
  layer?: string;
  fields: DataDictField[];
  [key: string]: unknown;
}

interface DataDictionary {
  L1?: DataDictTable[];
  L2?: DataDictTable[];
  L3?: DataDictTable[];
}

/** Read all current definitions from data-dictionary.json. */
function getCurrentState(): TableInfo[] {
  if (!fs.existsSync(DATA_DICT_PATH)) {
    console.error(`Data dictionary not found at ${DATA_DICT_PATH}`);
    console.error('Run `npm run db:introspect` or `npm run sync:data-model` first.');
    process.exit(1);
  }

  const dict: DataDictionary = JSON.parse(fs.readFileSync(DATA_DICT_PATH, 'utf-8'));
  const tables: TableInfo[] = [];

  for (const layer of ['L1', 'L2', 'L3'] as const) {
    const layerTables = dict[layer] || [];
    for (const t of layerTables) {
      tables.push({
        layer,
        tableName: t.name,
        fields: t.fields.map((f) => ({ name: f.name })),
      });
    }
  }

  return tables;
}

// ---------------------------------------------------------------------------
// Diff engine
// ---------------------------------------------------------------------------

function buildIndex(tables: TableInfo[]): Map<string, Set<string>> {
  const idx = new Map<string, Set<string>>();
  for (const t of tables) {
    const key = `${t.layer}.${t.tableName}`;
    idx.set(key, new Set(t.fields.map((f) => f.name)));
  }
  return idx;
}

function diff(prev: TableInfo[], curr: TableInfo[]): Change[] {
  const prevIdx = buildIndex(prev);
  const currIdx = buildIndex(curr);
  const changes: Change[] = [];
  const today = new Date().toISOString().slice(0, 10);

  // Find added tables and fields
  for (const [key, currFields] of currIdx) {
    const [layer, tableName] = key.split('.') as ['L1' | 'L2' | 'L3', string];
    const prevFields = prevIdx.get(key);

    if (!prevFields) {
      // Entire table is new
      changes.push({
        layer, table: tableName, field: '(new table)', changeType: 'Added',
        rationale: `New ${layer} table added`,
      });
      for (const f of currFields) {
        changes.push({
          layer, table: tableName, field: f, changeType: 'Added',
          rationale: `Field added to new ${layer}.${tableName}`,
        });
      }
    } else {
      // Check for new fields
      for (const f of currFields) {
        if (!prevFields.has(f)) {
          changes.push({
            layer, table: tableName, field: f, changeType: 'Added',
            rationale: `Field added to ${layer}.${tableName}`,
          });
        }
      }
    }
  }

  // Find removed tables and fields
  for (const [key, prevFields] of prevIdx) {
    const [layer, tableName] = key.split('.') as ['L1' | 'L2' | 'L3', string];
    const currFields = currIdx.get(key);

    if (!currFields) {
      // Entire table removed
      changes.push({
        layer, table: tableName, field: '(entire table)', changeType: 'Removed',
        rationale: `${layer} table removed`,
      });
    } else {
      // Check for removed fields
      for (const f of prevFields) {
        if (!currFields.has(f)) {
          changes.push({
            layer, table: tableName, field: f, changeType: 'Removed',
            rationale: `Field removed from ${layer}.${tableName}`,
          });
        }
      }
    }
  }

  return changes;
}

// ---------------------------------------------------------------------------
// Writer — prepend entries to data/release-entries.json
// ---------------------------------------------------------------------------

function appendEntries(changes: Change[]): void {
  const today = new Date().toISOString().slice(0, 10);
  const existing: Record<string, unknown>[] = fs.existsSync(DATA_JSON_PATH)
    ? JSON.parse(fs.readFileSync(DATA_JSON_PATH, 'utf-8'))
    : [];

  const newEntries = changes.map((c) => ({
    date: today,
    layer: c.layer,
    table: c.table,
    field: c.field,
    changeType: c.changeType,
    rationale: c.rationale,
  }));

  // Prepend new entries (newest first)
  const updated = [...newEntries, ...existing];
  fs.writeFileSync(DATA_JSON_PATH, JSON.stringify(updated, null, 2) + '\n', 'utf-8');
}

// ---------------------------------------------------------------------------
// Snapshot I/O
// ---------------------------------------------------------------------------

function loadSnapshot(): Snapshot | null {
  if (!fs.existsSync(SNAPSHOT_PATH)) return null;
  return JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf-8'));
}

function saveSnapshot(tables: TableInfo[]): void {
  const snap: Snapshot = {
    createdAt: new Date().toISOString(),
    tables,
  };
  fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(snap, null, 2) + '\n', 'utf-8');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const isInit = process.argv.includes('--init');
  const current = getCurrentState();

  if (isInit) {
    saveSnapshot(current);
    const tableCount = current.length;
    const fieldCount = current.reduce((n, t) => n + t.fields.length, 0);
    console.log(`Baseline snapshot saved: ${tableCount} tables, ${fieldCount} fields`);
    return;
  }

  const prev = loadSnapshot();
  if (!prev) {
    console.log('No snapshot found. Run with --init to create baseline.');
    console.log('  npx tsx scripts/release-tracker-sync.ts --init');
    process.exit(1);
  }

  const changes = diff(prev.tables, current);

  if (changes.length === 0) {
    console.log('No data model changes detected.');
    return;
  }

  console.log(`Detected ${changes.length} change(s):`);
  for (const c of changes) {
    const icon = c.changeType === 'Added' ? '+' : '-';
    console.log(`  ${icon} ${c.layer}.${c.table}.${c.field}`);
  }

  appendEntries(changes);
  saveSnapshot(current);

  console.log(`\nAppended ${changes.length} entries to data/release-entries.json`);
  console.log('Snapshot updated.');
}

main();
