/**
 * L2 table definitions: 26 tables (snapshots, events, attributions) for a GSIB-style bank.
 * All FKs reference L1 (or L2) for referential integrity. Order respects dependencies.
 */
import type { L2TableDef } from './types';

export const L2_TABLES: L2TableDef[] = [
  // ----- Position & exposure -----
  {
    tableName: 'position',
    scd: 'Snapshot',
    columns: [
      { name: 'position_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'facility_id', type: 'BIGINT', nullable: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'instrument_id', type: 'BIGINT', nullable: true, fk: 'l1.instrument_master(instrument_id)' },
      { name: 'position_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'balance_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'source_system_id', type: 'BIGINT', nullable: true, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'accrued_interest_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'book_value_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'contractual_maturity_date', type: 'DATE', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: true },
      { name: 'credit_status_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'effective_date', type: 'DATE', nullable: true },
      { name: 'exposure_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'external_risk_rating', type: 'VARCHAR(100)', nullable: true },
      { name: 'internal_risk_rating', type: 'VARCHAR(100)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'lgd_estimate', type: 'VARCHAR(100)', nullable: true },
      { name: 'market_value_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true },
      { name: 'notional_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'pd_estimate', type: 'VARCHAR(100)', nullable: true },
      { name: 'position_currency', type: 'VARCHAR(100)', nullable: true },
      { name: 'trading_banking_book_flag', type: 'CHAR(1)', nullable: true },
      { name: 'ultimate_parent_id', type: 'BIGINT', nullable: true },
      { name: 'product_node_id', type: 'BIGINT', nullable: true, fk: 'l1.enterprise_product_taxonomy(product_node_id)' },
    ],
  },
  {
    tableName: 'position_detail',
    scd: 'Snapshot',
    columns: [
      { name: 'position_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'position_id', type: 'BIGINT', nullable: false, fk: 'l2.position(position_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'detail_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'cash_leg_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'ccf', type: 'VARCHAR(100)', nullable: true },
      { name: 'current_balance', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'days_past_due', type: 'INTEGER', nullable: true },
      { name: 'delinquency_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'derivative_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'fair_value', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'funded_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'haircut_applied_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'insured_balance', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'interest_rate', type: 'DECIMAL(8,6)', nullable: true },
      { name: 'mark_to_market', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'origination_date', type: 'DATE', nullable: true },
      { name: 'pfe', type: 'VARCHAR(100)', nullable: true },
      { name: 'quantity', type: 'INTEGER', nullable: true },
      { name: 'rate_index', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'rate_type', type: 'CHAR(1)', nullable: true },
      { name: 'replacement_cost', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'sft_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'spread_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'total_commitment', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'unfunded_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'unrealized_gain_loss', type: 'VARCHAR(100)', nullable: true },
      // L3 procedure compatibility
      { name: 'product_node_id', type: 'BIGINT', nullable: true },
      { name: 'exposure_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'notional_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'credit_conversion_factor', type: 'DECIMAL(10,6)', nullable: true },
      { name: 'lgd_pct', type: 'DECIMAL(10,6)', nullable: true },
      { name: 'risk_weight_pct', type: 'DECIMAL(10,6)', nullable: true },
      { name: 'delinquent_payment_flag', type: 'CHAR(1)', nullable: true },
      { name: 'overdue_amt_0_30', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'overdue_amt_31_60', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'overdue_amt_61_90_plus', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'exposure_counterparty_attribution',
    scd: 'Snapshot',
    columns: [
      { name: 'attribution_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'exposure_type_id', type: 'BIGINT', nullable: false, fk: 'l1.exposure_type_dim(exposure_type_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'exposure_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'attributed_exposure_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'attribution_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'counterparty_role_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true },
      { name: 'is_risk_shifted_flag', type: 'CHAR(1)', nullable: true },
      { name: 'risk_shifted_from_counterparty_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'facility_exposure_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'exposure_type_id', type: 'BIGINT', nullable: false, fk: 'l1.exposure_type_dim(exposure_type_id)' },
      { name: 'drawn_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'committed_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'undrawn_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'coverage_ratio_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'exposure_amount_local', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'facility_exposure_id', type: 'BIGINT', nullable: true },
      { name: 'fr2590_category_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'gross_exposure_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'net_exposure_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'product_node_id', type: 'BIGINT', nullable: true },
      // L3 procedure compatibility: same as drawn_amount / undrawn_amount
      { name: 'outstanding_balance_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'undrawn_commitment_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'number_of_loans', type: 'INTEGER', nullable: true },
      { name: 'number_of_facilities', type: 'INTEGER', nullable: true },
      { name: 'days_until_maturity', type: 'INTEGER', nullable: true },
      { name: 'facility_utilization_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'limit_status_code', type: 'VARCHAR(30)', nullable: true },
      { name: 'rwa_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'internal_risk_rating_bucket_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.internal_risk_rating_bucket_dim(internal_risk_rating_bucket_code)' },
    ],
  },
  {
    tableName: 'netting_set_exposure_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'netting_set_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.netting_set(netting_set_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'netted_exposure_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'gross_exposure_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'collateral_held_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'gross_mtm_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'legal_entity_id', type: 'BIGINT', nullable: true },
      { name: 'netting_set_exposure_id', type: 'BIGINT', nullable: true },
      { name: 'pfe_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'netting_benefit_amt', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'facility_lob_attribution',
    scd: 'Snapshot',
    columns: [
      { name: 'attribution_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: false, fk: 'l1.enterprise_business_taxonomy(managed_segment_id)' },
      { name: 'attribution_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'attributed_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'attribution_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'attribution_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'lob_node_id', type: 'BIGINT', nullable: true },
      { name: 'hierarchy_id', type: 'VARCHAR(64)', nullable: true },
    ],
  },
  {
    tableName: 'collateral_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'collateral_asset_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.collateral_asset_master(collateral_asset_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'valuation_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'haircut_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'eligible_collateral_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'allocated_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'collateral_snapshot_id', type: 'BIGINT', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'crm_type_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'current_valuation_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true },
      { name: 'mitigant_group_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'mitigant_subtype', type: 'VARCHAR(100)', nullable: true },
      { name: 'original_valuation_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'risk_shifting_flag', type: 'CHAR(1)', nullable: true },
    ],
  },
  {
    tableName: 'cash_flow',
    scd: 'Event',
    columns: [
      { name: 'cash_flow_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'cash_flow_date', type: 'DATE', nullable: false },
      { name: 'cash_flow_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'contractual_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'contractual_amt_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'flow_date', type: 'DATE', nullable: true },
      { name: 'flow_direction', type: 'VARCHAR(100)', nullable: true },
      { name: 'flow_id', type: 'BIGINT', nullable: true },
      { name: 'flow_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'maturity_bucket_id', type: 'BIGINT', nullable: true },
      { name: 'position_id', type: 'BIGINT', nullable: true },
    ],
  },
  // ----- Facility financial snapshots -----
  {
    tableName: 'facility_financial_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'noi_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'total_debt_service_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'revenue_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'operating_expense_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'ebitda_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'interest_expense_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'principal_payment_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'reporting_period', type: 'VARCHAR(20)', nullable: true },
      { name: 'financial_snapshot_id', type: 'BIGINT', nullable: true },
      { name: 'dscr_value', type: 'DECIMAL(12,6)', nullable: true },
      { name: 'ltv_pct', type: 'DECIMAL(10,6)', nullable: true },
      { name: 'net_income_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'interest_rate_sensitivity_pct', type: 'DECIMAL(10,6)', nullable: true },
    ],
  },
  // ----- Facility snapshots -----
  {
    tableName: 'facility_delinquency_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'credit_status_code', type: 'BIGINT', nullable: false, fk: 'l1.credit_status_dim(credit_status_code)' },
      { name: 'days_past_due', type: 'INTEGER', nullable: true },
      { name: 'watch_list_flag', type: 'CHAR(1)', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'days_past_due_max', type: 'INTEGER', nullable: true },
      { name: 'delinquency_bucket_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'delinquency_snapshot_id', type: 'BIGINT', nullable: true },
      { name: 'delinquency_status_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'last_payment_received_date', type: 'DATE', nullable: true },
      { name: 'overdue_interest_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'overdue_principal_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'delinquent_payment_flag', type: 'CHAR(1)', nullable: true },
      { name: 'overdue_amt_0_30', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'overdue_amt_31_60', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'overdue_amt_61_90_plus', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'facility_pricing_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'spread_bps', type: 'DECIMAL(10,2)', nullable: true },
      { name: 'rate_index_id', type: 'BIGINT', nullable: true, fk: 'l1.interest_rate_index_dim(rate_index_id)' },
      { name: 'all_in_rate_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'floor_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'base_rate_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'facility_pricing_id', type: 'BIGINT', nullable: true },
      { name: 'min_spread_threshold_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'payment_frequency', type: 'VARCHAR(30)', nullable: true },
      { name: 'prepayment_penalty_flag', type: 'CHAR(1)', nullable: true },
      { name: 'rate_cap_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'rate_index_code', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'pricing_tier', type: 'VARCHAR(20)', nullable: true, fk: 'l1.pricing_tier_dim(pricing_tier_code)' },
      { name: 'pricing_exception_flag', type: 'CHAR(1)', nullable: true },
      { name: 'fee_rate_pct', type: 'DECIMAL(10,6)', nullable: true },
    ],
  },
  {
    tableName: 'facility_profitability_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'facility_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'nii_ytd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'fee_income_ytd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'ledger_account_id', type: 'BIGINT', nullable: true, fk: 'l1.ledger_account_dim(ledger_account_id)' },
      { name: 'allocated_equity_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'avg_earning_assets_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'base_currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'fee_income_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'interest_expense_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'interest_income_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'profitability_snapshot_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'limit_contribution_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'limit_rule_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.limit_rule(limit_rule_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'contribution_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'contribution_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'contribution_id', type: 'BIGINT', nullable: true },
      { name: 'contribution_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'limit_utilization_event',
    scd: 'Snapshot',
    columns: [
      { name: 'limit_rule_id', type: 'BIGINT', nullable: false, pk: true, fk: 'l1.limit_rule(limit_rule_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'utilized_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'available_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'reporting_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'utilization_event_id', type: 'BIGINT', nullable: true },
      { name: 'utilized_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  // ----- Amendments -----
  {
    tableName: 'amendment_change_detail',
    scd: 'Event',
    columns: [
      { name: 'change_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'amendment_id', type: 'BIGINT', nullable: false, fk: 'l2.amendment_event(amendment_id)' },
      { name: 'change_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'old_value', type: 'TEXT', nullable: true },
      { name: 'new_value', type: 'TEXT', nullable: true },
      { name: 'amendment_event_id', type: 'BIGINT', nullable: true },
      { name: 'change_currency_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'change_field_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'change_seq', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'amendment_event',
    scd: 'Event',
    columns: [
      { name: 'amendment_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: false, fk: 'l1.credit_agreement_master(credit_agreement_id)' },
      { name: 'amendment_type_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.amendment_type_dim(amendment_type_code)' },
      { name: 'amendment_status_code', type: 'VARCHAR(20)', nullable: false, fk: 'l1.amendment_status_dim(amendment_status_code)' },
      { name: 'effective_date', type: 'DATE', nullable: true },
      { name: 'event_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'amendment_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'amendment_event_id', type: 'BIGINT', nullable: true },
      { name: 'amendment_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'amendment_subtype', type: 'VARCHAR(100)', nullable: true },
      { name: 'amendment_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'completed_date', type: 'DATE', nullable: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true },
      { name: 'identified_date', type: 'DATE', nullable: true },
      { name: 'last_updated_ts', type: 'TIMESTAMP', nullable: true },
    ],
  },
  // ----- Credit events -----
  {
    tableName: 'credit_event',
    scd: 'Event',
    columns: [
      { name: 'credit_event_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'credit_event_type_code', type: 'BIGINT', nullable: false, fk: 'l1.credit_event_type_dim(credit_event_type_code)' },
      { name: 'event_date', type: 'DATE', nullable: false },
      { name: 'event_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'default_definition_id', type: 'BIGINT', nullable: true, fk: 'l1.default_definition_dim(default_definition_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'event_risk_rating', type: 'VARCHAR(100)', nullable: true },
      { name: 'event_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'event_summary', type: 'VARCHAR(2000)', nullable: true },
      { name: 'loss_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'recovery_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'credit_event_facility_link',
    scd: 'Event',
    columns: [
      { name: 'link_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'credit_event_id', type: 'BIGINT', nullable: false, fk: 'l2.credit_event(credit_event_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: false, fk: 'l1.facility_master(facility_id)' },
      { name: 'exposure_at_default', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'as_of_date', type: 'DATE', nullable: true },
      { name: 'estimated_loss_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'impact_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  // ----- Stress test -----
  {
    tableName: 'stress_test_breach',
    scd: 'Event',
    columns: [
      { name: 'breach_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'scenario_id', type: 'BIGINT', nullable: false, fk: 'l1.scenario_dim(scenario_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'limit_rule_id', type: 'BIGINT', nullable: true, fk: 'l1.limit_rule(limit_rule_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'breach_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'breach_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'breach_severity', type: 'VARCHAR(100)', nullable: true },
      { name: 'control_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'control_owner', type: 'VARCHAR(100)', nullable: true },
      { name: 'failure_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'stress_test_result_id', type: 'BIGINT', nullable: true },
    ],
  },
  {
    tableName: 'stress_test_result',
    scd: 'Snapshot',
    columns: [
      { name: 'result_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'scenario_id', type: 'BIGINT', nullable: false, fk: 'l1.scenario_dim(scenario_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'portfolio_id', type: 'BIGINT', nullable: true, fk: 'l1.portfolio_dim(portfolio_id)' },
      { name: 'loss_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'pnl_impact', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'capital_impact_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'execution_date', type: 'DATE', nullable: true },
      { name: 'expected_loss_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'result_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'result_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'scenario_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'stress_test_result_id', type: 'BIGINT', nullable: true },
      { name: 'total_breaches', type: 'INTEGER', nullable: true },
      { name: 'total_exposure_usd', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
  {
    tableName: 'deal_pipeline_fact',
    scd: 'Event',
    columns: [
      { name: 'pipeline_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'stage_code', type: 'VARCHAR(50)', nullable: true },
      { name: 'proposed_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'expected_all_in_rate_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'expected_close_date', type: 'DATE', nullable: true },
      { name: 'expected_committed_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'expected_coverage_ratio', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'expected_exposure_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'expected_internal_risk_grade', type: 'VARCHAR(255)', nullable: true },
      { name: 'expected_spread_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'expected_tenor_months', type: 'VARCHAR(255)', nullable: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'pipeline_deal_id', type: 'BIGINT', nullable: true },
      { name: 'pipeline_stage', type: 'VARCHAR(100)', nullable: true },
      { name: 'pipeline_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'record_level_code', type: 'VARCHAR(20)', nullable: true },
    ],
  },
  // ----- Ratings & metrics -----
  {
    tableName: 'counterparty_rating_observation',
    scd: 'Snapshot',
    columns: [
      { name: 'observation_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'rating_grade_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_grade_dim(rating_grade_id)' },
      { name: 'rating_source_id', type: 'BIGINT', nullable: false, fk: 'l1.rating_source(rating_source_id)' },
      { name: 'is_internal_flag', type: 'CHAR(1)', nullable: true },
      { name: 'pd_implied', type: 'VARCHAR(100)', nullable: true },
      { name: 'prior_rating_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'rating_agency', type: 'VARCHAR(100)', nullable: true },
      { name: 'rating_date', type: 'DATE', nullable: true },
      { name: 'rating_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'rating_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'risk_rating_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'risk_rating_change_steps', type: 'INTEGER', nullable: true },
    ],
  },
  {
    tableName: 'financial_metric_observation',
    scd: 'Snapshot',
    columns: [
      { name: 'observation_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'facility_id', type: 'BIGINT', nullable: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'metric_definition_id', type: 'BIGINT', nullable: false, fk: 'l1.metric_definition_dim(metric_definition_id)' },
      { name: 'value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'context_id', type: 'BIGINT', nullable: true, fk: 'l1.context_dim(context_id)' },
      { name: 'credit_agreement_id', type: 'BIGINT', nullable: true },
      { name: 'metric_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'metric_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'metric_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'metric_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'metric_value_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'period_end_date', type: 'DATE', nullable: true },
    ],
  },
  {
    tableName: 'metric_threshold',
    scd: 'SCD-1',
    columns: [
      { name: 'threshold_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'metric_definition_id', type: 'BIGINT', nullable: false, fk: 'l1.metric_definition_dim(metric_definition_id)' },
      { name: 'threshold_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'threshold_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'effective_from_date', type: 'DATE', nullable: true },
      { name: 'effective_to_date', type: 'DATE', nullable: true },
      { name: 'active_flag', type: 'CHAR(1)', nullable: true },
      { name: 'inner_threshold_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'last_threshold_updated_date', type: 'DATE', nullable: true },
      { name: 'limit_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'limit_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'lod1_sponsor', type: 'VARCHAR(100)', nullable: true },
      { name: 'lod2_sponsor', type: 'VARCHAR(100)', nullable: true },
      { name: 'metric_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'metric_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'metric_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'metric_id_display', type: 'VARCHAR(100)', nullable: true },
      { name: 'metric_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'metric_owner', type: 'VARCHAR(100)', nullable: true },
      { name: 'metric_threshold_id', type: 'BIGINT', nullable: true },
      { name: 'outer_threshold_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'report_deadline', type: 'VARCHAR(100)', nullable: true },
      { name: 'report_frequency', type: 'VARCHAR(30)', nullable: true },
    ],
  },
  {
    tableName: 'exception_event',
    scd: 'Event',
    columns: [
      { name: 'exception_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'exception_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'raised_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'resolved_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'actual_remediation_date', type: 'DATE', nullable: true },
      { name: 'approver', type: 'VARCHAR(100)', nullable: true },
      { name: 'breach_amount_usd', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'breach_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'days_open', type: 'INTEGER', nullable: true },
      { name: 'exception_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'exception_owner', type: 'VARCHAR(100)', nullable: true },
      { name: 'exception_severity', type: 'VARCHAR(100)', nullable: true },
      { name: 'exception_status', type: 'VARCHAR(30)', nullable: true },
      { name: 'exception_value', type: 'DECIMAL(18,4)', nullable: true },
      { name: 'identified_date', type: 'DATE', nullable: true },
      { name: 'limit_rule_id', type: 'BIGINT', nullable: true },
      { name: 'lob_segment_id', type: 'BIGINT', nullable: true },
      { name: 'lod_sponsor', type: 'VARCHAR(100)', nullable: true },
      { name: 'metric_threshold_id', type: 'BIGINT', nullable: true },
      { name: 'remediation_plan', type: 'VARCHAR(2000)', nullable: true },
      { name: 'target_remediation_date', type: 'DATE', nullable: true },
      { name: 'threshold_value', type: 'DECIMAL(18,4)', nullable: true },
    ],
  },
  {
    tableName: 'risk_flag',
    scd: 'Event',
    columns: [
      { name: 'risk_flag_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'facility_id', type: 'BIGINT', nullable: true, fk: 'l1.facility_master(facility_id)' },
      { name: 'counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'flag_type', type: 'VARCHAR(50)', nullable: false },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'raised_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'cleared_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'created_ts', type: 'TIMESTAMP', nullable: true },
      { name: 'flag_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'flag_description', type: 'VARCHAR(2000)', nullable: true },
      { name: 'flag_scope', type: 'VARCHAR(30)', nullable: true },
      { name: 'flag_severity', type: 'VARCHAR(100)', nullable: true },
      { name: 'flag_trigger_value', type: 'DECIMAL(18,4)', nullable: true },
    ],
  },
  {
    tableName: 'data_quality_score_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'score_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'target_table', type: 'VARCHAR(100)', nullable: true },
      { name: 'source_system_id', type: 'BIGINT', nullable: true, fk: 'l1.source_system_registry(source_system_id)' },
      { name: 'completeness_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'validity_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'overall_score', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'dimension_id', type: 'BIGINT', nullable: true },
      { name: 'dimension_name', type: 'VARCHAR(200)', nullable: true },
      { name: 'dq_score_id', type: 'BIGINT', nullable: true },
      { name: 'dq_score_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'impact_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'impacted_report_codes', type: 'VARCHAR(20)', nullable: true },
      { name: 'issue_count', type: 'INTEGER', nullable: true },
      { name: 'reconciliation_break_count', type: 'INTEGER', nullable: true },
      { name: 'score_dimension', type: 'VARCHAR(30)', nullable: true },
    ],
  },
  // ═══════════════════════════════════════════════════════════════════════
  // PRODUCT-SPECIFIC POSITION EXTENSION TABLES
  // These extend the generic position/position_detail with product-specific
  // attributes. The generic position table remains the master header.
  // ═══════════════════════════════════════════════════════════════════════
  {
    tableName: 'loan_position_detail',
    scd: 'Snapshot',
    columns: [
      { name: 'loan_position_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'position_id', type: 'BIGINT', nullable: false, fk: 'l2.position(position_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'loan_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'amortization_type', type: 'VARCHAR(30)', nullable: true },
      { name: 'payment_frequency', type: 'VARCHAR(20)', nullable: true },
      { name: 'interest_rate_type', type: 'VARCHAR(20)', nullable: true },
      { name: 'current_rate_pct', type: 'DECIMAL(8,6)', nullable: true },
      { name: 'rate_index_code', type: 'VARCHAR(30)', nullable: true },
      { name: 'spread_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'original_balance_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'current_balance_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'funded_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'unfunded_commitment_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'days_past_due', type: 'INTEGER', nullable: true },
      { name: 'accrual_status', type: 'VARCHAR(20)', nullable: true },
      { name: 'next_payment_date', type: 'DATE', nullable: true },
      { name: 'prepayment_penalty_flag', type: 'CHAR(1)', nullable: true },
      { name: 'collateral_coverage_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'covenant_compliance_flag', type: 'CHAR(1)', nullable: true },
      { name: 'hqla_eligible_flag', type: 'CHAR(1)', nullable: true },
      { name: 'lcr_outflow_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'nsfr_factor_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'capital_risk_weight_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'derivative_position_detail',
    scd: 'Snapshot',
    columns: [
      { name: 'derivative_position_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'position_id', type: 'BIGINT', nullable: false, fk: 'l2.position(position_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'derivative_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'derivative_subtype', type: 'VARCHAR(50)', nullable: true },
      { name: 'underlying_asset_class', type: 'VARCHAR(50)', nullable: true },
      { name: 'notional_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'mark_to_market_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'replacement_cost_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'potential_future_exposure_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'exposure_at_default_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'cva_charge_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true, fk: 'l1.netting_set(netting_set_id)' },
      { name: 'collateral_posted_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'collateral_received_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'initial_margin_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'variation_margin_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'settlement_type', type: 'VARCHAR(20)', nullable: true },
      { name: 'clearing_method', type: 'VARCHAR(30)', nullable: true },
      { name: 'is_centrally_cleared_flag', type: 'CHAR(1)', nullable: true },
      { name: 'trade_date', type: 'DATE', nullable: true },
      { name: 'effective_date', type: 'DATE', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'sa_ccr_exposure_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'capital_risk_weight_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'lcr_outflow_category', type: 'VARCHAR(50)', nullable: true },
    ],
  },
  {
    tableName: 'sft_position_detail',
    scd: 'Snapshot',
    columns: [
      { name: 'sft_position_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'position_id', type: 'BIGINT', nullable: false, fk: 'l2.position(position_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'sft_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'sft_subtype', type: 'VARCHAR(50)', nullable: true },
      { name: 'cash_leg_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'security_leg_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'collateral_value_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'haircut_applied_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'margin_call_frequency', type: 'VARCHAR(20)', nullable: true },
      { name: 'repo_rate_pct', type: 'DECIMAL(8,6)', nullable: true },
      { name: 'netting_set_id', type: 'BIGINT', nullable: true, fk: 'l1.netting_set(netting_set_id)' },
      { name: 'settlement_date', type: 'DATE', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'is_open_maturity_flag', type: 'CHAR(1)', nullable: true },
      { name: 'security_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'security_issuer_country', type: 'VARCHAR(20)', nullable: true },
      { name: 'hqla_eligible_flag', type: 'CHAR(1)', nullable: true },
      { name: 'lcr_inflow_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'nsfr_factor_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'capital_risk_weight_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'guarantee_lc_position_detail',
    scd: 'Snapshot',
    columns: [
      { name: 'guarantee_lc_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'position_id', type: 'BIGINT', nullable: false, fk: 'l2.position(position_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'instrument_type', type: 'VARCHAR(30)', nullable: true },
      { name: 'guarantee_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'lc_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'issued_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'outstanding_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'utilized_amount', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'credit_conversion_factor', type: 'DECIMAL(10,6)', nullable: true },
      { name: 'beneficiary_counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'expiry_date', type: 'DATE', nullable: true },
      { name: 'is_irrevocable_flag', type: 'CHAR(1)', nullable: true },
      { name: 'is_financial_standby_flag', type: 'CHAR(1)', nullable: true },
      { name: 'fee_rate_bps', type: 'DECIMAL(8,2)', nullable: true },
      { name: 'lcr_outflow_category', type: 'VARCHAR(50)', nullable: true },
      { name: 'capital_risk_weight_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'bond_security_position_detail',
    scd: 'Snapshot',
    columns: [
      { name: 'bond_security_detail_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'position_id', type: 'BIGINT', nullable: false, fk: 'l2.position(position_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'security_type', type: 'VARCHAR(50)', nullable: true },
      { name: 'security_subtype', type: 'VARCHAR(50)', nullable: true },
      { name: 'isin', type: 'VARCHAR(12)', nullable: true },
      { name: 'cusip', type: 'VARCHAR(9)', nullable: true },
      { name: 'face_value_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'market_value_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'book_value_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'accrued_interest_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'unrealized_gain_loss_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'coupon_rate_pct', type: 'DECIMAL(8,6)', nullable: true },
      { name: 'coupon_frequency', type: 'VARCHAR(20)', nullable: true },
      { name: 'maturity_date', type: 'DATE', nullable: true },
      { name: 'issuer_counterparty_id', type: 'BIGINT', nullable: true, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'issuer_country_code', type: 'VARCHAR(20)', nullable: true },
      { name: 'accounting_classification', type: 'VARCHAR(30)', nullable: true },
      { name: 'hqla_level', type: 'VARCHAR(10)', nullable: true },
      { name: 'hqla_eligible_flag', type: 'CHAR(1)', nullable: true },
      { name: 'lcr_haircut_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'nsfr_factor_pct', type: 'DECIMAL(10,4)', nullable: true },
      { name: 'capital_risk_weight_pct', type: 'DECIMAL(10,4)', nullable: true },
    ],
  },
  {
    tableName: 'counterparty_financial_snapshot',
    scd: 'Snapshot',
    columns: [
      { name: 'financial_snapshot_id', type: 'BIGINT', nullable: false, pk: true },
      { name: 'counterparty_id', type: 'BIGINT', nullable: false, fk: 'l1.counterparty(counterparty_id)' },
      { name: 'as_of_date', type: 'DATE', nullable: false },
      { name: 'reporting_period', type: 'VARCHAR(20)', nullable: true },
      { name: 'currency_code', type: 'VARCHAR(20)', nullable: true, fk: 'l1.currency_dim(currency_code)' },
      { name: 'revenue_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'operating_expense_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'net_income_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'interest_expense_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'tax_expense_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'depreciation_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'amortization_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'total_assets_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'total_liabilities_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'shareholders_equity_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'ebitda_amt', type: 'DECIMAL(18,2)', nullable: true },
      { name: 'noi_amt', type: 'DECIMAL(18,2)', nullable: true },
    ],
  },
];
